### ISSUE TITLE
[错误报告]: docker容器启动，自动升级后，无法启动

### ISSUE THREAD

**Issue by wangke8023** [jxxghp/MoviePilot#1040]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

原本是1.3.8版本，启动容器，观察日志，提示升级到1.3.9，然后就反复版本提示如下方日志

### 发生问题时系统日志和配置文件

```bash
2023-11-02 10:35:48 moviepilot  | 不使用代理更新程序
2023-11-02 10:35:48 moviepilot  | 当前版本号：v1.3.9
2023-11-02 10:35:53 moviepilot  | 最新版本号：v1.3.9
2023-11-02 10:35:53 moviepilot  | 未发现新版本，跳过更新步骤...
2023-11-02 10:35:53 moviepilot  | usermod: no changes
2023-11-02 10:35:54 moviepilot  | Traceback (most recent call last):
2023-11-02 10:35:54 moviepilot  |   File "/app/app/main.py", line 21, in <module>
2023-11-02 10:35:54 moviepilot  |     from app.core.plugin import PluginManager
2023-11-02 10:35:54 moviepilot  |   File "/app/app/core/plugin.py", line 9, in <module>
2023-11-02 10:35:54 moviepilot  |     from app.helper.sites import SitesHelper
2023-11-02 10:35:54 moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
2023-11-02 10:36:55 moviepilot  | 不使用代理更新程序
2023-11-02 10:36:55 moviepilot  | 当前版本号：v1.3.9
2023-11-02 10:36:59 moviepilot  | 最新版本号：v1.3.9
2023-11-02 10:36:59 moviepilot  | 未发现新版本，跳过更新步骤...
2023-11-02 10:36:59 moviepilot  | usermod: no changes
2023-11-02 10:37:00 moviepilot  | Traceback (most recent call last):
2023-11-02 10:37:00 moviepilot  |   File "/app/app/main.py", line 21, in <module>
2023-11-02 10:37:00 moviepilot  |     from app.core.plugin import PluginManager
2023-11-02 10:37:00 moviepilot  |   File "/app/app/core/plugin.py", line 9, in <module>
2023-11-02 10:37:00 moviepilot  |     from app.helper.sites import SitesHelper
2023-11-02 10:37:00 moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
2023-11-02 10:38:01 moviepilot  | 不使用代理更新程序
2023-11-02 10:38:01 moviepilot  | 当前版本号：v1.3.9
2023-11-02 10:38:05 moviepilot  | 最新版本号：v1.3.9
2023-11-02 10:38:05 moviepilot  | 未发现新版本，跳过更新步骤...
2023-11-02 10:38:06 moviepilot  | usermod: no changes
2023-11-02 10:38:07 moviepilot  | Traceback (most recent call last):
2023-11-02 10:38:07 moviepilot  |   File "/app/app/main.py", line 21, in <module>
2023-11-02 10:38:07 moviepilot  |     from app.core.plugin import PluginManager
2023-11-02 10:38:07 moviepilot  |   File "/app/app/core/plugin.py", line 9, in <module>
2023-11-02 10:38:07 moviepilot  |     from app.helper.sites import SitesHelper
2023-11-02 10:38:07 moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
2023-11-02 10:39:07 moviepilot  | 不使用代理更新程序
2023-11-02 10:39:07 moviepilot  | 当前版本号：v1.3.9
2023-11-02 10:39:12 moviepilot  | 最新版本号：v1.3.9
2023-11-02 10:39:12 moviepilot  | 未发现新版本，跳过更新步骤...
2023-11-02 10:39:12 moviepilot  | usermod: no changes
2023-11-02 10:39:13 moviepilot  | Traceback (most recent call last):
2023-11-02 10:39:13 moviepilot  |   File "/app/app/main.py", line 21, in <module>
2023-11-02 10:39:13 moviepilot  |     from app.core.plugin import PluginManager
2023-11-02 10:39:13 moviepilot  |   File "/app/app/core/plugin.py", line 9, in <module>
2023-11-02 10:39:13 moviepilot  |     from app.helper.sites import SitesHelper
2023-11-02 10:39:13 moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
2023-11-02 10:40:14 moviepilot  | 不使用代理更新程序
2023-11-02 10:40:14 moviepilot  | 当前版本号：v1.3.9
2023-11-02 10:40:18 moviepilot  | 最新版本号：v1.3.9
2023-11-02 10:40:18 moviepilot  | 未发现新版本，跳过更新步骤...
2023-11-02 10:40:18 moviepilot  | usermod: no changes
2023-11-02 10:40:19 moviepilot  | Traceback (most recent call last):
2023-11-02 10:40:19 moviepilot  |   File "/app/app/main.py", line 21, in <module>
2023-11-02 10:40:19 moviepilot  |     from app.core.plugin import PluginManager
2023-11-02 10:40:19 moviepilot  |   File "/app/app/core/plugin.py", line 9, in <module>
2023-11-02 10:40:19 moviepilot  |     from app.helper.sites import SitesHelper
2023-11-02 10:40:19 moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
2023-11-02 10:41:20 moviepilot  | 不使用代理更新程序
2023-11-02 10:41:20 moviepilot  | 当前版本号：v1.3.9
2023-11-02 10:41:24 moviepilot  | 最新版本号：v1.3.9
2023-11-02 10:41:24 moviepilot  | 未发现新版本，跳过更新步骤...
2023-11-02 10:41:24 moviepilot  | usermod: no changes
2023-11-02 10:41:25 moviepilot  | Traceback (most recent call last):
2023-11-02 10:41:25 moviepilot  |   File "/app/app/main.py", line 21, in <module>
2023-11-02 10:41:25 moviepilot  |     from app.core.plugin import PluginManager
2023-11-02 10:41:25 moviepilot  |   File "/app/app/core/plugin.py", line 9, in <module>
2023-11-02 10:41:25 moviepilot  |     from app.helper.sites import SitesHelper
2023-11-02 10:41:25 moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
2023-11-02 10:42:26 moviepilot  | 不使用代理更新程序
2023-11-02 10:42:26 moviepilot  | 当前版本号：v1.3.9
2023-11-02 10:42:31 moviepilot  | 最新版本号：v1.3.9
2023-11-02 10:42:31 moviepilot  | 未发现新版本，跳过更新步骤...
2023-11-02 10:42:31 moviepilot  | usermod: no changes
2023-11-02 10:42:32 moviepilot  | Traceback (most recent call last):
2023-11-02 10:42:32 moviepilot  |   File "/app/app/main.py", line 21, in <module>
2023-11-02 10:42:32 moviepilot  |     from app.core.plugin import PluginManager
2023-11-02 10:42:32 moviepilot  |   File "/app/app/core/plugin.py", line 9, in <module>
2023-11-02 10:42:32 moviepilot  |     from app.helper.sites import SitesHelper
2023-11-02 10:42:32 moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
moviepilot exited with code 1
```

**Comment by a928230991** [comment]
重新拉去镜像，可以先改为1.3.8，启动后再改为1.3.9，或者其他重置镜像一类的

**Comment by jxxghp** [comment]
不看更新说明的吗？
