### ISSUE TITLE
[错误报告]: Ubuntu使用Docker-compose启动会提示sql database is locked

### ISSUE THREAD

**Issue by sunshinenny** [jxxghp/MoviePilot#1055]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

lasted

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

如题，错误提示如下

感谢作者大大的付出

```shell
moviepilot_1  | Traceback (most recent call last):
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
moviepilot_1  |     self.dialect.do_execute(
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
moviepilot_1  |     cursor.execute(statement, parameters)
moviepilot_1  | sqlite3.OperationalError: database is locked
moviepilot_1  |
moviepilot_1  | The above exception was the direct cause of the following exception:
moviepilot_1  |
moviepilot_1  | Traceback (most recent call last):
moviepilot_1  |   File "/app/app/main.py", line 190, in <module>
moviepilot_1  |     init_db()
moviepilot_1  |   File "/app/app/db/init.py", line 23, in init_db
moviepilot_1  |     Base.metadata.create_all(bind=Engine)
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 5828, in create_all
moviepilot_1  |     bind._run_ddl_visitor(
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3243, in _run_ddl_visitor
moviepilot_1  |     conn._run_ddl_visitor(visitorcallable, element, **kwargs)
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2447, in _run_ddl_visitor
moviepilot_1  |     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 671, in traverse_single
moviepilot_1  |     return meth(obj, **kw)
moviepilot_1  |            ^^^^^^^^^^^^^^^
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 919, in visit_metadata
moviepilot_1  |     self.traverse_single(
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 671, in traverse_single
moviepilot_1  |     return meth(obj, **kw)
moviepilot_1  |            ^^^^^^^^^^^^^^^
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 957, in visit_table
moviepilot_1  |     )._invoke_with(self.connection)
moviepilot_1  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
moviepilot_1  |     return bind.execute(self)
moviepilot_1  |            ^^^^^^^^^^^^^^^^^^
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
moviepilot_1  |     return meth(
moviepilot_1  |            ^^^^^
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
moviepilot_1  |     return connection._execute_ddl(
moviepilot_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1528, in _execute_ddl
moviepilot_1  |     ret = self._execute_context(
moviepilot_1  |           ^^^^^^^^^^^^^^^^^^^^^^
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
moviepilot_1  |     return self._exec_single_context(
moviepilot_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
moviepilot_1  |     self._handle_dbapi_exception(
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
moviepilot_1  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
moviepilot_1  |     self.dialect.do_execute(
moviepilot_1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
moviepilot_1  |     cursor.execute(statement, parameters)
moviepilot_1  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
moviepilot_1  | [SQL:
moviepilot_1  | CREATE TABLE systemconfig (
moviepilot_1  | 	id INTEGER NOT NULL,
moviepilot_1  | 	"key" VARCHAR,
moviepilot_1  | 	value VARCHAR,
moviepilot_1  | 	PRIMARY KEY (id)
moviepilot_1  | )
moviepilot_1  |
moviepilot_1  | ]
```

## Docker-compose
```docker-compose
version: "3"
services:
  moviepilot:
    image: jxxghp/moviepilot:latest
      #image: jxxghp/moviepilot:1.3.4
      #ports:
      #  - 3020:3020 # web 接口
      #  - 3002:3001 # overseerr 接口
    restart: always
    network_mode: host #bridge
    hostname: moviepilot
    volumes:
      #- /mnt/truenas/appdata/docker/moviepilot/main:/moviepilot #程序主目录，必选
      - /mnt/truenas/appdata/docker/moviepilot/config:/config #config 配置文件，必选
        #- /mnt/truenas/appdata/docker/moviepilot/ms-playwright:/moviepilot/.cache/ms-playwright
      - /mnt/truenas/inbox/downloads/视频:/volume1/视频
        #- /mnt/truenas/appdata/docker/moviepilot/nas-tools:/volume1/docker/nas-tools
    environment:
# 基础设置
      - NGINX_PORT=3020
        #- PORT=3021
      - PUID=0
      - PGID=0
      - UMASK=000
      - MOVIEPILOT_AUTO_UPDATE=true   #重启更新
      - PROXY_HOST=http://192.168.31.22:7890 # 代理地址
      - TMDB_API_DOMAIN=api.tmdb.org
      - SUPERUSER=admin   #登录账号
      - SUPERUSER_PASSWORD=打码   #登录密码
      - API_TOKEN=sunshinenny
# 下载目录设置
      - DOWNLOAD_PATH=/volume1/视频   # 下载保存目录
      - DOWNLOAD_CATEGORY=false #下载二级分类开关
      - DOWNLOAD_MOVIE_PATH=/volume1/视频/电影
      - DOWNLOAD_TV_PATH=/volume1/视频/电视剧
      - DOWNLOAD_ANIME_PATH=/volume1/视频/日番
# 媒体库目录设置
      - LIBRARY_PATH=/volume1/视频 #媒体库目录
      - LIBRARY_MOVIE_NAME=电影   #电影目录名
      - LIBRARY_TV_NAME=电视剧    #电视剧目录名
      - LIBRARY_ANIME_NAME=日番   # 动漫目录名
      - LIBRARY_CATEGORY=true    # 媒体库自动分类功能
# 媒体库功能设置
      - DOWNLOAD_SUBTITLE=true  # 下载站点字幕
      - DOWNLOADER_MONITOR=true  # 下载器监控
      - TORRENT_TAG=MOVIEPILOT   #种子标签
      - SCRAP_METADATA=true   # 刮削入库的媒体文件
      - SCRAP_SOURCE=douban   # 刮削入库的媒体文件
      - REFRESH_MEDIASERVER=true    # 入库刷新媒体库
      - TRANSFER_TYPE=move      #转移方式，支持link/copy/move/softlink
# CookieCloud设置
      - COOKIECLOUD_HOST=http://192.168.31.1:8088   #CookieCloud服务器地址 必须添加
      - COOKIECLOUD_KEY=打码 #cc用户KEY
      - COOKIECLOUD_PASSWORD=打码  #cc端对端加密密码
      - COOKIECLOUD_INTERVAL=10  # CookieCloud同步间隔（分钟）
      - USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203    #CookieCloud对应的浏览器UA，可选，同步站点后可以在管理界面中修改
#  消息通知渠道
#      - MESSAGER=slack  #消息通知渠道
# slack通知
#      - SLACK_OAUTH_TOKEN=xoxb-xxx #Slack Bot User OAuth Token
#      - SLACK_APP_TOKEN=xapp-xxx #Slack App-Level Token
#      - SLACK_CHANNEL=  #频道名称，默认全体
# 下载器设置
      - DOWNLOADER:qbittorrent
     ##qbittorrent设置项
      - QB_HOST=http://192.168.31.4:8080 # qbittorrent地址
      - QB_USER=admin #qbittorrent用户名
      - QB_PASSWORD=打码  #qbittorrent密码
# 媒体服务器
#      - MEDIASERVER=plex
#      - PLEX_HOST=http://xxx:32400
#      - PLEX_TOKEN=
#      - MEDIASERVER_SYNC_INTERVAL:6   #媒体服务器同步间隔（小时）
# 用户认证
#      - AUTH_SITE=audiences  #认证站点
#      - AUDIENCES_UID= # 观众 ID
#      - AUDIENCES_PASSKEY= # 观众 passkey
# 其他设置
      - BIG_MEMORY_MODE=false  #大内存模式

```

**Comment by baichenxu06** [comment]
重新构建试试

**Comment by sunshinenny** [comment]
好像是权限不够导致的，感谢回答
