### ISSUE TITLE
[错误报告]: 豆瓣同步插件报错

### ISSUE THREAD

**Issue by echowiz** [jxxghp/MoviePilot#108]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0

### 问题类型

插件问题

### 问题描述

豆瓣同步插件运行时报错，日志如下

### 发生问题时系统日志和配置文件

```bash
moviepilot  | 2023-08-13 19:40:00,461 - base.py -【ERROR】Job "豆瓣想看 (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='0/20'], next run at: 2023-08-13 20:00:00 CST)" raised an exception
moviepilot  | Traceback (most recent call last):
moviepilot  |   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
moviepilot  |     retval = job.func(*job.args, **job.kwargs)
moviepilot  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/app/app/plugins/doubansync/__init__.py", line 462, in sync
moviepilot  |     self.save_data('history', history)
moviepilot  |   File "/app/app/plugins/__init__.py", line 153, in save_data
moviepilot  |     return self.plugindata.save(plugin_id, key, value)
moviepilot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/app/app/db/plugindata_oper.py", line 24, in save
moviepilot  |     plugin = PluginData.get_plugin_data_by_key(self._db, plugin_id, key)
moviepilot  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/app/app/db/models/plugin.py", line 22, in get_plugin_data_by_key
moviepilot  |     return db.query(PluginData).filter(PluginData.plugin_id == plugin_id, PluginData.key == key).first()
moviepilot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2747, in first
```

**Comment by jxxghp** [comment]
日志没贴完整，没看到下面的真正原因

**Comment by DDSDerek** [comment]
```bash
2023-08-13 19:40:00,461 - base.py -【ERROR】Job "豆瓣想看 (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='0/20'], next run at: 2023-08-13 20:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/doubansync/__init__.py", line 462, in sync
    self.save_data('history', history)
  File "/app/app/plugins/__init__.py", line 153, in save_data
    return self.plugindata.save(plugin_id, key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/plugindata_oper.py", line 24, in save
    plugin = PluginData.get_plugin_data_by_key(self._db, plugin_id, key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/models/plugin.py", line 22, in get_plugin_data_by_key
    return db.query(PluginData).filter(PluginData.plugin_id == plugin_id, PluginData.key == key).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2747, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2131, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1998, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 926, in _raise_for_prerequisite_state
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is provisioning a new connection; concurrent operations are not permitted (Background on this error at: https://sqlalche.me/e/20/isce)
```
