### ISSUE TITLE
[错误报告]: 服务启动失败

### ISSUE THREAD

**Issue by anxinJ** [jxxghp/MoviePilot#1081]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

群晖docker-compose方式启动容器。
为了升级到1.4.0，在项目中清除容器，再重新构建、启动。
启动日志中不断重复相同的错误日志**ModuleNotFoundError: No module named 'app.helper.sites'**。
多次清除重新构建不起作用。

### 发生问题时系统日志和配置文件

```bash
2023/11/08
10:26:32
前端程序下载成功
2023/11/08
10:26:33
程序更新成功，前端版本：v1.4.0-1，后端版本：v1.4.0
2023/11/08
10:26:40
Proxy dockerbackend started.
2023/11/08
10:26:40
Proxy dockerfrontend started.
2023/11/08
10:26:50
Traceback (most recent call last):
2023/11/08
10:26:50
  File "/app/app/main.py", line 21, in <module>
2023/11/08
10:26:50
    from app.core.plugin import PluginManager
2023/11/08
10:26:50
  File "/app/app/core/plugin.py", line 9, in <module>
2023/11/08
10:26:50
    from app.helper.sites import SitesHelper
2023/11/08
10:26:50
ModuleNotFoundError: No module named 'app.helper.sites'
2023/11/08
10:26:58
不使用代理更新程序
2023/11/08
10:26:58
当前版本号：v1.4.0
2023/11/08
10:26:59
最新版本号：v1.4.0
2023/11/08
10:26:59
未发现新版本，跳过更新步骤...
2023/11/08
10:27:00
usermod: no changes
2023/11/08
10:27:06
Proxy dockerbackend started.
2023/11/08
10:27:06
Proxy dockerfrontend started.
2023/11/08
10:27:12
Traceback (most recent call last):
2023/11/08
10:27:12
  File "/app/app/main.py", line 21, in <module>
2023/11/08
10:27:12
    from app.core.plugin import PluginManager
2023/11/08
10:27:12
  File "/app/app/core/plugin.py", line 9, in <module>
2023/11/08
10:27:12
    from app.helper.sites import SitesHelper
2023/11/08
10:27:12
ModuleNotFoundError: No module named 'app.helper.sites'
2023/11/08
10:27:20
不使用代理更新程序
2023/11/08
10:27:20
当前版本号：v1.4.0
2023/11/08
10:27:22
最新版本号：v1.4.0
2023/11/08
10:27:22
未发现新版本，跳过更新步骤...
2023/11/08
10:27:22
usermod: no changes
2023/11/08
10:27:27
Proxy dockerbackend started.
2023/11/08
10:27:27
Proxy dockerfrontend started.
2023/11/08
10:27:38
Traceback (most recent call last):
2023/11/08
10:27:38
  File "/app/app/main.py", line 21, in <module>
2023/11/08
10:27:38
    from app.core.plugin import PluginManager
2023/11/08
10:27:38
  File "/app/app/core/plugin.py", line 9, in <module>
2023/11/08
10:27:38
    from app.helper.sites import SitesHelper
2023/11/08
10:27:38
ModuleNotFoundError: No module named 'app.helper.sites'
```

**Comment by anxinJ** [comment]
补充下启动过程的几张截图
![1](https://github.com/jxxghp/MoviePilot/assets/10701711/2e0043e4-f377-4671-a208-19c67f490ee3)
![2](https://github.com/jxxghp/MoviePilot/assets/10701711/a0ea90d4-544a-434e-b6cb-73d0721514c3)
![3](https://github.com/jxxghp/MoviePilot/assets/10701711/618add97-ff51-4ef4-926c-4d8032f98500)
![4](https://github.com/jxxghp/MoviePilot/assets/10701711/ff5c2e1a-b70b-4290-9cba-089798cfffe9)

**Comment by anxinJ** [comment]
`MOVIEPILOT_AUTO_UPDATE=true` 修改为`MOVIEPILOT_AUTO_UPDATE=release`后，启动成功

**Comment by aztdmxb** [comment]
我再25年12月13日碰到了这个问题 MOVIEPILOT_AUTO_UPDATE=release修改为后，启动成功MOVIEPILOT_AUTO_UPDATE=true 后启动成功
