### ISSUE TITLE
[错误报告]: AUTO_UPDATE_RESOURCE默认为true时无法启动

### ISSUE THREAD

**Issue by rotent** [jxxghp/MoviePilot#1136]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

更新1.4.3后无法启动，只有把AUTO_UPDATE_RESOURCE设置为false才可以启动

### 发生问题时系统日志和配置文件

```bash
INFO:    migration.py - Context impl SQLiteImpl.
INFO:    migration.py - Will assume non-transactional DDL.
INFO:     Started server process [68]
INFO:     Waiting for application startup.
INFO:    singleton.py - 站点资源版本：1.0.2
INFO:    singleton.py - 认证资源版本：1.0.2
INFO:    singleton.py - iyuu 用户认证成功！
INFO:    resource.py - 开始检测资源包版本...
INFO:    resource.py - 最新资源包版本：v1.0.3
INFO:    resource.py - user.sites.bin 资源包有更新，最新版本：v1.0.3
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 656, in startup
    handler()
  File "/app/app/main.py", line 175, in start_module
    ResourceHelper()
  File "/app/app/utils/singleton.py", line 13, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/helper/resource.py", line 24, in __init__
    self.check()
  File "/app/app/helper/resource.py", line 97, in check
    file_path.write_bytes(res.content)
  File "/usr/local/lib/python3.11/pathlib.py", line 1067, in write_bytes
    with self.open(mode='wb') as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/app/app/helper'

ERROR:    Application startup failed. Exiting.
不使用代理更新程序
Release 更新模式
当前版本号：v1.4.3
最新版本号：v1.4.3
未发现新版本，跳过更新步骤...
Proxy dockerbackend started.
Proxy dockerfrontend started.
```

**Comment by jxxghp** [comment]
@rotent 重新拉下镜像

**Comment by rotent** [comment]
> @rotent 重新拉下镜像

感谢，解决了
