### ISSUE TITLE
[错误报告]: 插件显示安装成功，但是实际没有插件显示，无法正常使用插件

### ISSUE THREAD

**Issue by Aqr-K** [jxxghp/MoviePilot#1158]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.4

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

使用docker-compose安装
使用第三方插件库后，出现部分插件无法安装的情况，包括第三方插件库是填入官方插件地址来最新版插件的情况下，也是这样
它不是全部无法安装，时不时的出现这种情况，都是显示安装成功，但是插件页面里没变化，
我是用`cloudflare`搭建了一个加速，可以肯定我的插件地址是没问题的，国内环境完全打得开的
试过重启，查看后台日志，显示在线插件也安装成功了，但就是没显示，然后我尝试别人写好的第三方插件，也是有时候启动后能装上，有时候重新安装moviepolit后又不行了

`- PLUGIN_MARKET=https://gh.xxxx.com/https://raw.githubusercontent.com/jxxghp/MoviePilot-Plugins/main/,https://gh.xxxx.com/https://raw.githubusercontent.com/AnjoyLi/MoviePilot-Plugins/main/`
![image](https://github.com/jxxghp/MoviePilot/assets/95741669/1573717d-c770-4e7c-bc25-c2abab5521c2)

### 发生问题时系统日志和配置文件

```bash
INFO:    plugin.py - 开始安装在线插件...
INFO:    plugin.py - 插件 媒体库刮削 安装成功，版本：1.1
INFO:    plugin.py - 插件 媒体文件同步删除 安装成功，版本：1.2
INFO:    plugin.py - 插件 云盘文件删除 安装成功，版本：1.1
INFO:    plugin.py - 插件 QQ消息推送 安装成功，版本：0.1
INFO:    plugin.py - 在线插件安装完成
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3001 (Press CTRL+C to quit)
```

**Comment by jxxghp** [comment]
DEBUG=true，然后发下日志

**Comment by Aqr-K** [comment]
> DEBUG=true，然后发下日志

#### `v1.4.4`
- `官方插件库`
如果远程库比本地库版本更高，会进入安装阶段，过一段时间会显示安装成功，但没有内容
![image](https://github.com/jxxghp/MoviePilot/assets/95741669/07af1955-c59e-4ca2-bb86-f1fb301c4ccd)
![image](https://github.com/jxxghp/MoviePilot/assets/95741669/05483ab5-007b-4093-aa6b-25f6e6b3eee5)

我尝试将所有已安装的插件全部卸载后，进行项目重启
这是重启后的日志记录，会莫名其妙的多出这几个原来安装失败的插件
```
INFO:    plugin.py - 开始安装在线插件...
INFO:    plugin.py - 插件 媒体库刮削 安装成功，版本：1.1
INFO:    plugin.py - 插件 媒体文件同步删除 安装成功，版本：1.2
INFO:    plugin.py - 插件 媒体库服务器通知 安装成功，版本：1.1
```

#### `v1.4.5`
删除原1.4.4项目后重装到1.4.5时，出现无法使用第三方加速后的地址了，显示直接无法连接，但手动尝试打开这些地址还是能连通的

- 远程库变量值
```
PLUGIN_MARKET=https://gh.*****.com/https://raw.githubusercontent.com/jxxghp/MoviePilot-Plugins/main/,https://gh.*****.com/https://raw.githubusercontent.com/AnjoyLi/MoviePilot-Plugins/main/
```
日志
```
INFO:    plugin.py - 开始安装在线插件...
ERROR:   plugin.py - 未获取到在线插件
INFO:    plugin.py - Plugin Loaded：LibraryScraper
INFO:    plugin.py - Plugin Loaded：MediaSyncDel
INFO:    plugin.py - Plugin Loaded：MediaServerMsg
ERROR:   plugin.py - 加载插件 CloudDiskDel 出错：list index out of range - Traceback (most recent call last):
  File "/app/app/core/plugin.py", line 72, in start
    plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
  File "/app/app/plugins/clouddiskdel/__init__.py", line 53, in init_plugin
    self._paths[paths[0]] = paths[1]
                            ~~~~~^^^
IndexError: list index out of range
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3001 (Press CTRL+C to quit)
```

期望的修复结果是：支持第三方加速后的插件地址，这样就不用使用proxy代理了

**Comment by Aqr-K** [comment]
> DEBUG=true，然后发下日志

#### `v1.4.4`
- `官方插件库`
如果远程库比本地库版本更高，会进入安装阶段，过一段时间会显示安装成功，但没有内容
![image](https://github.com/jxxghp/MoviePilot/assets/95741669/07af1955-c59e-4ca2-bb86-f1fb301c4ccd)
![image](https://github.com/jxxghp/MoviePilot/assets/95741669/05483ab5-007b-4093-aa6b-25f6e6b3eee5)


```
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): api.github.com:443
DEBUG:   connectionpool.py - https://api.github.com:443 "GET /repos/jxxghp/MoviePilot-Plugins/contents/plugins/clouddiskdel HTTP/1.1" 200 294
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): api.github.com:443
DEBUG:   connectionpool.py - https://api.github.com:443 "GET /repos/jxxghp/MoviePilot-Plugins/contents/plugins/clouddiskdel HTTP/1.1" 200 294
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:   connectionpool.py - https://raw.githubusercontent.com:443 "GET /jxxghp/MoviePilot-Plugins/main/plugins/clouddiskdel/__init__.py HTTP/1.1" 200 3997
加载模块 clouddiskdel 失败：PluginAction
INFO:     192.168.100.113:0 - "GET /api/v1/plugin/install/CloudDiskDel?repo_url=https:%2F%2Fgh.******.com%2Fhttps:%2F%2Fraw.githubusercontent.com%2Fjxxghp%2FMoviePilot-Plugins%2Fmain%2F&force=true HTTP/1.1" 200 OK
INFO:     192.168.100.113:0 - "GET /api/v1/plugin/ HTTP/1.1" 200 OK
```
失败后直接删除项目重建的日志，
```
INFO:    plugin.py - 开始安装在线插件...
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): gh.204060.xyz:443
DEBUG:   connectionpool.py - https://gh.******.com:443 "GET /https://raw.githubusercontent.com/jxxghp/MoviePilot-Plugins/main/package.json HTTP/1.1" 200 2368
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): gh.204060.xyz:443
DEBUG:   connectionpool.py - https://gh.******.com:443 "GET /https://raw.githubusercontent.com/AnjoyLi/MoviePilot-Plugins/main/package.json HTTP/1.1" 200 230
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): api.github.com:443
DEBUG:   connectionpool.py - https://api.github.com:443 "GET /repos/jxxghp/MoviePilot-Plugins/contents/plugins/libraryscraper HTTP/1.1" 200 296
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): raw.githubusercontent.com:443
INFO:    plugin.py - 插件 媒体库刮削 安装成功，版本：1.1
INFO:    plugin.py - 在线插件安装完成
DEBUG:   event.py - Event Registed：site.signin - AutoSignIn.sign_in
DEBUG:   event.py - Event Registed：site.deleted - AutoSignIn.site_deleted
DEBUG:   event.py - Event Registed：notice.message - BarkMsg.send
DEBUG:   event.py - Event Registed：webhook.message - BestFilmVersion.webhook_message_action
DEBUG:   event.py - Event Registed：user.message - ChatGPT.talk
DEBUG:   event.py - Event Registed：name.recognize - ChatGPT.recognize
DEBUG:   event.py - Event Registed：transfer.complete - ChineseSubFinder.download
DEBUG:   event.py - Event Registed：cloudflare.speedtest - CloudflareSpeedTest.__cloudflareSpeedTest
DEBUG:   event.py - Event Registed：plugin.reload - CustomHosts.reload
DEBUG:   event.py - Event Registed：directory.sync - DirMonitor.remote_sync
DEBUG:   event.py - Event Registed：douban.sync - DoubanSync.remote_sync
DEBUG:   event.py - Event Registed：site.deleted - IYUUAutoSeed.site_deleted
DEBUG:   event.py - Event Registed：notice.message - IyuuMsg.send
DEBUG:   event.py - Event Registed：webhook.message - MediaServerMsg.send
DEBUG:   event.py - Event Registed：transfer.complete - MediaServerRefresh.refresh
DEBUG:   event.py - Event Registed：webhook.message - MediaSyncDel.sync_del_by_webhook
DEBUG:   event.py - Event Registed：webhook.message - MediaSyncDel.sync_del_by_plugin
DEBUG:   event.py - Event Registed：downloadfile.deleted - MediaSyncDel.downloadfile_del_sync
DEBUG:   event.py - Event Registed：notice.message - MessageForward.send
DEBUG:   event.py - Event Registed：transfer.complete - PersonMeta.scrap_rt
DEBUG:   event.py - Event Registed：notice.message - PushDeerMsg.send
DEBUG:   event.py - Event Registed：site.login - SiteRefresh.site_login
DEBUG:   event.py - Event Registed：site.statistic - SiteStatistic.refresh
DEBUG:   event.py - Event Registed：site.deleted - SiteStatistic.site_deleted
DEBUG:   event.py - Event Registed：webhook.message - SpeedLimiter.check_playing_sessions
DEBUG:   event.py - Event Registed：plugin.reload - WebHook.send
DEBUG:   event.py - Event Registed：command.excute - WebHook.send
DEBUG:   event.py - Event Registed：site.signin - WebHook.send
DEBUG:   event.py - Event Registed：site.statistic - WebHook.send
DEBUG:   event.py - Event Registed：site.deleted - WebHook.send
DEBUG:   event.py - Event Registed：douban.sync - WebHook.send
DEBUG:   event.py - Event Registed：webhook.message - WebHook.send
DEBUG:   event.py - Event Registed：transfer.complete - WebHook.send
DEBUG:   event.py - Event Registed：download.added - WebHook.send
DEBUG:   event.py - Event Registed：history.deleted - WebHook.send
DEBUG:   event.py - Event Registed：downloadfile.deleted - WebHook.send
DEBUG:   event.py - Event Registed：user.message - WebHook.send
DEBUG:   event.py - Event Registed：notice.message - WebHook.send
DEBUG:   event.py - Event Registed：name.recognize - WebHook.send
DEBUG:   event.py - Event Registed：name.recognize.result - WebHook.send
DEBUG:   event.py - Event Registed：directory.sync - WebHook.send
DEBUG:   event.py - Event Registed：cloudflare.speedtest - WebHook.send
DEBUG:   event.py - Event Registed：site.login - WebHook.send
DEBUG:   event.py - Event Registed：networkdisk.del - WebHook.send
DEBUG:   event.py - Event Disabled：AutoSignIn
DEBUG:   event.py - Event Disabled：CustomSites
DEBUG:   event.py - Event Disabled：SiteStatistic
DEBUG:   event.py - Event Disabled：SiteRefresh
DEBUG:   event.py - Event Disabled：DoubanSync
DEBUG:   event.py - Event Disabled：DirMonitor
DEBUG:   event.py - Event Disabled：ChineseSubFinder
DEBUG:   event.py - Event Disabled：DoubanRank
DEBUG:   event.py - Event Disabled：TorrentRemover
DEBUG:   event.py - Event Disabled：MediaSyncDel
DEBUG:   event.py - Event Disabled：CustomHosts
DEBUG:   event.py - Event Disabled：SpeedLimiter
DEBUG:   event.py - Event Disabled：CloudflareSpeedTest
DEBUG:   event.py - Event Disabled：BestFilmVersion
DEBUG:   event.py - Event Disabled：MediaServerMsg
DEBUG:   event.py - Event Disabled：MediaServerRefresh
DEBUG:   event.py - Event Disabled：WebHook
DEBUG:   event.py - Event Disabled：ChatGPT
DEBUG:   event.py - Event Disabled：NAStoolSync
DEBUG:   event.py - Event Disabled：MessageForward
DEBUG:   event.py - Event Disabled：AutoBackup
DEBUG:   event.py - Event Disabled：IYUUAutoSeed
DEBUG:   event.py - Event Disabled：TorrentTransfer
DEBUG:   event.py - Event Disabled：RssSubscribe
DEBUG:   event.py - Event Disabled：SyncDownloadFiles
DEBUG:   event.py - Event Disabled：BrushFlow
DEBUG:   event.py - Event Disabled：DownloadingMsg
DEBUG:   event.py - Event Disabled：AutoClean
DEBUG:   event.py - Event Disabled：InvitesSignin
DEBUG:   event.py - Event Disabled：PersonMeta
DEBUG:   event.py - Event Disabled：IyuuMsg
DEBUG:   event.py - Event Disabled：MoviePilotUpdateNotify
DEBUG:   event.py - Event Disabled：PushDeerMsg
DEBUG:   event.py - Event Disabled：BarkMsg
DEBUG:   scheduler.py - None
DEBUG:   chain - 请求模块执行：register_commands ...
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3001 (Press CTRL+C to quit)
```

- `第三方插件库`
与使用远程官方源的时候一样的问题，显示安装完成，但没有插件图标
![image](https://github.com/jxxghp/MoviePilot/assets/95741669/28c82fea-53de-42a2-9b47-50b5c96b4577)
![image](https://github.com/jxxghp/MoviePilot/assets/95741669/43d1faa0-2096-45d9-9a11-864ecdd1a421)

日志内容
```
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): api.github.com:443
DEBUG:   connectionpool.py - https://api.github.com:443 "GET /repos/AnjoyLi/MoviePilot-Plugins/contents/plugins/qqmsg HTTP/1.1" 200 291
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): raw.githubusercontent.com:443
INFO:     192.168.100.113:0 - "GET /api/v1/plugin/install/QqMsg?repo_url=https:%2F%2Fgh.******.com%2Fhttps:%2F%2Fraw.githubusercontent.com%2FAnjoyLi%2FMoviePilot-Plugins%2Fmain%2F&force=false HTTP/1.1" 200 OK
INFO:     192.168.100.113:0 - "GET /api/v1/plugin/ HTTP/1.1" 200 OK
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): api.github.com:443
DEBUG:   connectionpool.py - https://api.github.com:443 "GET /repos/AnjoyLi/MoviePilot-Plugins/contents/plugins/qqmsg HTTP/1.1" 200 291
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): raw.githubusercontent.com:443
INFO:     192.168.100.113:0 - "GET /api/v1/plugin/install/QqMsg?repo_url=https:%2F%2Fgh.******.com%2Fhttps:%2F%2Fraw.githubusercontent.com%2FAnjoyLi%2FMoviePilot-Plugins%2Fmain%2F&force=false HTTP/1.1" 200 OK
INFO:     192.168.100.113:0 - "GET /api/v1/plugin/ HTTP/1.1" 200 OK
```
- 个人的结论（属于个人看法，可能有误）

使用远程官方库的时候，看起来像是显示的问题
如果是远程插件与本地内置插件名字相同，默认使用的时候，就算远程库的版本号更高，也会使用本地的插件库进行安装
但是问题出在版本号上，在插件市场里，插件版本号是以远程库的为准的，如：本地版`云盘文件删除`为`1.0`，远程库最新版为`1.1`。显示的版本号为`1.1`，点击安装后，它看似安装了`1.1`，实际应该是安装了`1.0`，因为在我重启容器后，原本不显示的插件自己显示出来了，且版本号是本地的
在`v1.4.4`里，目前阶段来说远程库有4个插件比本地的版本号更高，这四个都无法安装的。
只要是只是获取了插件库的内容，安装插件的时候还是使用了api.github.com的原因

下载插件的时候好像还是调用了api.github.com，这应该是导致远程第三方插件有时候无法安装的原因，因为GitHub国内的环境问题

#### `v1.4.5`
删除原1.4.4项目后重装到1.4.5时，出现无法使用第三方加速后的地址了，显示直接无法连接，但手动尝试打开这些地址还是能连通的，估计是改变了获取到地址正则规则的原因

- 远程库变量值
```
PLUGIN_MARKET=https://gh.*****.com/https://raw.githubusercontent.com/jxxghp/MoviePilot-Plugins/main/,https://gh.*****.com/https://raw.githubusercontent.com/AnjoyLi/MoviePilot-Plugins/main/
```
日志
```
INFO:    plugin.py - 开始安装在线插件...
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:   connectionpool.py - Starting new HTTPS connection (1): raw.githubusercontent.com:443
ERROR:   plugin.py - 未获取到在线插件
DEBUG:   event.py - Event Registed：plugin.action - AutoSignIn.sign_in
DEBUG:   event.py - Event Registed：site.deleted - AutoSignIn.site_deleted
DEBUG:   event.py - Event Registed：notice.message - BarkMsg.send
DEBUG:   event.py - Event Registed：webhook.message - BestFilmVersion.webhook_message_action
DEBUG:   event.py - Event Registed：user.message - ChatGPT.talk
DEBUG:   event.py - Event Registed：name.recognize - ChatGPT.recognize
DEBUG:   event.py - Event Registed：transfer.complete - ChineseSubFinder.download
DEBUG:   event.py - Event Registed：plugin.action - CloudDiskDel.clouddisk_del
DEBUG:   event.py - Event Registed：plugin.action - CloudflareSpeedTest.__cloudflareSpeedTest
DEBUG:   event.py - Event Registed：plugin.reload - CustomHosts.reload
DEBUG:   event.py - Event Registed：plugin.action - DirMonitor.remote_sync
DEBUG:   event.py - Event Registed：plugin.action - DoubanSync.remote_sync
DEBUG:   event.py - Event Registed：site.deleted - IYUUAutoSeed.site_deleted
DEBUG:   event.py - Event Registed：notice.message - IyuuMsg.send
DEBUG:   event.py - Event Registed：webhook.message - MediaServerMsg.send
DEBUG:   event.py - Event Registed：transfer.complete - MediaServerRefresh.refresh
DEBUG:   event.py - Event Registed：webhook.message - MediaSyncDel.sync_del_by_webhook
DEBUG:   event.py - Event Registed：webhook.message - MediaSyncDel.sync_del_by_plugin
DEBUG:   event.py - Event Registed：downloadfile.deleted - MediaSyncDel.downloadfile_del_sync
DEBUG:   event.py - Event Registed：notice.message - MessageForward.send
DEBUG:   event.py - Event Registed：transfer.complete - PersonMeta.scrap_rt
DEBUG:   event.py - Event Registed：notice.message - PushDeerMsg.send
DEBUG:   event.py - Event Registed：plugin.action - SiteRefresh.site_refresh
DEBUG:   event.py - Event Registed：plugin.action - SiteStatistic.refresh
DEBUG:   event.py - Event Registed：site.deleted - SiteStatistic.site_deleted
DEBUG:   event.py - Event Registed：webhook.message - SpeedLimiter.check_playing_sessions
DEBUG:   event.py - Event Registed：plugin.reload - WebHook.send
DEBUG:   event.py - Event Registed：plugin.action - WebHook.send
DEBUG:   event.py - Event Registed：command.excute - WebHook.send
DEBUG:   event.py - Event Registed：site.deleted - WebHook.send
DEBUG:   event.py - Event Registed：webhook.message - WebHook.send
DEBUG:   event.py - Event Registed：transfer.complete - WebHook.send
DEBUG:   event.py - Event Registed：download.added - WebHook.send
DEBUG:   event.py - Event Registed：history.deleted - WebHook.send
DEBUG:   event.py - Event Registed：downloadfile.deleted - WebHook.send
DEBUG:   event.py - Event Registed：user.message - WebHook.send
DEBUG:   event.py - Event Registed：notice.message - WebHook.send
DEBUG:   event.py - Event Registed：name.recognize - WebHook.send
DEBUG:   event.py - Event Registed：name.recognize.result - WebHook.send
DEBUG:   event.py - Event Disabled：AutoSignIn
DEBUG:   event.py - Event Disabled：CustomSites
DEBUG:   event.py - Event Disabled：SiteStatistic
DEBUG:   event.py - Event Disabled：SiteRefresh
DEBUG:   event.py - Event Disabled：DoubanSync
DEBUG:   event.py - Event Disabled：DirMonitor
DEBUG:   event.py - Event Disabled：ChineseSubFinder
DEBUG:   event.py - Event Disabled：DoubanRank
INFO:    plugin.py - Plugin Loaded：LibraryScraper
DEBUG:   event.py - Event Disabled：TorrentRemover
INFO:    plugin.py - Plugin Loaded：MediaSyncDel
DEBUG:   event.py - Event Disabled：CustomHosts
DEBUG:   event.py - Event Disabled：SpeedLimiter
DEBUG:   event.py - Event Disabled：CloudflareSpeedTest
DEBUG:   event.py - Event Disabled：BestFilmVersion
INFO:    plugin.py - Plugin Loaded：MediaServerMsg
DEBUG:   event.py - Event Disabled：MediaServerRefresh
DEBUG:   event.py - Event Disabled：WebHook
DEBUG:   event.py - Event Disabled：ChatGPT
DEBUG:   event.py - Event Disabled：NAStoolSync
DEBUG:   event.py - Event Disabled：MessageForward
DEBUG:   event.py - Event Disabled：AutoBackup
DEBUG:   event.py - Event Disabled：IYUUAutoSeed
DEBUG:   event.py - Event Disabled：TorrentTransfer
DEBUG:   event.py - Event Disabled：RssSubscribe
DEBUG:   event.py - Event Disabled：SyncDownloadFiles
DEBUG:   event.py - Event Disabled：BrushFlow
DEBUG:   event.py - Event Disabled：DownloadingMsg
DEBUG:   event.py - Event Disabled：AutoClean
DEBUG:   event.py - Event Disabled：InvitesSignin
DEBUG:   event.py - Event Disabled：PersonMeta
DEBUG:   event.py - Event Disabled：IyuuMsg
DEBUG:   event.py - Event Disabled：MoviePilotUpdateNotify
ERROR:   plugin.py - 加载插件 CloudDiskDel 出错：list index out of range - Traceback (most recent call last):
  File "/app/app/core/plugin.py", line 72, in start
    plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
  File "/app/app/plugins/clouddiskdel/__init__.py", line 53, in init_plugin
    self._paths[paths[0]] = paths[1]
                            ~~~~~^^^
IndexError: list index out of range
DEBUG:   event.py - Event Disabled：PushDeerMsg
DEBUG:   event.py - Event Disabled：BarkMsg
DEBUG:   scheduler.py - None
DEBUG:   chain - 请求模块执行：register_commands ...
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3001 (Press CTRL+C to quit)
```

期望的结果是：支持第三方加速后的插件地址或者已经镜像在如：gitee这些国内能打的开网站上的插件，这样就不用使用proxy代理了

**Comment by jxxghp** [comment]
无法重现你说的这个情况。
