### ISSUE TITLE
[错误报告]: 站点自动签到抛出异常

### ISSUE THREAD

**Issue by nfgokie** [jxxghp/MoviePilot#1160]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.5

### 运行环境

Windows

### 问题类型

插件问题

### 问题描述

站点自动签到运行时报，抛出sql异常。
站点是通过CloudCookie同步过来的，IYUU辅种正常。

插件配置信息：
执行周期：空
队列数量：5
重试关键词：错误|失败
自动优选：0
签到站点：（站点列表）
登录站点：空

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-11-22 21:13:10,994 - autosignin - 站点自动签到服务启动，立即运行一次
【ERROR】2023-11-22 21:13:14,003 - base.py - Job "站点自动签到 (trigger: date[2023-11-22 21:13:13 CST], next run at: 2023-11-22 21:13:13 CST)" raised an exception
Traceback (most recent call last):
  File "sqlalchemy\engine\base.py", line 1969, in _exec_single_context
  File "sqlalchemy\engine\default.py", line 922, in do_execute
sqlite3.OperationalError: no such table: plugindata

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apscheduler\executors\base.py", line 125, in run_job
  File "app\plugins\autosignin\__init__.py", line 638, in sign_in
  File "app\plugins\autosignin\__init__.py", line 649, in __do
  File "app\plugins\__init__.py", line 174, in del_data
  File "app\db\plugindata_oper.py", line 50, in del_data
  File "app\db\__init__.py", line 96, in wrapper
  File "app\db\__init__.py", line 90, in wrapper
  File "app\db\models\plugin.py", line 31, in del_plugin_data_by_key
  File "sqlalchemy\orm\query.py", line 3181, in delete
  File "sqlalchemy\orm\session.py", line 2308, in execute
  File "sqlalchemy\orm\session.py", line 2190, in _execute_internal
  File "sqlalchemy\orm\bulk_persistence.py", line 1946, in orm_execute_statement
  File "sqlalchemy\orm\context.py", line 293, in orm_execute_statement
  File "sqlalchemy\engine\base.py", line 1416, in execute
  File "sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
  File "sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
  File "sqlalchemy\engine\base.py", line 1848, in _execute_context
  File "sqlalchemy\engine\base.py", line 1988, in _exec_single_context
  File "sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
  File "sqlalchemy\engine\base.py", line 1969, in _exec_single_context
  File "sqlalchemy\engine\default.py", line 922, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: plugindata
[SQL: DELETE FROM plugindata WHERE plugindata.plugin_id = ? AND plugindata."key" = ?]
[parameters: ('AutoSignIn', '签到-2023-11-21')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by nfgokie** [comment]
同883应该是同一个问题，重复了
