### ISSUE TITLE
[错误报告]: 手动整理时电影、电视剧tmdb ID相同识别错误

### ISSUE THREAD

**Issue by echowiz** [jxxghp/MoviePilot#118]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0

### 问题类型

主程序运行问题

### 问题描述

电影：肖申克的救赎 
tmdb ID：278
下载完成后识别正确，但是在重新整理时，遇到电影、电视剧tmdb ID相同导致识别错误

### 发生问题时系统日志和配置文件

```bash
moviepilot  | 2023-08-14 19:36:35,375 - media.py -【INFO】开始识别媒体信息，标题：肖申克的救赎.The.Shawshank.Redemption.1994.UHD.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS，副标题： ...
moviepilot  | 2023-08-14 19:36:35,377 - __init__.py -【INFO】正在识别 肖申克的救赎 ...
moviepilot  | 2023-08-14 19:36:36,264 - tmdbapi.py -【INFO】正在查询TMDB电影：278 ...
moviepilot  | 2023-08-14 19:36:36,878 - tmdbapi.py -【INFO】278 查询结果：肖申克的救赎
moviepilot  | 2023-08-14 19:36:36,879 - __init__.py -【INFO】肖申克的救赎 识别结果：电影 肖申克的救赎 (1994） 278
moviepilot  | 2023-08-14 19:36:36,879 - media.py -【INFO】肖申克的救赎.The.Shawshank.Redemption.1994.UHD.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS 识别到媒体信息：电影 肖申克的救赎 (1994）
moviepilot  | INFO:     172.17.0.1:0 - "GET /api/v1/media/recognize?title=%E8%82%96%E7%94%B3%E5%85%8B%E7%9A%84%E6%95%91%E8%B5%8E.The.Shawshank.Redemption.1994.UHD.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS&subtitle= HTTP/1.1" 200 OK
moviepilot  | INFO:     172.17.0.1:0 - "GET /api/v3/queue?apikey=moviepilot951357&includeEpisode=true HTTP/1.1" 404 Not Found
moviepilot  | 2023-08-14 19:37:55,707 - transfer.py -【INFO】开始转移下载器文件，参数：a5dfa4b28548941f3ea6d61dd03a5b3508bb6860 278
moviepilot  | 2023-08-14 19:37:55,726 - tmdbapi.py -【INFO】正在查询TMDB电视剧：278 ...
moviepilot  | 2023-08-14 19:37:56,622 - tmdbapi.py -【INFO】278 查询结果：Nightline
moviepilot  | 2023-08-14 19:37:56,622 - __init__.py -【INFO】278 识别结果：电视剧 Nightline (1980）
moviepilot  | 2023-08-14 19:37:56,622 - transfer.py -【INFO】获取到 1 个已完成的下载任务
moviepilot  | 2023-08-14 19:37:56,624 - transfer.py -【INFO】肖申克的救赎.The.Shawshank.Redemption.1994.UHD.2160p.x265.10bit.HDR.4Audios.mUHD-FRDS 识别为：电视剧 Nightline (1980）
moviepilot  | 2023-08-14 19:37:58,066 - __init__.py -【WARNING】没有获取到 Nightline (1980） 的Fanart图片数据
moviepilot  | 2023-08-14 19:37:58,067 - tmdbapi.py -【INFO】正在获取电视剧图片：278...
moviepilot  | Traceback (most recent call last):
moviepilot  |   File "/app/app/chain/__init__.py", line 88, in run_module
moviepilot  |     result = func(*args, **kwargs)
moviepilot  |              ^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/app/app/modules/filetransfer/__init__.py", line 46, in transfer
moviepilot  |     result = self.transfer_media(in_path=path,
moviepilot  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/app/app/modules/filetransfer/__init__.py", line 422, in transfer_media
moviepilot  |     new_path = target_dir / self.get_rename_path(
moviepilot  |                             ^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/app/app/modules/filetransfer/__init__.py", line 564, in get_rename_path
moviepilot  |     template = Template(template_string)
moviepilot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1208, in __new__
moviepilot  |     return env.from_string(source, template_class=cls)
moviepilot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string
moviepilot  |     return cls.from_code(self, self.compile(source), gs, None)
moviepilot  |                                ^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
moviepilot  | 2023-08-14 19:37:59,051 - command.py -【INFO】处理事件：notice.message - [<function MessageForward.send at 0x7fbda581a020>, <function WebHook.send at 0x7fbda57dae80>]
moviepilot  | INFO:     172.17.0.1:0 - "GET /api/v3/queue?apikey=moviepilot951357&includeEpisode=true HTTP/1.1" 404 Not Found
moviepilot  | 2023-08-14 19:38:02,283 - transfer.py -【INFO】下载器文件转移执行完成
```

**Comment by jxxghp** [comment]
tmdb ID相同的问题我改一下加个类型指定。
但上面日志的报错，可能是你的命名模板设置的格式有问题。
