### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by m215owen** [jxxghp/MoviePilot#1184]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

无法启动，去掉环境数据文件也无法启动

### 发生问题时系统日志和配置文件

```bash
usermod: no changes

Traceback (most recent call last):

  File "/app/app/main.py", line 19, in <module>

    from app.core.config import settings

  File "/app/app/core/config.py", line 359, in <module>

    _env_file=Settings().CONFIG_PATH / "app.env",

              ^^^^^^^^^^

  File "/app/app/core/config.py", line 340, in __init__

    super().__init__(**kwargs)

  File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__

  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__

pydantic.error_wrappers.ValidationError: 1 validation error for Settings

DEBUG
```

**Comment by asnfohsdgfbkxcv** [comment]
我的win版直接替换原来的exe，也是无法使用，登录显示网络无法连接。已经杀过进程、重启过电脑。后面替换回1.4.6，正常使用。
