### ISSUE TITLE
[错误报告]: 手动重新整理报错

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#1230]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.5.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

手动重新整理报错

### 发生问题时系统日志和配置文件

```bash
INFO:    transfer.py - 开始删除文件以及空目录：/media/link/电影/华语电影/前任4：英年早婚 (2023)/前任4：英年早婚 (2023) - DV - 2160p.mkv ...
WARNING: transfer.py - 文件 /media/link/电影/华语电影/前任4：英年早婚 (2023)/前任4：英年早婚 (2023) - DV - 2160p.mkv 已删除
WARNING: transfer.py - 目录 /media/link/电影/华语电影/前任4：英年早婚 (2023) 已删除
INFO:    transfer.py - 手动转移：/media/downloads/前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB/前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB.mkv ...
INFO:    themoviedb - The Ex Files 4 Marriage Plan 使用TMDB识别缓存：前任4：英年早婚
INFO:    tmdbapi.py - 正在查询TMDB电影：1173883 ...
INFO:    tmdbapi.py - 1173883 查询结果：前任4：英年早婚
INFO:    themoviedb - The Ex Files 4 Marriage Plan TMDB识别结果：电影 前任4：英年早婚 (2023) 1173883
INFO:    media.py - 前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB 识别到媒体信息：电影 前任4：英年早婚 (2023)
WARNING: fanart - 没有获取到 前任4：英年早婚 (2023) 的fanart图片数据
INFO:    tmdbapi.py - 正在获取电影图片：1173883...
INFO:    transfer.py - 前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB.mkv 识别为：电影 前任4：英年早婚 (2023)
INFO:    filetransfer - 获取转移目标路径：/media/link/电影/华语电影/前任4：英年早婚 (2023)/前任4：英年早婚 (2023) - DV - 2160p.mkv/华语电影
WARNING: transfer.py - 前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB.mkv 入库失败：/media/link/电影/华语电影/前任4：英年早婚 (2023)/前任4：英年早婚 (2023) - DV - 2160p.mkv/华语电影 目标路径不存在
INFO:    chain - 发送消息：channel=None，title=前任4：英年早婚 (2023)  入库失败！, text=原因：/media/link/电影/华语电影/前任4：英年早婚 (2023)/前任4：英年早婚 (2023) - DV - 2160p.mkv/华语电影 目标路径不存在，userid=None
INFO:    command.py - 处理事件：notice.message - [<function WebHook.send at 0x14b0ab2049a0>]
INFO:    webhook - 发送成功：http://192.168.100.6:5678/webhook/316eec7e-b4c9-43b4-aee1-93a67a5ef9c8
INFO:    transfer.py - /media/downloads/前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB/前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB.mkv 转移完成，共 1 个文件，失败 1 个，跳过 0 个
INFO:     192.168.100.2:0 - "POST /api/v1/transfer/manual?logid=1382&path=&target=%2Fmedia%2Flink%2F%E7%94%B5%E5%BD%B1%2F%E5%8D%8E%E8%AF%AD%E7%94%B5%E5%BD%B1%2F%E5%89%8D%E4%BB%BB4%EF%BC%9A%E8%8B%B1%E5%B9%B4%E6%97%A9%E5%A9%9A+(2023)%2F%E5%89%8D%E4%BB%BB4%EF%BC%9A%E8%8B%B1%E5%B9%B4%E6%97%A9%E5%A9%9A+(2023)+-+DV+-+2160p.mkv&type_name=&transfer_type=&episode_format=&episode_detail=&episode_part=&min_filesize=0 HTTP/1.1" 200 OK
INFO:     192.168.100.2:0 - "GET /api/v1/history/transfer?page=1&count=50&title=%E5%89%8D%E4%BB%BB HTTP/1.1" 200 OK
INFO:    transfer.py - 手动转移：/media/downloads/前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB/前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB.mkv ...
INFO:     192.168.100.2:0 - "GET /api/v1/system/progress/filetransfer?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI5ODM4NjUsInN1YiI6IjEifQ.-FdqfTSd97LXnCPTaMeqnp__gy2wCg0FD3FYjpMvewY HTTP/1.1" 200 OK
INFO:    themoviedb - The Ex Files 4 Marriage Plan 使用TMDB识别缓存：前任4：英年早婚
INFO:    tmdbapi.py - 正在查询TMDB电影：1173883 ...
INFO:    tmdbapi.py - 1173883 查询结果：前任4：英年早婚
INFO:    themoviedb - The Ex Files 4 Marriage Plan TMDB识别结果：电影 前任4：英年早婚 (2023) 1173883
INFO:    media.py - 前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB 识别到媒体信息：电影 前任4：英年早婚 (2023)
WARNING: fanart - 没有获取到 前任4：英年早婚 (2023) 的fanart图片数据
INFO:    tmdbapi.py - 正在获取电影图片：1173883...
INFO:    transfer.py - 前任4：英年早婚.The.Ex-Files.4.Marriage.Plan.2023.2160p.WEB-DL.DDP2.0.H265.DV-HDSWEB.mkv 识别为：电影 前任4：英年早婚 (2023)
INFO:    filetransfer - 获取转移目标路径：/media/link/电影/华语电影
INFO:    filetransfer - 目标文件已存在，转移覆盖模式：size
INFO:    filetransfer - 目标文件文件大小更小，将被覆盖：/media/link/电影/华语电影/前任4：英年早婚 (2023)/前任4：英年早婚 (2023) - DV - 2160p.mkv
INFO:    filetransfer - 正在删除已存在的文件：/media/link/电影/华语电影/前任4：英年早婚 (2023)/前任4：英年早婚 (2023) - DV - 2160p.mkv
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 97, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filetransfer/__init__.py", line 72, in transfer
    return self.transfer_media(in_path=path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filetransfer/__init__.py", line 525, in transfer_media
    retcode = self.__transfer_file(file_item=in_path,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filetransfer/__init__.py", line 329, in __transfer_file
    new_file.unlink()
  File "/usr/local/lib/python3.11/pathlib.py", line 1147, in unlink
    os.unlink(self)
IsADirectoryError: [Errno 21] Is a directory: '/media/link/电影/华语电影/前任4：英年早婚 (2023)/前任4：英年早婚 (2023) - DV - 2160p.mkv'
ERROR:   chain - 运行模块 transfer 出错：FileTransferModule - [Errno 21] Is a directory: '/media/link/电影/华语电影/前任4：英年早婚 (2023)/前任4：英年早婚 (2023) - DV - 2160p.mkv'
None
ERROR:   transfer.py - 文件转移模块运行失败
```

**Comment by yellowstrong** [comment]
只要是对一部电影不进行任何更改，重新转移就会出发错误，哪怕更改了命名格式，但是只要还是同一部，位置不变就会触发

**Comment by yellowstrong** [comment]
> 只要是对一部电影不进行任何更改，重新转移就会触发错误，哪怕更改了命名格式，但是只要还是同一部，位置不变就会触发

**Comment by yellowstrong** [comment]
INFO:    transfer.py - 开始删除文件以及空目录：/media/link/电影/外语电影/奇异博士 (2016)/奇异博士 (2016) - 2160p.mkv ...
WARNING: transfer.py - 文件 /media/link/电影/外语电影/奇异博士 (2016)/奇异博士 (2016) - 2160p.mkv 已删除
WARNING: transfer.py - 目录 /media/link/电影/外语电影/奇异博士 (2016) 已删除
INFO:    transfer.py - 手动转移：/media/downloads/Doctor Strange 2016 UHD BluRay REMUX 2160p HEVC Atmos TrueHD7.1 2Audio-CHD/Doctor Strange 2016 UHD BluRay REMUX 2160p HEVC Atmos TrueHD7.1 2Audio-CHD.mkv ...
INFO:    themoviedb - 正在识别 Doctor Strange ...
INFO:    tmdbapi.py - 正在查询TMDB电影：284052 ...
INFO:    tmdbapi.py - 284052 查询结果：奇异博士
INFO:    themoviedb - Doctor Strange TMDB识别结果：电影 奇异博士 (2016) 284052
INFO:    media.py - Doctor Strange 2016 UHD BluRay REMUX 2160p HEVC Atmos TrueHD7.1 2Audio-CHD 识别到媒体信息：电影 奇异博士 (2016)
INFO:    transfer.py - Doctor Strange 2016 UHD BluRay REMUX 2160p HEVC Atmos TrueHD7.1 2Audio-CHD.mkv 识别为：电影 奇异博士 (2016)
INFO:    filetransfer - 获取转移目标路径：/media/link/电影/外语电影/奇异博士 (2016)/奇异博士 (2016) - 2160p.mkv/外语电影
WARNING: transfer.py - Doctor Strange 2016 UHD BluRay REMUX 2160p HEVC Atmos TrueHD7.1 2Audio-CHD.mkv 入库失败：/media/link/电影/外语电影/奇异博士 (2016)/奇异博士 (2016) - 2160p.mkv/外语电影 目标路径不存在
INFO:    chain - 发送消息：channel=None，title=奇异博士 (2016)  入库失败！, text=原因：/media/link/电影/外语电影/奇异博士 (2016)/奇异博士 (2016) - 2160p.mkv/外语电影 目标路径不存在，userid=None
INFO:    command.py - 处理事件：notice.message - [<function WebHook.send at 0x14e2ee8c2de0>]
INFO:    webhook - 发送成功：http://192.168.100.6:5678/webhook/316eec7e-b4c9-43b4-aee1-93a67a5ef9c8
INFO:    cookiecloud.py - 开始同步CookieCloud站点 ...
INFO:    transfer.py - /media/downloads/Doctor Strange 2016 UHD BluRay REMUX 2160p HEVC Atmos TrueHD7.1 2Audio-CHD/Doctor Strange 2016 UHD BluRay REMUX 2160p HEVC Atmos TrueHD7.1 2Audio-CHD.mkv 转移完成，共 1 个文件，失败 1 个，跳过 0 个
INFO:     192.168.100.2:0 - "POST /api/v1/transfer/manual?logid=1433&path=&target=%2Fmedia%2Flink%2F%E7%94%B5%E5%BD%B1%2F%E5%A4%96%E8%AF%AD%E7%94%B5%E5%BD%B1%2F%E5%A5%87%E5%BC%82%E5%8D%9A%E5%A3%AB+(2016)%2F%E5%A5%87%E5%BC%82%E5%8D%9A%E5%A3%AB+(2016)+-+2160p.mkv&type_name=&transfer_type=&episode_format=&episode_detail=&episode_part=&min_filesize=0 HTTP/1.1" 200 OK
INFO:     192.168.100.2:0 - "GET /api/v1/history/transfer?page=1&count=50&title= HTTP/1.1" 200 OK
