### ISSUE TITLE
[错误报告]: chain模块的recognize_media模块报错，无法识别媒体信息

### ISSUE THREAD

**Issue by WNotCoder** [jxxghp/MoviePilot#1245]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

自动整理、手工整理均无法识别媒体信息。提示为：TheMovieDbModule - 'str' object has no attribute 'items'。
具体日志：
![image](https://github.com/jxxghp/MoviePilot/assets/30321199/66686be8-e4f1-4b9f-ab0a-3ca3d7cb7a9b)

#### 采取过的行动：
Issue中有提过类似问题，答复是网络联通性不好。我采取了以下办法来依次测试：
1）修改TMDB_API_DOMAIN值为api.tmdb.org。结论：无效，错误依旧。
2）挂梯子，分别尝试api.tmdb.org、api.themoviedb.org。结论：依旧无效。
3）使用内建联通性检查，联通性无问题。检查结果见截图：
![image](https://github.com/jxxghp/MoviePilot/assets/30321199/324a2fdd-cc71-4615-952f-2edf5b4388af)

#### 上一次正常使用的版本：
1.5.0

#### 上一次正常使用到本次出现异常中间变更过的设置：
1.升级MoviePilot，由1.5.0升级至1.5.1，后又升级至1.5.1-1
2.清理user.db数据库，使用SQLBrowser删除了transferhistory表的全部内容（表未删除）
3.重写了category.yaml（因二级分类一直不起作用，而且本次重写以后还不起作用）。具体文件内容见截图：
![image](https://github.com/jxxghp/MoviePilot/assets/30321199/9ae1f297-e4ef-40be-b3a0-c70ce7fb58d9)

头一次写Issue，如有不规范的行为望多包涵。

### 发生问题时系统日志和配置文件

```bash
2023-12-14 05:03:28	stdout	[32mINFO:[0m    iyuumsg - IYUU消息发送成功
2023-12-14 05:03:27	stdout	[32mINFO:[0m    command.py - 处理事件：notice.message - [<function IyuuMsg.send at 0x7f5238befb00>, <function WebHook.send at 0x7f5238a65580>]
2023-12-14 05:03:27	stdout	 手动识别转移。，userid=None
2023-12-14 05:03:27	stdout	/redo 1021 [tmdbid]|[类型]
2023-12-14 05:03:27	stdout	[32mINFO:[0m    chain - 发送消息：channel=None，title=少年的你.Better.Days.2019.2160p.WEB-DL.HEVC.DDP5.1-OurTV.mkv 未识别到媒体信息，无法入库！, text=回复：```
2023-12-14 05:03:27	stdout	[33mWARNING:[0m transfer.py - /Media/Movie/少年的你.Better.Days.2019.2160p.WEB-DL.HEVC.DDP5.1-OurTV/少年的你.Better.Days.2019.2160p.WEB-DL.HEVC.DDP5.1-OurTV.mkv 未识别到媒体信息
2023-12-14 05:03:27	stdout	[33mWARNING:[0m media.py - 少年的你.Better.Days.2019.2160p.WEB-DL.HEVC.DDP5.1-OurTV 未识别到媒体信息
2023-12-14 05:03:26	stdout	[32mINFO:[0m    command.py - 处理事件：name.recognize.result - [<function MediaChain.recognize_result at 0x7f523a717ec0>, <function WebHook.send at 0x7f5238a65580>]
2023-12-14 05:03:26	stdout	[32mINFO:[0m    command.py - 处理事件：name.recognize - [<function ChatGPT.recognize at 0x7f5238d18900>, <function WebHook.send at 0x7f5238a65580>]
2023-12-14 05:03:26	stdout	[32mINFO:[0m    media.py - 请求辅助识别，标题：少年的你.Better.Days.2019.2160p.WEB-DL.HEVC.DDP5.1-OurTV ...
2023-12-14 05:03:26	stdout	None
2023-12-14 05:03:26	stdout	[31mERROR:[0m   chain - 运行模块 recognize_media 出错：TheMovieDbModule - 'str' object has no attribute 'items'
2023-12-14 05:03:26	stdout	AttributeError: 'str' object has no attribute 'items'
2023-12-14 05:03:26	stdout	                       ^^^^^^^^^^
2023-12-14 05:03:26	stdout	    for attr, value in item.items():
2023-12-14 05:03:26	stdout	  File "/app/app/modules/themoviedb/category.py", line 110, in get_category
2023-12-14 05:03:26	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-14 05:03:26	stdout	    return self.get_category(self._movie_categorys, tmdb_info)
2023-12-14 05:03:26	stdout	  File "/app/app/modules/themoviedb/category.py", line 84, in get_movie_category
2023-12-14 05:03:26	stdout	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-14 05:03:26	stdout	    cat = self.category.get_movie_category(info)
2023-12-14 05:03:26	stdout	  File "/app/app/modules/themoviedb/__init__.py", line 131, in recognize_media
2023-12-14 05:03:26	stdout	             ^^^^^^^^^^^^^^^^^^^^^
2023-12-14 05:03:26	stdout	    result = func(*args, **kwargs)
2023-12-14 05:03:26	stdout	  File "/app/app/chain/__init__.py", line 97, in run_module
2023-12-14 05:03:26	stdout	Traceback (most recent call last):
2023-12-14 05:03:26	stdout	[32mINFO:[0m    tmdbapi.py - 575813 查询结果：少年的你
2023-12-14 05:03:25	stdout	[32mINFO:[0m    tmdbapi.py - 正在查询TMDB电影：575813 ...
2023-12-14 05:03:25	stdout	[32mINFO:[0m    themoviedb - 少年的你 使用TMDB识别缓存：少年的你
2023-12-14 05:03:25	stdout	[32mINFO:[0m    transfer.py - 手动转移：/Media/Movie/少年的你.Better.Days.2019.2160p.WEB-DL.HEVC.DDP5.1-OurTV/少年的你.Better.Days.2019.2160p.WEB-DL.HEVC.DDP5.1-OurTV.mkv
```

**Comment by WNotCoder** [comment]
已确定问题原因。

问题原因为二级分类文件问题，将开启二级分类改为false后正常。
