### ISSUE TITLE
[错误报告]: Cloudflare IP优选 不可用，看不明白日志是什么情况。劳烦点拨~

### ISSUE THREAD

**Issue by Travel2Here** [jxxghp/MoviePilot#1284]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.4

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

Cloudflare IP优选 不可用，看不明白日志是什么情况。劳烦点拨~

### 发生问题时系统日志和配置文件

```bash
stderr: [32mINFO:[0m    cloudflarespeedtest - Cloudflare CDN优选服务启动，立即运行一次
stdout: Pending jobs:
stdout:     Cloudflare优选 (trigger: date[2023-12-27 16:47:49 CST], pending)
stdout: INFO:     113.108.77.57:0 - "PUT /api/v1/plugin/CloudflareSpeedTest HTTP/1.1" 200 OK
stdout: INFO:     113.108.77.57:0 - "GET /api/v1/plugin/ HTTP/1.1" 200 OK
stderr: [31mERROR:[0m   base.py - Job "Cloudflare优选 (trigger: date[2023-12-27 16:47:49 CST], next run at: 2023-12-27 16:47:49 CST)" raised an exception
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
stderr:     retval = job.func(*job.args, **job.kwargs)
stderr:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/app/app/plugins/cloudflarespeedtest/__init__.py", line 130, in __cloudflareSpeedTest
stderr:     if self._cf_ip and not customHosts or not customHosts.get("hosts"):
stderr:                                               ^^^^^^^^^^^^^^^
stderr: AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by thsrite** [comment]
先配置自定义Hosts插件，不然cf优选插件无意义

**Comment by Travel2Here** [comment]
> 先配置自定义Hosts插件，不然cf优选插件无意义

原来如此 多谢
