### ISSUE TITLE
[错误报告]: 手动转移文件发生文件转移模块运行失败

### ISSUE THREAD

**Issue by lxlw1320** [jxxghp/MoviePilot#1430]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

手动转移文件的时候出现“运行模块 transfer 出错：FileTransferModule - tag name expected，transfer.py - 文件转移模块运行失败”，这个是什么问题呢，没有搜到可以解决的办法

### 发生问题时系统日志和配置文件

```bash
soothing_frederic-main_app-1  | [32mINFO:[0m    transfer.py - 手动转移：/downloads/TV/杀人者的购物中心.A.Shop.for.Killers.S01.2024.2160p.WEB-DL.DDP5.1.HDR.H265.60fps-HDSWEB/杀人者的购物中心.A.Shop.for.Killers.S01E03.2024.2160p.WEB-DL.DDP5.1.HDR.H265.60fps-HDSWEB.mkv ...
soothing_frederic-main_app-1  | [32mINFO:[0m    themoviedb - 杀人者的购物中心 使用TMDB识别缓存：杀人者的购物中心
soothing_frederic-main_app-1  | INFO:     172.17.0.1:0 - "GET /api/v1/system/progress/filetransfer?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDczMDU3NjQsInN1YiI6IjEiLCJ1c2VybmFtZSI6ImFkbWluIiwic3VwZXJfdXNlciI6dHJ1ZX0.uRbdRUHtJviI3QlG2lWUcRdaGBxDHZ4NvkzvLTCpRVM HTTP/1.1" 200 OK
soothing_frederic-main_app-1  | [32mINFO:[0m    tmdbapi.py - 正在查询TMDB电视剧：215072 ...
soothing_frederic-main_app-1  | [32mINFO:[0m    tmdbapi.py - 215072 查询结果：杀人者的购物中心
soothing_frederic-main_app-1  | [32mINFO:[0m    themoviedb - 杀人者的购物中心 TMDB识别结果：电视剧 杀人者的购物中心 (2024) 215072
soothing_frederic-main_app-1  | [32mINFO:[0m    media.py - 杀人者的购物中心.A.Shop.for.Killers.S01E03.2024.2160p.WEB-DL.DDP5.1.HDR.H265.60fps-HDSWEB 识别到媒体信息：电视剧 杀人者的购物中心 (2024)
soothing_frederic-main_app-1  | [32mINFO:[0m    transfer.py - 杀人者的购物中心.A.Shop.for.Killers.S01E03.2024.2160p.WEB-DL.DDP5.1.HDR.H265.60fps-HDSWEB.mkv 识别为：电视剧 杀人者的购物中心 (2024)
soothing_frederic-main_app-1  | [32mINFO:[0m    tmdbapi.py - 正在查询TMDB电视剧：215072，季：1 ...
soothing_frederic-main_app-1  | [32mINFO:[0m    filetransfer - 获取转移目标路径：/libray/TV/日韩剧
soothing_frederic-main_app-1  | Traceback (most recent call last):
soothing_frederic-main_app-1  |   File "/app/app/chain/__init__.py", line 97, in run_module
soothing_frederic-main_app-1  |     result = func(*args, **kwargs)
soothing_frederic-main_app-1  |              ^^^^^^^^^^^^^^^^^^^^^
soothing_frederic-main_app-1  |   File "/app/app/modules/filetransfer/__init__.py", line 71, in transfer
soothing_frederic-main_app-1  |     return self.transfer_media(in_path=path,
soothing_frederic-main_app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
soothing_frederic-main_app-1  |   File "/app/app/modules/filetransfer/__init__.py", line 476, in transfer_media
soothing_frederic-main_app-1  |     new_file = self.get_rename_path(
soothing_frederic-main_app-1  |                ^^^^^^^^^^^^^^^^^^^^^
soothing_frederic-main_app-1  |   File "/app/app/modules/filetransfer/__init__.py", line 618, in get_rename_path
soothing_frederic-main_app-1  |     template = Template(template_string)
soothing_frederic-main_app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
soothing_frederic-main_app-1  |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1208, in __new__
soothing_frederic-main_app-1  |     return env.from_string(source, template_class=cls)
soothing_frederic-main_app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
soothing_frederic-main_app-1  |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string
soothing_frederic-main_app-1  |     return cls.from_code(self, self.compile(source), gs, None)
soothing_frederic-main_app-1  |                                ^^^^^^^^^^^^^^^^^^^^
soothing_frederic-main_app-1  |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
soothing_frederic-main_app-1  |     self.handle_exception(source=source_hint)
soothing_frederic-main_app-1  |   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
soothing_frederic-main_app-1  |     raise rewrite_traceback_stack(source=source)
soothing_frederic-main_app-1  |   File "", line 1, in template
soothing_frederic-main_app-1  | jinja2.exceptions.TemplateSyntaxError: tag name expected
soothing_frederic-main_app-1  | [31mERROR:[0m   chain - 运行模块 transfer 出错：FileTransferModule - tag name expected
soothing_frederic-main_app-1  | None
soothing_frederic-main_app-1  | [31mERROR:[0m   transfer.py - 文件转移模块运行失败
soothing_frederic-main_app-1  | 无法连接TheMovieDb，请检查网络连接！
soothing_frederic-main_app-1  | INFO:     172.17.0.1:0 - "POST /api/v1/transfer/manual?logid=0&path=%2Fdownloads%2FTV%2F%E6%9D%80%E4%BA%BA%E8%80%85%E7%9A%84%E8%B4%AD%E7%89%A9%E4%B8%AD%E5%BF%83.A.Shop.for.Killers.S01.2024.2160p.WEB-DL.DDP5.1.HDR.H265.60fps-HDSWEB%2F%E6%9D%80%E4%BA%BA%E8%80%85%E7%9A%84%E8%B4%AD%E7%89%A9%E4%B8%AD%E5%BF%83.A.Shop.for.Killers.S01E03.2024.2160p.WEB-DL.DDP5.1.HDR.H265.60fps-HDSWEB.mkv&target=&type_name=&transfer_type=&episode_format=&episode_detail=&episode_part=&min_filesize=0 HTTP/1.1" 200 OK
soothing_frederic-main_app-1  | INFO:     172.17.0.1:0 - "GET /api/v1/filebrowser/list?path=%2Fdownloads%2FTV%2F%E6%9D%80%E4%BA%BA%E8%80%85%E7%9A%84%E8%B4%AD%E7%89%A9%E4%B8%AD%E5%BF%83.A.Shop.for.Killers.S01.2024.2160p.WEB-DL.DDP5.1.HDR.H265.60fps-HDSWEB%2F&sort=name HTTP/1.1" 200 OK
soothing_frederic-main_app-1  | INFO:     172.17.0.1:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
soothing_frederic-main_app-1  | INFO:     172.17.0.1:0 - "GET /api/v1/user/ HTTP/1.1" 200 OK
soothing_frederic-main_app-1  | INFO:     172.17.0.1:0 - "GET /api/v1/system/env HTTP/1.1" 200 OK
soothing_frederic-main_app-1  | INFO:     172.17.0.1:0 - "GET /api/v1/system/versions HTTP/1.1" 200 OK
```

**Comment by lxlw1320** [comment]
重命名函数语句换行错误
