### ISSUE TITLE
[错误报告]: 插件页面载入失败，无限转圈圈

### ISSUE THREAD

**Issue by samyang211** [jxxghp/MoviePilot#151]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.1

### 问题类型

插件问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/14155364/539d88cc-8a4e-41d3-9b83-56021e3c5764)

部署的微1.0.0最后一个版本，测试安装了多个插件，在不确定安装某个插件后，插件页面就无法打开，如上图。
升级到1.0.1后问题仍旧存在。

### 发生问题时系统日志和配置文件

```bash
2023-08-17T03:40:26.326480218Z INFO:     210.21.229.226:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect
2023-08-17T03:40:26.376244795Z INFO:     210.21.229.226:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK
2023-08-17T03:40:28.091845881Z INFO:     210.21.229.226:0 - "GET /api/v1/history/transfer?page=1&count=25&title= HTTP/1.1" 200 OK
2023-08-17T03:40:29.558882003Z INFO:     210.21.229.226:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect
2023-08-17T03:40:29.587370286Z INFO:     210.21.229.226:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK
2023-08-17T03:40:32.543314971Z INFO:     210.21.229.226:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect
2023-08-17T03:40:32.573289565Z INFO:     210.21.229.226:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK
2023-08-17T03:40:32.693253388Z INFO:     210.21.229.226:0 - "GET /api/v1/plugin HTTP/1.1" 307 Temporary Redirect
2023-08-17T03:40:32.733447324Z INFO:     210.21.229.226:0 - "GET /api/v1/plugin/ HTTP/1.1" 500 Internal Server Error
2023-08-17T03:40:32.734761761Z ERROR:    Exception in ASGI application
2023-08-17T03:40:32.734788771Z Traceback (most recent call last):
2023-08-17T03:40:32.734811617Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2023-08-17T03:40:32.734816760Z     result = await app(  # type: ignore[func-returns-value]
2023-08-17T03:40:32.734821158Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-17T03:40:32.734825762Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-08-17T03:40:32.734830126Z     return await self.app(scope, receive, send)
2023-08-17T03:40:32.734834581Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-17T03:40:32.734839122Z   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2023-08-17T03:40:32.734843404Z     await super().__call__(scope, receive, send)
2023-08-17T03:40:32.734847613Z   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2023-08-17T03:40:32.734851850Z     await self.middleware_stack(scope, receive, send)
2023-08-17T03:40:32.734855995Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-08-17T03:40:32.734860529Z     raise exc
2023-08-17T03:40:32.734864354Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-08-17T03:40:32.734868738Z     await self.app(scope, receive, _send)
2023-08-17T03:40:32.734873190Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
2023-08-17T03:40:32.734877621Z     await self.app(scope, receive, send)
2023-08-17T03:40:32.734881288Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-08-17T03:40:32.734885735Z     raise exc
2023-08-17T03:40:32.734889978Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-08-17T03:40:32.734894826Z     await self.app(scope, receive, sender)
2023-08-17T03:40:32.734900080Z   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-08-17T03:40:32.734904635Z     raise e
2023-08-17T03:40:32.734908826Z   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-08-17T03:40:32.734913263Z     await self.app(scope, receive, send)
2023-08-17T03:40:32.734917520Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2023-08-17T03:40:32.734922253Z     await route.handle(scope, receive, send)
2023-08-17T03:40:32.734926628Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2023-08-17T03:40:32.734931399Z     await self.app(scope, receive, send)
2023-08-17T03:40:32.734936639Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2023-08-17T03:40:32.734948714Z     response = await func(request)
2023-08-17T03:40:32.734952899Z                ^^^^^^^^^^^^^^^^^^^
2023-08-17T03:40:32.734957555Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 255, in app
2023-08-17T03:40:32.734962313Z     content = await serialize_response(
2023-08-17T03:40:32.734966648Z               ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-17T03:40:32.734970905Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 141, in serialize_response
2023-08-17T03:40:32.734974133Z     raise ValidationError(errors, field.type_)
2023-08-17T03:40:32.734976937Z pydantic.error_wrappers.ValidationError: 1 validation error for Plugin
2023-08-17T03:40:32.734979890Z response -> 11 -> state
2023-08-17T03:40:32.734983176Z   value could not be parsed to a boolean (type=type_error.bool)
```

**Comment by MichaelYXQ** [comment]
重置容器试试？

**Comment by samyang211** [comment]
> 重置容器试试？

不行，从1.0.0 更新到1.0.1问题还是存在

**Comment by jxxghp** [comment]
@samyang211 仔细查看说明文档，添加代理配置代码

**Comment by samyang211** [comment]
> @samyang211 仔细查看说明文档，添加代理配置代码

请问哪个插件是必须代理的，没看到相关介绍。目前网络环境可以git tmdb就没配置代理

**Comment by jxxghp** [comment]
> > @samyang211 仔细查看说明文档，添加代理配置代码
> 
> 
> 
> 请问哪个插件是必须代理的，没看到相关介绍。目前网络环境可以git tmdb就没配置代理

如果是使用代理中转访问WEB，要加nginx配置。本地访问转圈就不知道什么情况了，可以看下浏览器控制台和网络请求和后台日志。

**Comment by LoSiTeE** [comment]
> > > @samyang211 仔细查看说明文档，添加代理配置代码
> > 
> > 
> > 请问哪个插件是必须代理的，没看到相关介绍。目前网络环境可以git tmdb就没配置代理
> 
> 如果是使用代理中转访问WEB，要加nginx配置。本地访问转圈就不知道什么情况了，可以看下浏览器控制台和网络请求和后台日志。

我也有这种情况，只能重新建立容器才能解决……
