### ISSUE TITLE
[错误报告]: 部分共享识别词存在问题

### ISSUE THREAD

**Issue by BlueflameLi** [jxxghp/MoviePilot#1554]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.8

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

` (\b[ji5-9]\b|\b[1-9][0-9]\b) \[ =>  E\1 [` 这个辅助词会影响一些标题里带数字的，如
`[ANi]殭屍 100～在成為殭屍前要做的 100 件事～ - 12 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4` 
原本能识别成功的会无法识别媒体信息

`^[\W_](.*?(?:组|組|屋|社|動漫|Lab|sub|S(?:UB|ub|tudio)|Raw(?:|s)|Production))[\W_]+(?:[\W_]+\d{1,2}(?:月(?:新|)番|国漫)[\jhiW_]+|)[\[【](.*?)[\]】] => [\1] \2 `
这个词不知道为什么在我这试了几个番的文件名，虽然都不影响正常识别但是日志里会有报错，具体见下面日志，只要注释掉这条错误就会消失，应该是这条的问题

`(?<=[\[【huh].*?(?:组|組|sub|S(?:UB|hihub|tudio)|Rawhi(?:|s)|社)[\]】])(?:(?:\[|【|★|)\d{1,2}月新番(?:\]|】|★|)|)[\[【](.*?)[\]】] => \1`
这条对于下面这种中英文之间只用空格分隔的，然后中文名还不是标准名称的会有影响
`[Amor压制组][药师少女的独语 藥師少女的獨語 Kusuriya no Hitorigoto][20][简繁内封][U-NEXTDL+NetflixSub][1080P][MKV].mkv`
去除[]后，这种格式的会忽略后面的英文名，只把中文当标题，如果中文名是标准的，或者中英文之间有 ”/“ 之类的分隔符倒是都不会有影响

除此之外还有个小问题就是，tv和anime两个文件里都有`Text.`，是否可以考虑添加时去重？

不过番剧种子命名本来就参差不齐，除了第二条确实有点问题，另外两条只能说不是完全通用就是了，可以通过其他识别词自行解决，不过还是希望能有一些更通用的辅助识别词，或者可以考虑把通用的辅助识别词单独分离出来，TV_Words和Anime_Words里只放具体的剧对应的，不容易产生冲突或者影响其他正常种子识别的。然后单独弄一个链接放通用的辅助识别词，这样用户可以更方便选择，通用识别词也很少需要更新，而特化的具体某部剧对应的识别词可以通过插件一直保持更新不用修改

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-02-27 02:01:21,019 - words.py - 自定义识别词正则替换失败：bad escape \j at position 111 - Traceback (most recent call last):
  File "/app/app/core/meta/words.py", line 77, in __replace_regex
    if not re.findall(r'%s' % replaced, title):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/regex/regex.py", line 337, in findall
    pat = _compile(pattern, flags, ignore_unused, kwargs, True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/regex/regex.py", line 546, in _compile
    raise error(caught_exception.msg, caught_exception.pattern,
regex._regex_core.error: bad escape \j at position 111

【INFO】2024-02-27 02:01:21,024 - themoviedb - 非自愿的不死冒险者 使用TMDB识别缓存：事与愿违的不死冒险者
【INFO】2024-02-27 02:01:21,026 - tmdbapi.py - 正在查询TMDB电视剧：197848 ...
【INFO】2024-02-27 02:01:21,027 - tmdbapi.py - 197848 查询结果：事与愿违的不死冒险者
【INFO】2024-02-27 02:01:21,028 - themoviedb - 非自愿的不死冒险者 TMDB识别结果：电视剧 事与愿违的不死冒险者 (2024) 197848
【INFO】2024-02-27 02:01:21,029 - media.py - [GJ.Y] 非自願的不死冒險者 - 08 (Baha 1920x1080 AVC AAC MP4) [88B7B152].mp4 识别到媒体信息：电视剧 事与愿违的不死冒险者 (2024)
【ERROR】2024-02-27 02:01:29,170 - words.py - 自定义识别词正则替换失败：bad escape \j at position 111 - Traceback (most recent call last):
  File "/app/app/core/meta/words.py", line 77, in __replace_regex
    if not re.findall(r'%s' % replaced, title):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/regex/regex.py", line 337, in findall
    pat = _compile(pattern, flags, ignore_unused, kwargs, True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/regex/regex.py", line 546, in _compile
    raise error(caught_exception.msg, caught_exception.pattern,
regex._regex_core.error: bad escape \j at position 111

【INFO】2024-02-27 02:01:29,175 - themoviedb - Shangri-La Frontier 使用TMDB识别缓存：香格里拉边境
【INFO】2024-02-27 02:01:29,176 - tmdbapi.py - 正在查询TMDB电视剧：205050 ...
【INFO】2024-02-27 02:01:29,178 - tmdbapi.py - 205050 查询结果：香格里拉边境
【INFO】2024-02-27 02:01:29,179 - themoviedb - Shangri-La Frontier TMDB识别结果：电视剧 香格里拉边境 (2023) 205050
【INFO】2024-02-27 02:01:29,181 - tmdbapi.py - 正在获取剧集组年份：64f995a3ffc9de00e133d923...
【INFO】2024-02-27 02:01:29,181 - media.py - [GJ.Y] 香格里拉・開拓異境～糞作獵手挑戰神作～ / Shangri-La Frontier - 13 (CR 1920x1080 AVC AAC MKV) 识别到媒体信息：电视剧 香格里拉边境 (2023)
【ERROR】2024-02-27 02:01:40,437 - words.py - 自定义识别词正则替换失败：bad escape \j at position 111 - Traceback (most recent call last):
  File "/app/app/core/meta/words.py", line 77, in __replace_regex
    if not re.findall(r'%s' % replaced, title):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/regex/regex.py", line 337, in findall
    pat = _compile(pattern, flags, ignore_unused, kwargs, True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/regex/regex.py", line 546, in _compile
    raise error(caught_exception.msg, caught_exception.pattern,
regex._regex_core.error: bad escape \j at position 111

【INFO】2024-02-27 02:01:40,439 - themoviedb - 不死不運 使用TMDB识别缓存：不死不幸
【INFO】2024-02-27 02:01:40,441 - tmdbapi.py - 正在查询TMDB电视剧：209077 ...
【INFO】2024-02-27 02:01:40,442 - tmdbapi.py - 209077 查询结果：不死不幸
【INFO】2024-02-27 02:01:40,443 - themoviedb - 不死不運 TMDB识别结果：电视剧 不死不幸 (2023) 209077
【INFO】2024-02-27 02:01:40,445 - tmdbapi.py - 正在获取剧集组年份：64f98ec75f2b8d00e12e3a29...
【INFO】2024-02-27 02:01:40,446 - media.py - [ANi] Undead Unluck / 不死不運 - 20 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] 识别到媒体信息：电视剧 不死不幸 (2023)
```

**Comment by BlueflameLi** [comment]
> 好像还有个问题，勾选立即运行一次保存的话，之后过滤空行会自己勾选上，不管是分两次保存，还是一次保存，似乎无法关闭过滤空行

`self._flitter = config.get("flitter") or True`这条是永远为true的吧

**Comment by BlueflameLi** [comment]
我看主要问题已经修复了，剩下两个识别词严格意义上不算bug，这个issue就关了
