### ISSUE TITLE
[错误报告]: 重启更新报错

### ISSUE THREAD

**Issue by ZevAlain** [jxxghp/MoviePilot#160]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.1

### 问题类型

Docker或运行环境问题

### 问题描述

重启更新之后报错

### 发生问题时系统日志和配置文件

```bash
前端下载成功
程序更新成功
sh: 0: getcwd() failed: No such file or directory
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at /usr/local/lib/python3.11/site-packages/playwright/driver/package/lib/utilsBundleImpl.js:35:62384
    at /usr/local/lib/python3.11/site-packages/playwright/driver/package/lib/utilsBundleImpl.js:1:222
    at Object.<anonymous> (/usr/local/lib/python3.11/site-packages/playwright/driver/package/lib/utilsBundleImpl.js:44:14503)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

Node.js v18.16.0
python3: can't open file 'app/main.py': [Errno 2] No such file or directory
```

**Comment by ZevAlain** [comment]
重新拉取镜像已解决
