### ISSUE TITLE
[错误报告]: 查看影片，经常提示 500， 未识别到媒体信息。需要重启docker才能好。

### ISSUE THREAD

**Issue by virtualhu** [jxxghp/MoviePilot#1664]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

如题，日志里有一个报错，不知是否相关：
![image](https://github.com/jxxghp/MoviePilot/assets/49012897/fa58cad4-e503-4528-87e9-b9059ef6c30e)

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-03-11 20:34:03,937 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-03-11 20:34:03,940 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-03-11 20:39:03,938 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-03-11 20:39:03,941 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-03-11 20:42:51,481 - douban - 开始发现豆瓣 电视剧 ...
【INFO】2024-03-11 20:42:51,482 - douban - 开始发现豆瓣 电影 ...
【INFO】2024-03-11 20:42:57,339 - douban - 开始获取豆瓣信息：35575567 ...
【INFO】2024-03-11 20:44:03,937 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-03-11 20:44:03,940 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-03-11 20:44:39,413 - douban - 开始获取豆瓣信息：36151692 ...
【INFO】2024-03-11 20:47:00,023 - torrents.py - 开始获取站点 m-team.io 最新种子 ...
【ERROR】2024-03-11 20:47:00,029 - scheduler.py - 定时任务 subscribe_refresh 执行失败：'NoneType' object has no attribute 'sort' - Traceback (most recent call last):
  File "/app/app/scheduler.py", line 279, in start
    job["func"](*args, **kwargs)
  File "/app/app/chain/subscribe.py", line 419, in refresh
    self.torrentschain.refresh(sites=sites)
  File "/app/app/chain/torrents.py", line 169, in refresh
    torrents.sort(key=lambda x: x.pubdate or '', reverse=True)
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sort'

【INFO】2024-03-11 20:49:03,939 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-03-11 20:49:03,942 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-03-11 20:49:33,130 - douban - 开始获取豆瓣信息：35575567 ...
```

**Comment by jxxghp** [comment]
500是因为连不上themoviedb，日志和问题现象无关。
