### ISSUE TITLE
scheduler.py - 定时任务 cookiecloud 执行失败

### ISSUE THREAD

**Issue by kingcard1131** [jxxghp/MoviePilot#1674]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

前端版本：v1.7.2，后端版本：v1.7.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

 今天突然出现scheduler.py - 定时任务 cookiecloud 执行失败，没有改动过这里 。
系统：DS920+ DSM7.2  docker bridge模式
日志如下：

### 发生问题时系统日志和配置文件

```bash
moviepilot-moviepilot-1  | ERROR:   scheduler.py - 定时任务 cookiecloud 执行失败：Expecting value: line 1 column 1 (char 0) - Traceback (most recent call last):
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
moviepilot-moviepilot-1  |     return complexjson.loads(self.text, **kwargs)
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
moviepilot-moviepilot-1  |     return _default_decoder.decode(s)
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
moviepilot-moviepilot-1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
moviepilot-moviepilot-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
moviepilot-moviepilot-1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
moviepilot-moviepilot-1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
moviepilot-moviepilot-1  | 
moviepilot-moviepilot-1  | During handling of the above exception, another exception occurred:
moviepilot-moviepilot-1  | 
moviepilot-moviepilot-1  | Traceback (most recent call last):
moviepilot-moviepilot-1  |   File "/app/app/scheduler.py", line 279, in start
moviepilot-moviepilot-1  |     job["func"](*args, **kwargs)
moviepilot-moviepilot-1  |   File "/app/app/chain/site.py", line 172, in sync_cookies
moviepilot-moviepilot-1  |     status, msg = self.test(domain)
moviepilot-moviepilot-1  |                   ^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/app/app/chain/site.py", line 307, in test
moviepilot-moviepilot-1  |     return self.special_site_test[domain](site_info)
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/app/app/chain/site.py", line 86, in __zhuque_test
moviepilot-moviepilot-1  |     user_info = user_res.json()
moviepilot-moviepilot-1  |                 ^^^^^^^^^^^^^^^
```

**Comment by gm-fire** [comment]
我也遇到了,1.7.1 是正常同步的,mp和cc都是docker部署

**Comment by jxxghp** [comment]
看起来像是朱雀这个站返回的报文不对了

**Comment by kingcard1131** [comment]
谢谢大佬，把朱雀删了，果然好了。但是我不知道这个要谁来修改，我给站点说了。
