### ISSUE TITLE
[错误报告]: autosub 插件裝不上 要如何刪除

### ISSUE THREAD

**Issue by kai456789** [jxxghp/MoviePilot#1702]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.3-2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

插件 AI字幕自动生成 安裝不上 日誌報錯 要如何刪除

### 发生问题时系统日志和配置文件

```bash
moviepilot  | INFO:    pluginautoupdate - 插件 AI字幕自动生成 更新成功，最新版本 1.0
moviepilot  | INFO:    pluginautoupdate - 开始插件重载
moviepilot  | ERROR:   module.py - 加载模块 autosub 失败：No module named 'iso639' - Traceback (most recent call last):
moviepilot  |   File "/app/app/helper/module.py", line 31, in load
moviepilot  |     module = importlib.import_module(full_package_name)
moviepilot  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
moviepilot  |     return _bootstrap._gcd_import(name[level:], package, level)
moviepilot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
moviepilot  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
moviepilot  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
moviepilot  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
moviepilot  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
moviepilot  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
moviepilot  |   File "/app/app/plugins/autosub/__init__.py", line 12, in <module>
moviepilot  |     import iso639
moviepilot  | ModuleNotFoundError: No module named 'iso639'
```

**Comment by jxxghp** [comment]
@kai456789 这是谁做的插件，要找开发者，依赖模块要加上。

**Comment by Griselda-droid** [comment]
pip install srt
pip install iso639
容器内输入代码安装依赖

**Comment by kai456789** [comment]
> pip install srt pip install iso639 容器內輸入程式碼安裝依賴

好的 不過作者 已開始修復 改版支援MP 等他處理
