### ISSUE TITLE
[错误报告]: 网络测试正常，硬链接后刮削报错

### ISSUE THREAD

**Issue by 376797822** [jxxghp/MoviePilot#1706]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.73-2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

网络测试和系统健康检查都通过，进行文件识别（手动和自动）硬链接可以识别，重命名，但是没法刮削nfo文件和jpg，日记提示如下

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-03-18 17:17:02,639 - tmdbapi.py - 正在查询TMDB电视剧：213181 ...
【INFO】2024-03-18 17:17:02,644 - tmdbapi.py - 213181 查询结果：北海道辣妹贼拉可爱
【INFO】2024-03-18 17:17:02,648 - themoviedb - Dosanko Gal Wa Namara Menkoi TMDB识别结果：电视剧 北海道辣妹贼拉可爱 (2024) 213181
【INFO】2024-03-18 17:17:02,651 - media.py - [Nekomoe kissaten][Dosanko Gal wa Namara Menkoi][01][1080p][JPSC] 识别到媒体信息：电视剧 北海道辣妹贼拉可爱 (2024)
【INFO】2024-03-18 17:17:02,657 - transfer.py - [Nekomoe kissaten][Dosanko Gal wa Namara Menkoi][01][1080p][JPSC].mp4 识别为：电视剧 北海道辣妹贼拉可爱 (2024)
【INFO】2024-03-18 17:17:02,663 - tmdbapi.py - 正在查询TMDB电视剧：213181，季：1 ...
【INFO】2024-03-18 17:17:02,674 - filetransfer - 获取转移目标路径：/pt4/media/连载动漫
【INFO】2024-03-18 17:17:02,685 - filetransfer - 正在转移文件：/pt4/download3/动漫/北海道辣妹贼拉可爱/[Nekomoe kissaten][Dosanko Gal wa Namara Menkoi][01][1080p][JPSC]/[Nekomoe kissaten][Dosanko Gal wa Namara Menkoi][01][1080p][JPSC].mp4 到 /pt4/media/连载动漫/北海道辣妹贼拉可爱 (2024)/Season 1/北海道辣妹贼拉可爱 - S01E01 - 第 1 集.mp4
【INFO】2024-03-18 17:17:02,694 - filetransfer - 文件 /pt4/download3/动漫/北海道辣妹贼拉可爱/[Nekomoe kissaten][Dosanko Gal wa Namara Menkoi][01][1080p][JPSC]/[Nekomoe kissaten][Dosanko Gal wa Namara Menkoi][01][1080p][JPSC].mp4 link完成
【INFO】2024-03-18 17:17:02,709 - filetransfer - 文件 /pt4/download3/动漫/北海道辣妹贼拉可爱/[Nekomoe kissaten][Dosanko Gal wa Namara Menkoi][01][1080p][JPSC]/[Nekomoe kissaten][Dosanko Gal wa Namara Menkoi][01][1080p][JPSC].mp4 转移成功
【INFO】2024-03-18 17:17:02,738 - themoviedb - 开始刮削媒体库文件：/pt4/media/连载动漫/北海道辣妹贼拉可爱 (2024)/Season 1/北海道辣妹贼拉可爱 - S01E01 - 第 1 集.mp4 ...
【INFO】2024-03-18 17:17:02,745 - scraper.py - 正在下载backdrop图片：https://image.tmdb.org/t/p/original/vsVhyFhtJ6XBc0FkVQpvqsPjNm7.jpg ...
【WARNING】2024-03-18 17:17:03,221 - common.py - , 3 秒后重试 ...
【INFO】2024-03-18 17:17:06,227 - scraper.py - 正在下载backdrop图片：https://image.tmdb.org/t/p/original/vsVhyFhtJ6XBc0FkVQpvqsPjNm7.jpg ...
【WARNING】2024-03-18 17:17:06,705 - common.py - , 6 秒后重试 ...
【INFO】2024-03-18 17:17:12,711 - scraper.py - 正在下载backdrop图片：https://image.tmdb.org/t/p/original/vsVhyFhtJ6XBc0FkVQpvqsPjNm7.jpg ...
【ERROR】2024-03-18 17:17:13,231 - scraper.py - /pt4/media/连载动漫/北海道辣妹贼拉可爱 (2024)/Season 1/北海道辣妹贼拉可爱 - S01E01 - 第 1 集.mp4 刮削失败： - Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='image.tmdb.org', port=443): Max retries exceeded with url: /t/p/original/vsVhyFhtJ6XBc0FkVQpvqsPjNm7.jpg (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app/utils/http.py", line 117, in get_res
    return requests.get(url,
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='image.tmdb.org', port=443): Max retries exceeded with url: /t/p/original/vsVhyFhtJ6XBc0FkVQpvqsPjNm7.jpg (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app/modules/themoviedb/scraper.py", line 94, in gen_scraper_files
    self.__save_image(url=attr_value,
  File "/app/app/utils/common.py", line 35, in f_retry
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/themoviedb/scraper.py", line 373, in __save_image
    raise err
  File "/app/app/modules/themoviedb/scraper.py", line 363, in __save_image
    r = RequestUtils(proxies=settings.PROXY).get_res(url=url, raise_exception=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/utils/http.py", line 130, in get_res
    raise requests.exceptions.RequestException
requests.exceptions.RequestException
```

**Comment by 376797822** [comment]
api使用api.tmdb和另一个都试过了，刮削来源tmdb和豆瓣也都试过，结果没变

**Comment by 376797822** [comment]
只有tvshow.nfo能正常生成

**Comment by 376797822** [comment]
解决了，容器是host的，重新建立bridge模式的就好了
