### ISSUE TITLE
[错误报告]: 一直出现系统错误! 几个版本都这样！

### ISSUE THREAD

**Issue by hollis-sun** [jxxghp/MoviePilot#1799]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。

### 当前程序版本

1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

几个版本都有这个错误,几天更新最新的之后系统卡死启动之后点网页无效一直在卡

<img width="684" alt="屏幕截图 2024-03-31 204602" src="https://github.com/jxxghp/MoviePilot/assets/48936549/25ddaa1c-8ccd-41f6-97ab-05ef85641f4c">

ERROR:   module.py - 加载模块 pushdeermsg 失败：No module named 'pypushdeer' - Traceback (most recent call last):
  File "/app/app/helper/module.py", line 31, in load
    module = importlib.import_module(full_package_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app/plugins/pushdeermsg/__init__.py", line 3, in <module>
    from pypushdeer import PushDeer
ModuleNotFoundError: No module named 'pypushdeer'

ERROR:   module.py - 加载模块 vcbanimemonitor 失败：No module named 'roman' - Traceback (most recent call last):
  File "/app/app/helper/module.py", line 31, in load
    module = importlib.import_module(full_package_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app/plugins/vcbanimemonitor/__init__.py", line 29, in <module>
    from app.plugins.vcbanimemonitor.remeta import ReMeta
  File "/app/app/plugins/vcbanimemonitor/remeta.py", line 6, in <module>
    import roman
ModuleNotFoundError: No module named 'roman'

**Comment by jxxghp** [comment]
都是第三方插件依赖没装的报错，拉最新镜像，重置。

**Comment by sylee9695** [comment]
我也遇到同样的报错，拉取最新镜像依然如此

**Comment by tardlk** [comment]
同样问题，今天拉取了最新镜像还是这样

**Comment by latel** [comment]
同样问题，今天拉取了最新镜像还是这样
