### ISSUE TITLE
[错误报告]: 不知名错误日志，具体影响不知

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#1801]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

发现错误日志不知道有什么具体影响

### 发生问题时系统日志和配置文件

```bash
ModuleNotFoundError: No module named 'roman'
    import roman
  File "/app/app/plugins/vcbanimemonitor/remeta.py", line 6, in <module>
    from app.plugins.vcbanimemonitor.remeta import ReMeta
  File "/app/app/plugins/vcbanimemonitor/__init__.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    module = importlib.import_module(full_package_name)
  File "/app/app/helper/module.py", line 31, in load
【ERROR】2024-03-31 22:23:56,056 - module.py - 加载模块 vcbanimemonitor 失败：No module named 'roman' - Traceback (most recent call last):

ModuleNotFoundError: No module named 'pypushdeer'
    from pypushdeer import PushDeer
  File "/app/app/plugins/pushdeermsg/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    module = importlib.import_module(full_package_name)
  File "/app/app/helper/module.py", line 31, in load
【ERROR】2024-03-31 22:23:55,605 - module.py - 加载模块 pushdeermsg 失败：No module named 'pypushdeer' - Traceback (most recent call last):
【INFO】2024-03-31 22:23:54,211 - plugin.py - 第三方插件安装完成
```

**Comment by cddjr** [comment]
手动安装依赖可解决，执行 `find /app/app/plugins -name requirements.txt -exec pip install ${PIP_OPTIONS} -r {} \;`

**Comment by dlovew** [comment]
> 手动安装依赖可解决，执行 `find /app/app/plugins -name requirements.txt -exec pip install -r {} \;`

容器内还是宿主机执行啊

**Comment by cddjr** [comment]
> > 手动安装依赖可解决，执行 `find /app/app/plugins -name requirements.txt -exec pip install -r {} \;`
> 
> 容器内还是宿主机执行啊

MP容器内

**Comment by dlovew** [comment]
> find /app/app/plugins -name requirements.txt -exec pip install -r {} \

安装了没什么用，而且看requirements.txt里面好像也没有日志报错的相关模块

**Comment by dlovew** [comment]
> find /app/app/plugins -name requirements.txt -exec pip install -r {} \

安装了没什么用，而且看requirements.txt里面好像也没有日志报错的相关模块

**Comment by BlueflameLi** [comment]
我这边也遇到了同样的报错，这两个插件都是我从来没安装过的插件，所以实际上也没什么影响，试了下只要安装了这个插件就不会再有这个报错

**Comment by goxofy** [comment]
我也有同样问题

**Comment by cmcuiliu** [comment]
> 手动安装依赖可解决，执行 `find /app/app/plugins -name requirements.txt -exec pip install -r {} \;`
安装了这个没看见有报错了。

**Comment by cmcuiliu** [comment]
> 手动安装依赖可解决，执行 `find /app/app/plugins -name requirements.txt -exec pip install -r {} \;`

安装了这个没有看见有报错了。

**Comment by autunn** [comment]
[Uploading logging.txt…]()
错误日志在这里，希望大佬能看到

**Comment by jxxghp** [comment]
有些插件依赖没装，其实是没影响的，最新版本已经屏蔽了。
