### ISSUE TITLE
[错误报告]: “历史记录同步”插件的问题

### ISSUE THREAD

**Issue by LoSiTeE** [jxxghp/MoviePilot#184]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.2

### 问题类型

插件问题

### 问题描述

刚刚想同步nastool数据，只填写了user.db的路径，然后点了确定然后日志报错无法打开文件。于是重启了容器，把nastool的user.db路径映射至容器，再打开容器后，历史记录同步插件就一片空白，像这样（同时日志报错，附在下面日志栏）
![image](https://github.com/jxxghp/MoviePilot/assets/125968595/1c3d8cbf-06e2-4572-9173-55b52dea74f5)

### 发生问题时系统日志和配置文件

```bash
2023-08-19 15:05:43,204 - module.py -【INFO】Moudle Loaded：JellyfinModule
2023-08-19 15:05:43,210 - module.py -【INFO】Moudle Loaded：QbittorrentModule
2023-08-19 15:05:44,697 - client.py -【INFO】A new session has been established (session id: 86b0ad16-6547-4be3-815a-d25bd766c497)
2023-08-19 15:05:44,697 - slack.py -【INFO】Slack消息接收服务启动
2023-08-19 15:05:44,697 - module.py -【INFO】Moudle Loaded：SlackModule
2023-08-19 15:05:44,697 - module.py -【INFO】Moudle Loaded：SubtitleModule
2023-08-19 15:05:44,698 - module.py -【INFO】Moudle Loaded：TheMovieDbModule
2023-08-19 15:05:44,698 - module.py -【INFO】Moudle Loaded：TheTvDbModule
2023-08-19 15:05:44,725 - client.py -【INFO】Starting to receive messages from a new connection (session id: 86b0ad16-6547-4be3-815a-d25bd766c497)
2023-08-19 15:05:44,808 - plugin.py -【INFO】Plugin Loaded：AutoSignIn
2023-08-19 15:05:44,812 - plugin.py -【INFO】Plugin Loaded：SiteStatistic
2023-08-19 15:05:44,812 - plugin.py -【INFO】Plugin Loaded：DoubanSync
2023-08-19 15:05:44,812 - plugin.py -【INFO】Plugin Loaded：DirMonitor
2023-08-19 15:05:44,813 - plugin.py -【INFO】Plugin Loaded：ChineseSubFinder
2023-08-19 15:05:44,813 - plugin.py -【INFO】Plugin Loaded：LibraryScraper
2023-08-19 15:05:44,813 - plugin.py -【INFO】Plugin Loaded：TorrentRemover
2023-08-19 15:05:44,813 - plugin.py -【INFO】Plugin Loaded：MediaSyncDel
2023-08-19 15:05:44,813 - plugin.py -【INFO】Plugin Loaded：CustomHosts
2023-08-19 15:05:44,813 - plugin.py -【INFO】Plugin Loaded：SpeedLimiter
2023-08-19 15:05:44,813 - plugin.py -【INFO】Plugin Loaded：CloudflareSpeedTest
2023-08-19 15:05:44,813 - plugin.py -【INFO】Plugin Loaded：BestFilmVersion
2023-08-19 15:05:44,814 - plugin.py -【INFO】Plugin Loaded：WebHook
2023-08-19 15:05:44,814 - plugin.py -【INFO】Plugin Loaded：ChatGPT
2023-08-19 15:05:44,815 - plugin.py -【ERROR】加载插件 NAStoolSync 出错：unable to open database file - Traceback (most recent call last):
File "/app/app/core/plugin.py", line 62, in start
plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
File "/app/app/plugins/nastoolsync/__init__.py", line 65, in init_plugin
gradedb = sqlite3.connect(self._nt_db_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
2023-08-19 15:05:44,815 - plugin.py -【INFO】Plugin Loaded：MessageForward
2023-08-19 15:05:44,815 - plugin.py -【INFO】Plugin Loaded：AutoBackup
2023-08-19 15:05:44,815 - plugin.py -【INFO】Plugin Loaded：IYUUAutoSeed
2023-08-19 15:05:44,815 - plugin.py -【INFO】Plugin Loaded：TorrentTransfer
2023-08-19 15:05:44,815 - plugin.py -【INFO】Plugin Loaded：RssSubscribe
2023-08-19 15:06:08,518 - __init__.py -【ERROR】运行模块 media_statistic 出错：JellyfinModule - 'NoneType' object has no attribute 'get'
None
2023-08-19 15:06:44,816 - cookiecloud.py -【INFO】开始同步CookieCloud站点 ...
2023-08-19 15:06:46,815 - cookiecloud.py -【INFO】站点【馒头】连通性正常，不同步CookieCloud数据
2023-08-19 15:06:48,122 - cookiecloud.py -【INFO】站点【铂金家】连通性正常，不同步CookieCloud数据
2023-08-19 15:06:49,364 - cookiecloud.py -【INFO】站点【天雪】连通性正常，不同步CookieCloud数据
2023-08-19 15:06:50,687 - cookiecloud.py -【INFO】站点【自由农场】连通性正常，不同步CookieCloud数据
2023-08-19 15:06:57,504 - cookiecloud.py -【INFO】站点【学校】连通性正常，不同步CookieCloud数据
2023-08-19 15:07:19,273 - cookiecloud.py -【INFO】站点【他吹吹风】连通性正常，不同步CookieCloud数据
2023-08-19 15:07:19,274 - cookiecloud.py -【INFO】CookieCloud同步成功：更新了0个站点，新增了0个站点
2023-08-19 15:10:44,816 - mediaserver.py -【INFO】开始同步媒体库数据 ...
2023-08-19 15:10:44,823 - transfer.py -【INFO】开始执行下载器文件转移 ...
2023-08-19 15:10:44,827 - mediaserver.py -【INFO】【MediaServer】媒体库数据同步完成，同步数量：0
2023-08-19 15:10:44,868 - transfer.py -【INFO】没有获取到已完成的下载任务
```

**Comment by thsrite** [comment]
更新完再试试还有问题吗

**Comment by LoSiTeE** [comment]
> 更新完再试试还有问题吗

更新至1.0.3，没有改善，还是这个问题
