### ISSUE TITLE
[错误报告]: Windows版本1.8.0无法登录

### ISSUE THREAD

**Issue by eatumom** [jxxghp/MoviePilot#1879]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

无法登录

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

Windows版本1.8.0无法登录 换了多台PC都如此

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-04-12 17:05:24,735 - init.pyc - 【超级管理员初始密码】DdTfeCErLlrqmbI7 请登录系统后在设定中修改。 注：该密码只会显示一次，请注意保存。
【INFO】2024-04-12 17:05:25,020 - singleton.pyc - 站点资源版本：1.2.8
【INFO】2024-04-12 17:05:25,024 - singleton.pyc - 认证资源版本：1.2.4
【INFO】2024-04-12 17:05:25,635 - singleton.pyc - hdfans 用户认证成功！
【INFO】2024-04-12 17:05:25,790 - category.pyc - 已加载二级分类策略 category.yaml
【INFO】2024-04-12 17:05:25,792 - module.pyc - Moudle Loaded：TheMovieDbModule
【INFO】2024-04-12 17:05:25,796 - module.pyc - Moudle Loaded：IndexerModule
【INFO】2024-04-12 17:05:25,798 - module.pyc - Moudle Loaded：EmbyModule
【INFO】2024-04-12 17:05:25,800 - module.pyc - Moudle Loaded：TelegramModule
【INFO】2024-04-12 17:05:25,802 - module.pyc - Moudle Loaded：TheTvDbModule
【INFO】2024-04-12 17:05:25,804 - module.pyc - Moudle Loaded：BangumiModule
【INFO】2024-04-12 17:05:25,806 - module.pyc - Moudle Loaded：FileTransferModule
【INFO】2024-04-12 17:05:25,809 - module.pyc - Moudle Loaded：QbittorrentModule
【INFO】2024-04-12 17:05:25,811 - module.pyc - Moudle Loaded：DoubanModule
【INFO】2024-04-12 17:05:25,814 - module.pyc - Moudle Loaded：FilterModule
【INFO】2024-04-12 17:05:25,816 - module.pyc - Moudle Loaded：SubtitleModule
【INFO】2024-04-12 17:05:25,819 - module.pyc - Moudle Loaded：FanartModule
【ERROR】2024-04-12 17:05:25,973 - module.pyc - 加载模块 vcbanimemonitor 失败：No module named 'roman' - Traceback (most recent call last):
  File "app\helper\module.py", line 31, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app\plugins\vcbanimemonitor\__init__.py", line 29, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app\plugins\vcbanimemonitor\remeta.py", line 6, in <module>
ModuleNotFoundError: No module named 'roman'

【ERROR】2024-04-12 17:05:26,349 - module.pyc - 加载模块 pushdeermsg 失败：No module named 'pypushdeer' - Traceback (most recent call last):
  File "app\helper\module.py", line 31, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app\plugins\pushdeermsg\__init__.py", line 3, in <module>
ModuleNotFoundError: No module named 'pypushdeer'
```

**Comment by cddjr** [comment]
问题详细点吧，是 看不到登录页面？ 点击登录没反应？ 密码错误无法登录？

**Comment by eatumom** [comment]
> 问题详细点吧，是 看不到登录页面？ 点击登录没反应？ 密码错误无法登录？

登录页面输入日志里生成的密码显示 登录失败，请检查用户名、密码或双重验证是否正确

**Comment by eatumom** [comment]
> > 问题详细点吧，是 看不到登录页面？ 点击登录没反应？ 密码错误无法登录？
> 
> 登录页面输入日志里生成的密码显示 登录失败，请检查用户名、密码或双重验证是否正确

找到问题了apiport被占用了
