### ISSUE TITLE
在启动时，命令行显示的新的报错

### ISSUE THREAD

**Issue by autunn** [jxxghp/MoviePilot#1886]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在群晖docker启动时，打开终端机查看启动状态时看到的报错，在chatgpt也没有找到解决办法
### 发生问题时系统日志和配置文件

```bash
ERROR:   module.py - 加载模块 downloadsitetag 失败：cannot import name 'TmdbHelpe
r' from 'app.modules.themoviedb.tmdbapi' (/app/app/modules/themoviedb/tmdbapi.py)
 - Traceback (most recent call last):                                            
  File "/app/app/helper/module.py", line 31, in load                             
    module = importlib.import_module(full_package_name)                          
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_mod
ule                                                                              
    return _bootstrap._gcd_import(name[level:], package, level)                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import                
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load             
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked    
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked              
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module        
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed   
  File "/app/app/plugins/downloadsitetag/__init__.py", line 16, in <module>      
    from app.modules.themoviedb.tmdbapi import TmdbHelper                        
ImportError: cannot import name 'TmdbHelper' from 'app.modules.themoviedb.tmdbapi
' (/app/app/modules/themoviedb/tmdbapi.py)
```

**Comment by hh0610** [comment]
下载任务分类与标签这个插件从新安装然后重启系统就不会了

**Comment by yujianhui21** [comment]
就是更新一下，刚才看代码，发现下载任务分类与标签这个插件默认使用的不是最新的，更新一下就可以正常使用了

**Comment by autunn** [comment]
> 下载任务分类与标签这个插件从新安装然后重启系统就不会了

我没装这个插件啊，难道只要有了这个插件的库，就会默认安装依赖？
