### ISSUE TITLE
[错误报告]: 无法打开订阅菜单

### ISSUE THREAD

**Issue by yunjie-li** [jxxghp/MoviePilot#1902]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

打开订阅菜单，一直转圈。看了接口，在请求/api/v1/subscribe/时报了500错误。
![image](https://github.com/jxxghp/MoviePilot/assets/15187773/34403ed7-89dd-40d6-997c-2ea3762fe521)

### 发生问题时系统日志和配置文件

```bash
INFO:     192.168.2.253:0 - "GET /api/v1/system/message?token=***** HTTP/1.1" 200 OK
INFO:     192.168.2.253:0 - "GET /api/v1/subscribe/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 255, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Subscribe
response -> 0 -> sites
  value is not a valid list (type=type_error.list)
```

**Comment by jxxghp** [comment]
维护站点了吗？

**Comment by yunjie-li** [comment]
我把站点清理过重新同步了一下，又手动添加了馒头

**Comment by 200506818** [comment]
我也遇到和你一样的问题

**Comment by jxxghp** [comment]
确认浏览器缓存清理干净了没有。

**Comment by woshidaifu** [comment]
我这里好了，刚好因为升级1.8.3版本之后密码不正确，把db文件删了之后重新配置密码，之后订阅就ok了

**Comment by mapupu-real** [comment]
按这个方法尝试之后短暂好了一下，添加了几个订阅之后又开始转圈打不开了
> 我这里好了，刚好因为升级1.8.3版本之后密码不正确，把db文件删了之后重新配置密码，之后订阅就ok了

**Comment by cng10001** [comment]
> 我这里好了，刚好因为升级1.8.3版本之后密码不正确，把db文件删了之后重新配置密码，之后订阅就ok了

db文件删了是不是订阅和配置都没有了?

**Comment by woshidaifu** [comment]
容器配置的话，主要的配置文件都是宿主磁盘与容器映射目录里的，大部分都在的；订阅确实就没了，我这边后来一直都是好的了
