### ISSUE TITLE
[错误报告]:1、py模块无法加载；2、日志没有管理员密码

### ISSUE THREAD

**Issue by fictioner** [jxxghp/MoviePilot#1904]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

ASUS路由器安装有科学上网插件，谷歌等都正常访问，但安装MP时，容器日志报错：
1、py模块无法加载；
2、日志没有管理员密码

### 发生问题时系统日志和配置文件

```bash
不使用代理更新程序
Release 更新模式
当前版本号：v1.8.1
最新版本号：v1.8.1
未发现新版本，跳过更新步骤...
[32mINFO:[0m doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
[32mINFO:[0m plugin.py - 共获取到 43 个第三方插件
[32mINFO:[0m plugin.py - 第三方插件安装完成
[31mERROR:[0m module.py - 加载模块 pushdeermsg 失败：No module named 'pypushdeer' - Traceback (most recent call last):
File "/app/app/helper/module.py", line 31, in load
module = importlib.import_module(full_package_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/app/app/plugins/pushdeermsg/__init__.py", line 3, in <module>
from pypushdeer import PushDeer
ModuleNotFoundError: No module named 'pypushdeer'

[31mERROR:[0m module.py - 加载模块 vcbanimemonitor 失败：No module named 'roman' - Traceback (most recent call last):
File "/app/app/helper/module.py", line 31, in load
module = importlib.import_module(full_package_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/app/app/plugins/vcbanimemonitor/__init__.py", line 29, in <module>
from app.plugins.vcbanimemonitor.remeta import ReMeta
File "/app/app/plugins/vcbanimemonitor/remeta.py", line 6, in <module>
import roman
ModuleNotFoundError: No module named 'roman'
```

**Comment by jxxghp** [comment]
1、插件的问题，无视它。
2、不能的，肯定有，看清楚说明文档中的说明。

**Comment by fictioner** [comment]
删除配置文件目录下的user.db文件，然后重启服务后看到了。谢谢！
