### ISSUE TITLE
[错误报告]: 模块 filter_torrents 出错：FilterModule - Expected '|' term, found '订'

### ISSUE THREAD

**Issue by Ice-Cream-MY** [jxxghp/MoviePilot#1927]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.1.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/76402568/d3ea5fc4-b7f4-4aa8-87e7-c3f2d9048f8d)

订阅时显示如图错误
![image](https://github.com/jxxghp/MoviePilot/assets/76402568/7bdf8978-3c65-47d4-ab8c-84e611b2de0f)

### 发生问题时系统日志和配置文件

```bash
ERROR:   chain - 运行模块 filter_torrents 出错：FilterModule - Expected '|' term, found '订'  (at char 0), (line:1, col:1)
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 101, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filter/__init__.py", line 171, in filter_torrents
    if not self.__get_order(torrent, rule_string):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filter/__init__.py", line 222, in __get_order
    parsed_group = self.parser.parse(rule_group.strip())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filter/RuleParser.py", line 39, in parse
    return self.expr.parseString(expression)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected '|' term, found '订'  (at char 0), (line:1, col:1)
```

**Comment by jxxghp** [comment]
你的设定里的优先级规则配的有问题？重新配置下。
