### ISSUE TITLE
电影订阅搜索完成已经触发下载，没办法完成订阅

### ISSUE THREAD

**Issue by bestfang** [jxxghp/MoviePilot#1960]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.3

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

订阅无法自动完成，需要手动删除

### 发生问题时系统日志和配置文件

```bash
(Background on this error at: https://sqlalche.me/e/20/gkpj)
[parameters: (80, '破墓', '2024', '电影', None, 838209, 'tt27802490', None, None, None, 0, 'https://image.tmdb.org/t/p/w500/3NDHFOSmAW8TStkGNRThPTSd4dx.jpg', 'https://image.tmdb.org/t/p/w500/aINel9503ompOlGKn4sIVMg09Un.jpg', 7.8, '影片讲述接受巨额资金委托移葬可疑墓地的风水师和同行的葬仪师、巫女之间发生的奇异事件。', None, None, None, None, None, None, None, None, '2024-04-26 11:18:41', 'admin', None, 0, None, 0)]
[SQL: INSERT INTO subscribehistory (id, name, year, type, keyword, tmdbid, imdbid, tvdbid, doubanid, bangumiid, season, poster, backdrop, vote, description, filter, include, exclude, quality, resolution, effect, total_episode, start_episode, date, username, sites, best_version, save_path, search_imdbid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: subscribehistory.id
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self._exec_single_context(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
          ^^^^^^^^^^^^^^^^^^^^^^
    ret = self._execute_context(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
           ^^^^^
    return meth(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
             ^^^^^^^^^^^^^^^^^^^
    result = connection.execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
    _emit_insert_statements(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    flush_context.execute()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    with util.safe_reraise():
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    self._flush(objects)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self.session.flush()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
                ^^^^^^^^^^^^^^^^^^^^
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
  File "<string>", line 2, in _prepare_impl
    self._prepare_impl()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
                ^^^^^^^^^^^^^^^^^^^^
    ret_value = fn(self, *arg, **kw)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
  File "<string>", line 2, in commit
    trans.commit(_to_root=True)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    db.commit()
  File "/app/app/db/__init__.py", line 95, in wrapper
    raise err
  File "/app/app/db/__init__.py", line 99, in wrapper
    subscribe.create(self._db)
  File "/app/app/db/subscribehistory_oper.py", line 21, in add
    self.subscribehistoryoper.add(**subscribe.to_dict())
  File "/app/app/chain/subscribe.py", line 415, in finish_subscribe_or_not
    self.finish_subscribe_or_not(subscribe=subscribe, meta=meta, mediainfo=mediainfo, force=True)
  File "/app/app/chain/subscribe.py", line 265, in search
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 286, in start
Traceback (most recent call last):

The above exception was the direct cause of the following exception:

sqlite3.IntegrityError: UNIQUE constraint failed: subscribehistory.id
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
(Background on this error at: https://sqlalche.me/e/20/gkpj) - Traceback (most recent call last):
[parameters: (80, '破墓', '2024', '电影', None, 838209, 'tt27802490', None, None, None, 0, 'https://image.tmdb.org/t/p/w500/3NDHFOSmAW8TStkGNRThPTSd4dx.jpg', 'https://image.tmdb.org/t/p/w500/aINel9503ompOlGKn4sIVMg09Un.jpg', 7.8, '影片讲述接受巨额资金委托移葬可疑墓地的风水师和同行的葬仪师、巫女之间发生的奇异事件。', None, None, None, None, None, None, None, None, '2024-04-26 11:18:41', 'admin', None, 0, None, 0)]
[SQL: INSERT INTO subscribehistory (id, name, year, type, keyword, tmdbid, imdbid, tvdbid, doubanid, bangumiid, season, poster, backdrop, vote, description, filter, include, exclude, quality, resolution, effect, total_episode, start_episode, date, username, sites, best_version, save_path, search_imdbid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
【ERROR】2024-04-26 11:18:41,221 - scheduler.py - 定时任务 new_subscribe_search 执行失败：(sqlite3.IntegrityError) UNIQUE constraint failed: subscribehistory.id
```

**Comment by jxxghp** [comment]
v1.8.4已解决
