### ISSUE TITLE
[错误报告]: 订阅报错

### ISSUE THREAD

**Issue by latel** [jxxghp/MoviePilot#1965]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.3

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

电影订阅报错

### 发生问题时系统日志和配置文件

```bash
2024-04-26T05:12:53.701696274Z INFO:    subscribe.py - 开始搜索订阅，标题：怦然心动 ...
2024-04-26T05:12:53.766321314Z INFO:    tmdbapi.py - 正在查询TMDB电影：43949 ...
2024-04-26T05:12:53.767839122Z INFO:    tmdbapi.py - 43949 查询结果：怦然心动
2024-04-26T05:12:53.769011180Z INFO:    themoviedb - 怦然心动 TMDB识别结果：电影 怦然心动 (2010) 43949
2024-04-26T05:12:54.104621398Z INFO:    jellyfin - 怦然心动 (2010) 在媒体库中不存在
2024-04-26T05:12:54.105656034Z INFO:    search.py - 开始搜索资源，关键词：怦然心动 ...
2024-04-26T05:12:54.108775600Z INFO:    spider.py - 开始请求：https://hdatmos.club/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E6%80%A6%E7%84%B6%E5%BF%83%E5%8A%A8&cat401=1&cat405=1&cat404=1
2024-04-26T05:12:54.110973912Z INFO:    spider.py - 开始请求：https://ptcafe.club/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E6%80%A6%E7%84%B6%E5%BF%83%E5%8A%A8&cat401=1&cat405=1&cat404=1
2024-04-26T05:12:54.111229664Z INFO:    spider.py - 开始请求：https://www.pttime.org/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E6%80%A6%E7%84%B6%E5%BF%83%E5%8A%A8&cat401=1&cat430=1&cat431=1&cat404=1
2024-04-26T05:12:54.111612534Z INFO:    spider.py - 开始请求：https://hdarea.club/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E6%80%A6%E7%84%B6%E5%BF%83%E5%8A%A8&cat300=1&cat401=1&cat415=1&cat416=1&cat410=1&cat411=1&cat414=1&cat412=1&cat413=1&cat417=1&cat405=1&cat404=1
2024-04-26T05:12:54.112804243Z INFO:    spider.py - 开始请求：https://www.icc2022.com/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E6%80%A6%E7%84%B6%E5%BF%83%E5%8A%A8&cat401=1&cat405=1&cat404=1
2024-04-26T05:12:54.114446303Z INFO:    spider.py - 开始请求：https://rousi.zip/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E6%80%A6%E7%84%B6%E5%BF%83%E5%8A%A8&cat401=1&cat405=1&cat404=1
2024-04-26T05:12:54.116256304Z INFO:    spider.py - 开始请求：https://carpt.net/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E6%80%A6%E7%84%B6%E5%BF%83%E5%8A%A8&cat401=1&cat403=1&cat404=1
2024-04-26T05:12:54.119122373Z INFO:    spider.py - 开始请求：https://ptchina.org/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E6%80%A6%E7%84%B6%E5%BF%83%E5%8A%A8&cat401=1&cat404=1
2024-04-26T05:12:55.330848371Z INFO:    indexer - 咖啡 搜索完成，耗时 1 秒，返回数据：1
2024-04-26T05:12:55.331879387Z INFO:    search.py - 站点搜索进度：1 / 8
2024-04-26T05:12:56.421217153Z INFO:    spider.py - 开始请求：https://ptchina.org/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=Flipped&cat401=1&cat404=1
2024-04-26T05:12:56.447736796Z INFO:    spider.py - 开始请求：https://hdatmos.club/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=Flipped&cat401=1&cat405=1&cat404=1
2024-04-26T05:12:56.473222479Z INFO:    indexer - Rousi 搜索完成，耗时 2 秒，返回数据：4
2024-04-26T05:12:56.474270333Z INFO:    search.py - 站点搜索进度：2 / 8
2024-04-26T05:12:56.558778989Z INFO:    indexer - CARPT 搜索完成，耗时 2 秒，返回数据：2
2024-04-26T05:12:56.559682356Z INFO:    search.py - 站点搜索进度：3 / 8
2024-04-26T05:12:57.341752660Z INFO:    spider.py - 开始请求：https://www.icc2022.com/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=Flipped&cat401=1&cat405=1&cat404=1
2024-04-26T05:12:57.435356082Z INFO:    indexer - 高清视界 搜索完成，耗时 3 秒，返回数据：20
2024-04-26T05:12:57.436437137Z INFO:    search.py - 站点搜索进度：4 / 8
2024-04-26T05:12:58.268555526Z INFO:    indexer - PT时间 搜索完成，耗时 4 秒，返回数据：4
2024-04-26T05:12:58.269467591Z INFO:    search.py - 站点搜索进度：5 / 8
2024-04-26T05:12:58.580381147Z WARNING: indexer - 铂金学院 未搜索到数据，耗时 4 秒
2024-04-26T05:12:58.581404809Z INFO:    search.py - 站点搜索进度：6 / 8
2024-04-26T05:12:59.022082013Z INFO:    indexer - 阿童木 搜索完成，耗时 4 秒，返回数据：4
2024-04-26T05:12:59.023104609Z INFO:    search.py - 站点搜索进度：7 / 8
2024-04-26T05:13:00.175868576Z WARNING: indexer - 冰淇淋 未搜索到数据，耗时 6 秒
2024-04-26T05:13:00.176941478Z INFO:    search.py - 站点搜索进度：8 / 8
2024-04-26T05:13:00.177928579Z INFO:    search.py - 站点搜索完成，有效资源数：35，总耗时 6 秒
2024-04-26T05:13:00.178768634Z INFO:    search.py - 开始匹配结果 标题：怦然心动，原标题：Flipped，别名：['萌动青春', '冒失', '青春萌动', '梧桐树之恋', 'Flipped - Il primo amore non si scorda mai', '怦然心动', 'O Primeiro Amor', 'Привет, Джули!', 'İlk Aşk', "Un Cœur à l'envers", 'Verliebt und ausgeflippt', 'Változó szerelem', 'Dziewczyna i chłopak wszystko na opak', 'Flipped', 'Má mě rád, nemá mě rád', 'Пут љубави', 'Πρώτη Αγάπη', '플립', 'הפכים', 'Насмешливо', 'Привіт, Джулі!', 'Il primo amore non si scorda mai', 'Juli și Bryce', 'Mi Primer Amor', '怦然心動', '初戀', 'Įsimylėjęs iki ausų', 'Má ma rád, nemá ma rád', 'Một Thuở Tình Thơ', 'FLIPPED - 2010']
2024-04-26T05:13:00.180546152Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：咖啡 - Flipped 2010 BluRay 1080p 2Audio DTS-HD MA5.1 x265 10bit-BeiTai
2024-04-26T05:13:00.181825306Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：Rousi - Flipped 2010 BluRay 1080p x264 DTS 2Audios-CMCT
2024-04-26T05:13:00.183067399Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：Rousi - Flipped 2010 BluRay 1080p x265 10bit AC3 MNHD-FRDS
2024-04-26T05:13:00.184143973Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：Rousi - Flipped 2010 Blu-Ray 1080p 2Audio DTS-HD MA 5.1 x264-beAst
2024-04-26T05:13:00.185430005Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：Rousi - Flipped 2010 BluRay 1080p 2Audio DTS-HD MA5.1 x265 10bit-BeiTai
2024-04-26T05:13:00.186747041Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：CARPT - 怦然心动 2010 Flipped 2010 1080p BluRay AVC DTS-HD MA 5.1-GKD@Audies
2024-04-26T05:13:00.187907274Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：CARPT - Flipped 2010 1080p BluRay x265 10bit DTS-WiKi
2024-04-26T05:13:00.189074540Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 1080p BluRay AVC DTS-HD MA 5.1-GKD@Audies
2024-04-26T05:13:00.190242557Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 720p BluRay x264 DTS-HDChina
2024-04-26T05:13:00.191298548Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 BD 1080p x265 10bit DD5.1 3Audios-FFans@leon
2024-04-26T05:13:00.192278448Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 1080p BluRay x264 DTS-WiKi
2024-04-26T05:13:00.193264035Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 1080p BluRay x265 10bit DTS-WiKi
2024-04-26T05:13:00.194355710Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 BluRay 1080p 2Audio DTS-HD MA 5.1 x265 10bit-BeiTai
2024-04-26T05:13:00.195334716Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped  2010 1080p AVC DTS-HD MA
2024-04-26T05:13:00.196338419Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 BluRay 1080p x265 10bit 2Audio MNHD-FRDS
2024-04-26T05:13:00.197502809Z WARNING: torrent.py - 高清视界 - Kuch Kuch Hota Hai 1998 1080p Bluray x264 DTS-HD MA 5.1-Hon3yHD 年份不匹配 2010
2024-04-26T05:13:00.198560944Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 Blu-Ray 1080p 2Audio DTS-HD MA 5.1 x264-beAst
2024-04-26T05:13:00.199663049Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 ViE mHD BluRay DD5.1 x264-EPiK
2024-04-26T05:13:00.200741926Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 BluRay 720p x264 AC3-CMCT
2024-04-26T05:13:00.202135581Z WARNING: torrent.py - 高清视界 - Flipped 2010 1080p Blu-ray AVC DTS-HD MA 5.1-DIY@miracle1934 种子标题类型为 电视剧，不匹配 电影
2024-04-26T05:13:00.203232019Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 1080p Blu-ray REMUX AVC DTS-HD MA 5.1-HDArea
2024-04-26T05:13:00.204281822Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 1080p Blu-ray AVC DTS-HD MA 5.1-CtrlHD
2024-04-26T05:13:00.205386200Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 1080p BluRay DTS-HD MA 5.1 x264-BluEvo
2024-04-26T05:13:00.206506819Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 Bluray 1080p x265 AAC5.1-GREENOTEA
2024-04-26T05:13:00.207614773Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 Bluray 1080p x265 AAC(5.1) GREENOTEA
2024-04-26T05:13:00.208631282Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 BluRay 1080p x264 DTS-CnSCG
2024-04-26T05:13:00.209650515Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：高清视界 - Flipped 2010 720p BluRay x264 DTS-WiKi
2024-04-26T05:13:00.210733456Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：PT时间 - Flipped 2010 BluRay 1080p 2Audio DTS-HD MA5.1 x265 10bit-BeiTai
2024-04-26T05:13:00.211948504Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：PT时间 - Flipped 2010 BluRay 1080p x265.10bit 2Audio MNHD-FRDS
2024-04-26T05:13:00.212940735Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：PT时间 - Flipped 2010 BluRay 1080p DTS x264 Remux-xander
2024-04-26T05:13:00.213936886Z WARNING: torrent.py - PT时间 - Flipped 2010 1080p Blu-ray AVC DTS-HD MA 5 1-DIY@miracle1934 种子标题类型为 电视剧，不匹配 电影
2024-04-26T05:13:00.215026775Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：阿童木 - 怦然心动 2010 Flipped 2010 1080p BluRay AVC DTS-HD MA 5.1-GKD@Audies
2024-04-26T05:13:00.216222027Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：阿童木 - 怦然心动 2010 Flipped 2010 Blu-Ray 1080p 2Audio DTS-HD MA 5.1 x264-beAst
2024-04-26T05:13:00.217275844Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：阿童木 - 怦然心动 2010 Flipped 2010 1080p BluRay DTS x264-WiKi
2024-04-26T05:13:00.218389547Z INFO:    torrent.py - 怦然心动 通过标题匹配到资源：阿童木 - 怦然心动 2010 Flipped 2010 BluRay 1080p REMUX AVC DTS-HD MA 5.1-LEGi0N
2024-04-26T05:13:00.219024384Z INFO:    search.py - 匹配完成，共匹配到 32 个资源
2024-04-26T05:13:00.219783317Z INFO:    search.py - 开始优先级规则/剧集过滤，当前规则： SPECSUB & 4K & 60FPS & ATMOS & HDR & DOLBY > 4K & ATMOS & HDR > 4K > 1080P  ...
2024-04-26T05:13:00.243967498Z INFO:    filter - 种子 咖啡 - Flipped 2010 BluRay 1080p 2Audio DTS-HD MA5.1 x265 10bit-BeiTai 优先级为 4
2024-04-26T05:13:00.246590285Z INFO:    filter - 种子 Rousi - Flipped 2010 BluRay 1080p x264 DTS 2Audios-CMCT 优先级为 4
2024-04-26T05:13:00.249715781Z INFO:    filter - 种子 Rousi - Flipped 2010 BluRay 1080p x265 10bit AC3 MNHD-FRDS 优先级为 4
2024-04-26T05:13:00.252328856Z INFO:    filter - 种子 Rousi - Flipped 2010 Blu-Ray 1080p 2Audio DTS-HD MA 5.1 x264-beAst 优先级为 4
2024-04-26T05:13:00.254952384Z INFO:    filter - 种子 Rousi - Flipped 2010 BluRay 1080p 2Audio DTS-HD MA5.1 x265 10bit-BeiTai 优先级为 4
2024-04-26T05:13:00.257623138Z INFO:    filter - 种子 CARPT - 怦然心动 2010 Flipped 2010 1080p BluRay AVC DTS-HD MA 5.1-GKD@Audies 优先级为 4
2024-04-26T05:13:00.260073399Z INFO:    filter - 种子 CARPT - Flipped 2010 1080p BluRay x265 10bit DTS-WiKi 优先级为 4
2024-04-26T05:13:00.262357144Z INFO:    filter - 种子 高清视界 - Flipped 2010 1080p BluRay AVC DTS-HD MA 5.1-GKD@Audies 优先级为 4
2024-04-26T05:13:00.266706008Z INFO:    filter - 种子 高清视界 - Flipped 2010 BD 1080p x265 10bit DD5.1 3Audios-FFans@leon 优先级为 4
2024-04-26T05:13:00.268965669Z INFO:    filter - 种子 高清视界 - Flipped 2010 1080p BluRay x264 DTS-WiKi 优先级为 4
2024-04-26T05:13:00.271349324Z INFO:    filter - 种子 高清视界 - Flipped 2010 1080p BluRay x265 10bit DTS-WiKi 优先级为 4
2024-04-26T05:13:00.273947099Z INFO:    filter - 种子 高清视界 - Flipped 2010 BluRay 1080p 2Audio DTS-HD MA 5.1 x265 10bit-BeiTai 优先级为 4
2024-04-26T05:13:00.276642564Z INFO:    filter - 种子 高清视界 - Flipped  2010 1080p AVC DTS-HD MA 优先级为 4
2024-04-26T05:13:00.278965729Z INFO:    filter - 种子 高清视界 - Flipped 2010 BluRay 1080p x265 10bit 2Audio MNHD-FRDS 优先级为 4
2024-04-26T05:13:00.281571319Z INFO:    filter - 种子 高清视界 - Flipped 2010 Blu-Ray 1080p 2Audio DTS-HD MA 5.1 x264-beAst 优先级为 4
2024-04-26T05:13:00.287599751Z INFO:    filter - 种子 高清视界 - Flipped 2010 1080p Blu-ray REMUX AVC DTS-HD MA 5.1-HDArea 优先级为 4
2024-04-26T05:13:00.290077950Z INFO:    filter - 种子 高清视界 - Flipped 2010 1080p Blu-ray AVC DTS-HD MA 5.1-CtrlHD 优先级为 4
2024-04-26T05:13:00.292589905Z INFO:    filter - 种子 高清视界 - Flipped 2010 1080p BluRay DTS-HD MA 5.1 x264-BluEvo 优先级为 4
2024-04-26T05:13:00.294857176Z INFO:    filter - 种子 高清视界 - Flipped 2010 Bluray 1080p x265 AAC5.1-GREENOTEA 优先级为 4
2024-04-26T05:13:00.297335402Z INFO:    filter - 种子 高清视界 - Flipped 2010 Bluray 1080p x265 AAC(5.1) GREENOTEA 优先级为 4
2024-04-26T05:13:00.299841573Z INFO:    filter - 种子 高清视界 - Flipped 2010 BluRay 1080p x264 DTS-CnSCG 优先级为 4
2024-04-26T05:13:00.303724385Z INFO:    filter - 种子 PT时间 - Flipped 2010 BluRay 1080p 2Audio DTS-HD MA5.1 x265 10bit-BeiTai 优先级为 4
2024-04-26T05:13:00.305970496Z INFO:    filter - 种子 PT时间 - Flipped 2010 BluRay 1080p x265.10bit 2Audio MNHD-FRDS 优先级为 4
2024-04-26T05:13:00.308284155Z INFO:    filter - 种子 PT时间 - Flipped 2010 BluRay 1080p DTS x264 Remux-xander 优先级为 4
2024-04-26T05:13:00.310705386Z INFO:    filter - 种子 阿童木 - 怦然心动 2010 Flipped 2010 1080p BluRay AVC DTS-HD MA 5.1-GKD@Audies 优先级为 4
2024-04-26T05:13:00.313024146Z INFO:    filter - 种子 阿童木 - 怦然心动 2010 Flipped 2010 Blu-Ray 1080p 2Audio DTS-HD MA 5.1 x264-beAst 优先级为 4
2024-04-26T05:13:00.315466400Z INFO:    filter - 种子 阿童木 - 怦然心动 2010 Flipped 2010 1080p BluRay DTS x264-WiKi 优先级为 4
2024-04-26T05:13:00.317949018Z INFO:    filter - 种子 阿童木 - 怦然心动 2010 Flipped 2010 BluRay 1080p REMUX AVC DTS-HD MA 5.1-LEGi0N 优先级为 4
2024-04-26T05:13:00.318846991Z INFO:    search.py - 开始过滤规则过滤，当前规则：{'include': None, 'exclude': None, 'quality': None, 'resolution': None, 'effect': None, 'tv_size': None, 'movie_size': None, 'min_seeders': None} ...
2024-04-26T05:13:00.325412539Z INFO:    search.py - 过滤完成，剩余 28 个资源
2024-04-26T05:13:07.248458471Z INFO:    chain - 发送消息：channel=None，title=怦然心动 (2010)  开始下载, text=用户：admin
2024-04-26T05:13:07.248481410Z 站点：PT时间
2024-04-26T05:13:07.248484827Z 质量： BluRay 1080p
2024-04-26T05:13:07.248487849Z 大小：4.55G
2024-04-26T05:13:07.248490699Z 种子：Flipped 2010 BluRay 1080p x265.10bit 2Audio MNHD-FRDS
2024-04-26T05:13:07.248493785Z 发布时间：2021-03-04 17:06:17
2024-04-26T05:13:07.248496852Z 做种数：668
2024-04-26T05:13:07.248499933Z 促销：50%
2024-04-26T05:13:07.248503310Z 描述：50%免费，userid=None
2024-04-26T05:13:07.250574460Z INFO:    command.py - 处理事件：notice.message - []
2024-04-26T05:13:07.271860884Z INFO:    command.py - 处理事件：download.added - []
2024-04-26T05:13:07.272039002Z INFO:    subscribe.py - 怦然心动 (2010) 完成订阅
2024-04-26T05:13:07.467115467Z ERROR:   scheduler.py - 定时任务 subscribe_search 执行失败：(sqlite3.IntegrityError) UNIQUE constraint failed: subscribehistory.id
2024-04-26T05:13:07.467134795Z [SQL: INSERT INTO subscribehistory (id, name, year, type, keyword, tmdbid, imdbid, tvdbid, doubanid, bangumiid, season, poster, backdrop, vote, description, filter, include, exclude, quality, resolution, effect, total_episode, start_episode, date, username, sites, best_version, save_path, search_imdbid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
2024-04-26T05:13:07.467150467Z [parameters: (8, '怦然心动', '2010', '电影', None, 43949, 'tt0817177', None, None, None, 0, 'https://image.tmdb.org/t/p/w500/4Nu5blbEXzNm58UKVVZ9qhe3O3y.jpg', 'https://image.tmdb.org/t/p/w500/xBSwwkAYl9h8QVG2OxNpSaSgJwr.jpg', 8.0, '布莱斯全家搬到小镇，邻家女孩朱丽前来帮忙。她对他一见钟情，心愿是获得他的吻。两人是同班同学，她一直想方设法接近他，但是他避之不及。她喜欢爬在高高的梧桐树上看风景。但因为施工，树被要被砍掉，她誓死捍卫，希望他并肩作战，但是他退缩了。她的事迹上了报纸，外公对她颇有好感，令他十分困惑。她凭借鸡下蛋的项目 ... (35 characters truncated) ... 听家人怀疑她家鸡蛋不卫生，便偷偷把鸡蛋丢掉。她得知真相，很伤心，两人关系跌入冰点。她跟家人诉说，引发争吵。原来父亲一直攒钱照顾傻弟弟，所以生活拮据。她理解了父母，自己动手，还得到了他外公的鼎力相助。他向她道歉，但是并未解决问题。他开始关注她。鸡蛋风波未平，家庭晚宴与午餐男孩评选又把两人扯在了一起。', None, None, None, None, None, None, None, None, '2024-04-26 13:13:07', 'admin', None, 0, None, 0)]
2024-04-26T05:13:07.467157099Z (Background on this error at: https://sqlalche.me/e/20/gkpj) - Traceback (most recent call last):
2024-04-26T05:13:07.467159522Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
2024-04-26T05:13:07.467162409Z     self.dialect.do_execute(
2024-04-26T05:13:07.467164522Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
2024-04-26T05:13:07.467166751Z     cursor.execute(statement, parameters)
2024-04-26T05:13:07.467168906Z sqlite3.IntegrityError: UNIQUE constraint failed: subscribehistory.id
2024-04-26T05:13:07.467171041Z 
2024-04-26T05:13:07.467173079Z The above exception was the direct cause of the following exception:
2024-04-26T05:13:07.467175190Z 
2024-04-26T05:13:07.467177273Z Traceback (most recent call last):
2024-04-26T05:13:07.467179374Z   File "/app/app/scheduler.py", line 286, in start
2024-04-26T05:13:07.467181517Z     job["func"](*args, **kwargs)
2024-04-26T05:13:07.467183674Z   File "/app/app/chain/subscribe.py", line 353, in search
2024-04-26T05:13:07.467185831Z     self.finish_subscribe_or_not(subscribe=subscribe, meta=meta, mediainfo=mediainfo,
2024-04-26T05:13:07.467187954Z   File "/app/app/chain/subscribe.py", line 415, in finish_subscribe_or_not
2024-04-26T05:13:07.467190099Z     self.subscribehistoryoper.add(**subscribe.to_dict())
2024-04-26T05:13:07.467192182Z   File "/app/app/db/subscribehistory_oper.py", line 21, in add
2024-04-26T05:13:07.467194350Z     subscribe.create(self._db)
2024-04-26T05:13:07.467196413Z   File "/app/app/db/__init__.py", line 99, in wrapper
2024-04-26T05:13:07.467202135Z     raise err
2024-04-26T05:13:07.467204480Z   File "/app/app/db/__init__.py", line 95, in wrapper
2024-04-26T05:13:07.467206672Z     db.commit()
2024-04-26T05:13:07.467208768Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
2024-04-26T05:13:07.467210971Z     trans.commit(_to_root=True)
2024-04-26T05:13:07.467213034Z   File "<string>", line 2, in commit
2024-04-26T05:13:07.467215254Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
2024-04-26T05:13:07.467217441Z     ret_value = fn(self, *arg, **kw)
2024-04-26T05:13:07.467219519Z                 ^^^^^^^^^^^^^^^^^^^^
2024-04-26T05:13:07.467221582Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
2024-04-26T05:13:07.467223778Z     self._prepare_impl()
2024-04-26T05:13:07.467225808Z   File "<string>", line 2, in _prepare_impl
2024-04-26T05:13:07.467227910Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
2024-04-26T05:13:07.467230359Z     ret_value = fn(self, *arg, **kw)
2024-04-26T05:13:07.467233791Z                 ^^^^^^^^^^^^^^^^^^^^
2024-04-26T05:13:07.467236977Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
2024-04-26T05:13:07.467240335Z     self.session.flush()
2024-04-26T05:13:07.467243837Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
2024-04-26T05:13:07.467247299Z     self._flush(objects)
2024-04-26T05:13:07.467250567Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
2024-04-26T05:13:07.467254191Z     with util.safe_reraise():
2024-04-26T05:13:07.467257948Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
2024-04-26T05:13:07.467261615Z     raise exc_value.with_traceback(exc_tb)
2024-04-26T05:13:07.467264638Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
2024-04-26T05:13:07.467267891Z     flush_context.execute()
2024-04-26T05:13:07.467270914Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
2024-04-26T05:13:07.467274176Z     rec.execute(self)
2024-04-26T05:13:07.467277326Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
2024-04-26T05:13:07.467280964Z     util.preloaded.orm_persistence.save_obj(
2024-04-26T05:13:07.467284526Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
2024-04-26T05:13:07.467288252Z     _emit_insert_statements(
2024-04-26T05:13:07.467291870Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
2024-04-26T05:13:07.467297911Z     result = connection.execute(
2024-04-26T05:13:07.467302591Z              ^^^^^^^^^^^^^^^^^^^
2024-04-26T05:13:07.467304798Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
2024-04-26T05:13:07.467307030Z     return meth(
2024-04-26T05:13:07.467309189Z            ^^^^^
2024-04-26T05:13:07.467311553Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
2024-04-26T05:13:07.467317961Z     return connection._execute_clauseelement(
2024-04-26T05:13:07.467321467Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-26T05:13:07.467324683Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
2024-04-26T05:13:07.467328506Z     ret = self._execute_context(
2024-04-26T05:13:07.467332028Z           ^^^^^^^^^^^^^^^^^^^^^^
2024-04-26T05:13:07.467335570Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
2024-04-26T05:13:07.467338230Z     return self._exec_single_context(
2024-04-26T05:13:07.467340340Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-26T05:13:07.467342476Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
2024-04-26T05:13:07.467344704Z     self._handle_dbapi_exception(
2024-04-26T05:13:07.467346766Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
2024-04-26T05:13:07.467348963Z     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2024-04-26T05:13:07.467351129Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
2024-04-26T05:13:07.467353330Z     self.dialect.do_execute(
2024-04-26T05:13:07.467355416Z   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
2024-04-26T05:13:07.467357876Z     cursor.execute(statement, parameters)
2024-04-26T05:13:07.467360045Z sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: subscribehistory.id
2024-04-26T05:13:07.467362279Z [SQL: INSERT INTO subscribehistory (id, name, year, type, keyword, tmdbid, imdbid, tvdbid, doubanid, bangumiid, season, poster, backdrop, vote, description, filter, include, exclude, quality, resolution, effect, total_episode, start_episode, date, username, sites, best_version, save_path, search_imdbid) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
2024-04-26T05:13:07.467366379Z [parameters: (8, '怦然心动', '2010', '电影', None, 43949, 'tt0817177', None, None, None, 0, 'https://image.tmdb.org/t/p/w500/4Nu5blbEXzNm58UKVVZ9qhe3O3y.jpg', 'https://image.tmdb.org/t/p/w500/xBSwwkAYl9h8QVG2OxNpSaSgJwr.jpg', 8.0, '布莱斯全家搬到小镇，邻家女孩朱丽前来帮忙。她对他一见钟情，心愿是获得他的吻。两人是同班同学，她一直想方设法接近他，但是他避之不及。她喜欢爬在高高的梧桐树上看风景。但因为施工，树被要被砍掉，她誓死捍卫，希望他并肩作战，但是他退缩了。她的事迹上了报纸，外公对她颇有好感，令他十分困惑。她凭借鸡下蛋的项目 ... (35 characters truncated) ... 听家人怀疑她家鸡蛋不卫生，便偷偷把鸡蛋丢掉。她得知真相，很伤心，两人关系跌入冰点。她跟家人诉说，引发争吵。原来父亲一直攒钱照顾傻弟弟，所以生活拮据。她理解了父母，自己动手，还得到了他外公的鼎力相助。他向她道歉，但是并未解决问题。他开始关注她。鸡蛋风波未平，家庭晚宴与午餐男孩评选又把两人扯在了一起。', None, None, None, None, None, None, None, None, '2024-04-26 13:13:07', 'admin', None, 0, None, 0)]
2024-04-26T05:13:07.467377063Z (Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-04-26T05:13:07.467380346Z
```

**Comment by jxxghp** [comment]
v1.8.4已解决

**Comment by latel** [comment]
🥂
