### ISSUE TITLE
[错误报告]: 启动报错导致无法启动

### ISSUE THREAD

**Issue by gravitation-ch** [jxxghp/MoviePilot#1971]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

黑裙关机维护，开机后MP启动报错，无法启动。

### 发生问题时系统日志和配置文件

```bash
未发现新版本，跳过更新步骤...

最新版本号：v1.8.4

当前版本号：v1.8.4

Release 更新模式

不使用代理更新程序

Downloading Chromium 114.0.5735.35 (playwright build v1064) from https://playwright.azureedge.net/builds/chromium/1064/chromium-linux.zip

usermod: no changes

Traceback (most recent call last):

  File "/app/app/main.py", line 21, in <module>

    from app.core.plugin import PluginManager

  File "/app/app/core/plugin.py", line 12, in <module>

    from app.helper.sites import SitesHelper

ModuleNotFoundError: No module named 'app.helper.sites'

```

**Comment by gravitation-ch** [comment]
重新拉镜像，重建好了
