### ISSUE TITLE
[错误报告]: 更新版本，重启失败

### ISSUE THREAD

**Issue by li11701087** [jxxghp/MoviePilot#1980]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.5

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

更新新版本后反复重启失败，之前版本也是这样，重新安装容器能解决，是什么原因造成的啊？

### 发生问题时系统日志和配置文件

```bash
2024/4/29 22:20:29  usermod: no changes
2024/4/29 22:20:29  未发现新版本，跳过更新步骤...
2024/4/29 22:20:29  最新版本号：v1.8.5
2024/4/29 22:20:27  当前版本号：v1.8.5
2024/4/29 22:20:27  Release 更新模式
2024/4/29 22:20:27  不使用代理更新程序
2024/4/29 22:20:24  ModuleNotFoundError: No module named 'app.helper.sites'
2024/4/29 22:20:24      from app.helper.sites import SitesHelper
2024/4/29 22:20:24    File "/app/app/core/plugin.py", line 12, in <module>
2024/4/29 22:20:24      from app.core.plugin import PluginManager
2024/4/29 22:20:24    File "/app/app/main.py", line 21, in <module>
2024/4/29 22:20:24  Traceback (most recent call last):
2024/4/29 22:20:10  usermod: no changes
2024/4/29 22:20:10  最新版本号获取失败，继续启动...
2024/4/29 22:20:09  当前版本号：v1.8.5
2024/4/29 22:20:09  Release 更新模式
2024/4/29 22:20:09  不使用代理更新程序
2024/4/29 22:20:06  ModuleNotFoundError: No module named 'app.helper.sites'
2024/4/29 22:20:06      from app.helper.sites import SitesHelper
2024/4/29 22:20:06    File "/app/app/core/plugin.py", line 12, in <module>
2024/4/29 22:20:06      from app.core.plugin import PluginManager
2024/4/29 22:20:06    File "/app/app/main.py", line 21, in <module>
2024/4/29 22:20:06  Traceback (most recent call last):
```

**Comment by houxiaoyi0722** [comment]
重新安装容器能解决么？我1.9.4 版本更新后出现这个问题，更新镜像版本到1.9.10重新创建容器启动后还是报错

**Comment by xuxiaohu6** [comment]
我的今天也是这个问题，大概可能好像是版本没有更新完容器就被关闭了，我是重置（前提是已经做好好像叫conige和socker这两个是映射）或是在portainer中重建，然后重启就可以了，不过重启可能还是会有版本更新，如果你没有在配置文件里面关闭的话，我更新的时间很长，在日志中看的是大概50分钟才更新完。

**Comment by li11701087** [comment]
我后来重新拉取镜像后重装就可以了，后来就再没有碰到这个问题。
