### ISSUE TITLE
[错误报告]: 配置代理地址后启动报错 无法连接代理

### ISSUE THREAD

**Issue by kiliter** [jxxghp/MoviePilot#2070]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.7

### 运行环境

Windows

### 问题类型

其他问题

### 问题描述

1. 使用插件[配置中心]配置代理地址 网络可以连通
2. 重启群晖套件mp 启动报错 网络无法连通 tmdb 电报 等
3. 打开插件 配置中心后 点击确定并启用 网络恢复

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-05-14 15:18:40,638 - chain - 运行模块 register_commands 出错：TelegramModule - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /:/deleteMyCommands (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fbfb003a9d0>: Failed to resolve ''socks5' ([Errno -2] Name or service not known)")))
Traceback (most recent call last):
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/moviepilot/app/helper/doh.py", line 50, in _patched_getaddrinfo
    return _orig_getaddrinfo(host, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/Python3.11/target/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/urllib3/connectionpool.py", line 777, in urlopen
    self._prepare_proxy(conn)
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1046, in _prepare_proxy
    conn.connect()
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7fbfb003a9d0>: Failed to resolve ''socks5' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fbfb003a9d0>: Failed to resolve ''socks5' ([Errno -2] Name or service not known)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7180737904:AAEPFIuwF8tr3adHYZMPwrHfORAaVx94s2o/deleteMyCommands (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fbfb003a9d0>: Failed to resolve ''socks5' ([Errno -2] Name or service not known)")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/packages/MoviePilot/target/moviepilot/app/chain/__init__.py", line 101, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/moviepilot/app/modules/telegram/__init__.py", line 137, in register_commands
    self.telegram.register_commands(commands)
  File "/var/packages/MoviePilot/target/moviepilot/app/modules/telegram/telegram.py", line 228, in register_commands
    self._bot.delete_my_commands()
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/telebot/__init__.py", line 3674, in delete_my_commands
    return apihelper.delete_my_commands(self.token, scope, language_code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/telebot/apihelper.py", line 1267, in delete_my_commands
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/telebot/apihelper.py", line 156, in _make_request
    result = _get_req_session().request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/lib/python3.11/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot7180737904:AAEPFIuwF8tr3adHYZMPwrHfORAaVx94s2o/deleteMyCommands (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fbfb003a9d0>: Failed to resolve ''socks5' ([Errno -2] Name or service not known)")))

【ERROR】2024-05-14 15:18:43,560 - chain - 运行模块 tmdb_trending 出错：TheMovieDbModule - 无法连接TheMovieDb，请检查网络连接！
Traceback (most recent call last):
  File "/var/packages/MoviePilot/target/moviepilot/app/chain/__init__.py", line 101, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/moviepilot/app/modules/themoviedb/__init__.py", line 353, in tmdb_trending
    trending = self.tmdb.trending.all_week(page=page)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/moviepilot/app/modules/themoviedb/tmdbv3api/objs/trending.py", line 28, in all_week
    return self._trending(media_type="all", time_window="week", page=page)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/moviepilot/app/modules/themoviedb/tmdbv3api/objs/trending.py", line 8, in _trending
    return self._request_obj(
           ^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/moviepilot/app/modules/themoviedb/tmdbv3api/tmdb.py", line 174, in _request_obj
    req = self.cached_request(method, url, data, json)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/moviepilot/app/modules/themoviedb/tmdbv3api/tmdb.py", line 146, in cached_request
    return self.request(method, url, data, json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/MoviePilot/target/moviepilot/app/modules/themoviedb/tmdbv3api/tmdb.py", line 154, in request
    raise TMDbException("无法连接TheMovieDb，请检查网络连接！")
app.modules.themoviedb.tmdbv3api.exceptions.TMDbException: 无法连接TheMovieDb，请检查网络连接！
```

**Comment by kiliter** [comment]
我可以确认 我的代理地址是正确的  并且可用

**Comment by jxxghp** [comment]
错误提示中提到Failed to resolve ''socks5'，这表明在使用代理连接时，代理的地址解析失败。即代理服务器的地址或配置有误。
没有别人出现这个情况，自己研究下。
