### ISSUE TITLE
subscribe_refresh 执行失败

### ISSUE THREAD

**Issue by 705058548** [jxxghp/MoviePilot#2103]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

昨天升级了1.8.9版本，先是系统设置内容丢失（只是系统的这个栏目丢，其他设置栏目设置内容均在），然后我就重新配置上了，然后就报错了，报，定时任务 subscribe_refresh 执行失败。请大佬帮看看怎么回事，重新构建了，也不行，配置文件均映射到了 本地
 - '/volume1/docker/MoviePilot/config:/config'
 - '/volume1/docker/MoviePilot/moviepilot:/moviepilot/'
 - '/var/run/docker.sock:/var/run/docker.sock:ro'

### 发生问题时系统日志和配置文件

```bash
(Background on this error at: https://sqlalche.me/e/20/4xp6)
[parameters: (676705, '电影', 1, 0)]
 LIMIT ? OFFSET ?]
WHERE mediaserveritem.tmdbid = ? AND mediaserveritem.item_type = ?
FROM mediaserveritem 
[SQL: SELECT mediaserveritem.id AS mediaserveritem_id, mediaserveritem.server AS mediaserveritem_server, mediaserveritem.library AS mediaserveritem_library, mediaserveritem.item_id AS mediaserveritem_item_id, mediaserveritem.item_type AS mediaserveritem_item_type, mediaserveritem.title AS mediaserveritem_title, mediaserveritem.original_title AS mediaserveritem_original_title, mediaserveritem.year AS mediaserveritem_year, mediaserveritem.tmdbid AS mediaserveritem_tmdbid, mediaserveritem.imdbid AS mediaserveritem_imdbid, mediaserveritem.tvdbid AS mediaserveritem_tvdbid, mediaserveritem.path AS mediaserveritem_path, mediaserveritem.seasoninfo AS mediaserveritem_seasoninfo, mediaserveritem.note AS mediaserveritem_note, mediaserveritem.lst_mod_date AS mediaserveritem_lst_mod_date 
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self._exec_single_context(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
          ^^^^^^^^^^^^^^^^^^^^^^
    ret = self._execute_context(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
           ^^^^^
    return meth(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
             ^^^^^^^^^^^^^
    result = conn.execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2236, in _execute_internal
           ^^^^^^^^^^^^^^^^^^^^^^^
    return self._execute_internal(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
                                                  ^^^^^^^^^^^^^^^^^^^^^
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
           ^^^^^^^^^^^^^^^^^^^^^
    return self.limit(1)._iter().first()  # type: ignore
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2728, in first
                                        ^^^^^^^
    MediaServerItem.item_type == mtype).first()
  File "/app/app/db/models/mediaserver.py", line 61, in exist_by_tmdbid
             ^^^^^^^^^^^^^^^^^^^^^
    result = func(*args, **kwargs)
  File "/app/app/db/__init__.py", line 129, in wrapper
    raise err
  File "/app/app/db/__init__.py", line 131, in wrapper
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    item = MediaServerItem.exist_by_tmdbid(self._db, tmdbid=kwargs.get("tmdbid"),
  File "/app/app/db/mediaserver_oper.py", line 40, in exists
           ^^^^^^^^^^^^^^^^^^^^^
    item = self.exists(**kwargs)
  File "/app/app/db/mediaserver_oper.py", line 64, in get_item_id
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    itemid = self.mediaserver.get_item_id(mtype=mediainfo.type.value,
  File "/app/app/chain/download.py", line 725, in get_no_exists_info
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    exist_flag, no_exists = self.downloadchain.get_no_exists_info(
  File "/app/app/chain/subscribe.py", line 540, in match
    self.match(
  File "/app/app/chain/subscribe.py", line 453, in refresh
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 325, in start
Traceback (most recent call last):

The above exception was the direct cause of the following exception:

sqlite3.DatabaseError: database disk image is malformed
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
(Background on this error at: https://sqlalche.me/e/20/4xp6) - Traceback (most recent call last):
[parameters: (676705, '电影', 1, 0)]
 LIMIT ? OFFSET ?]
WHERE mediaserveritem.tmdbid = ? AND mediaserveritem.item_type = ?
FROM mediaserveritem 
[SQL: SELECT mediaserveritem.id AS mediaserveritem_id, mediaserveritem.server AS mediaserveritem_server, mediaserveritem.library AS mediaserveritem_library, mediaserveritem.item_id AS mediaserveritem_item_id, mediaserveritem.item_type AS mediaserveritem_item_type, mediaserveritem.title AS mediaserveritem_title, mediaserveritem.original_title AS mediaserveritem_original_title, mediaserveritem.year AS mediaserveritem_year, mediaserveritem.tmdbid AS mediaserveritem_tmdbid, mediaserveritem.imdbid AS mediaserveritem_imdbid, mediaserveritem.tvdbid AS mediaserveritem_tvdbid, mediaserveritem.path AS mediaserveritem_path, mediaserveritem.seasoninfo AS mediaserveritem_seasoninfo, mediaserveritem.note AS mediaserveritem_note, mediaserveritem.lst_mod_date AS mediaserveritem_lst_mod_date 
【ERROR】2024-05-18 08:38:57,024 - scheduler.py - 定时任务 subscribe_refresh 执行失败：(sqlite3.DatabaseError) database disk image is malformed
```

**Comment by jxxghp** [comment]
这个报错表明您的 SQLite 数据库文件已经损坏。这通常是由以下几种原因造成的：

突然的应用程序终止：如果在数据库正在写入数据时，应用程序突然崩溃或关闭，可能会导致数据库文件损坏。
硬件故障：存储数据库的硬盘或其他存储介质出现故障也可能导致数据库损坏。
文件系统问题：文件系统的问题，例如坏扇区或不良的磁盘操作，可能导致数据库文件被破坏。
不正确的数据库操作：不正确的数据库操作，如频繁的强制关闭或不适当的事务处理，也可能导致数据库文件的损坏。
错误日志分析
从错误日志中，我们可以看到以下关键信息：

报错信息：sqlite3.DatabaseError: database disk image is malformed
这表明 SQLite 数据库文件结构不正确，数据库文件已经损坏。

**Comment by 705058548** [comment]
> 这个报错表明您的 SQLite 数据库文件已经损坏。这通常是由以下几种原因造成的：
> 
> 突然的应用程序终止：如果在数据库正在写入数据时，应用程序突然崩溃或关闭，可能会导致数据库文件损坏。 硬件故障：存储数据库的硬盘或其他存储介质出现故障也可能导致数据库损坏。 文件系统问题：文件系统的问题，例如坏扇区或不良的磁盘操作，可能导致数据库文件被破坏。 不正确的数据库操作：不正确的数据库操作，如频繁的强制关闭或不适当的事务处理，也可能导致数据库文件的损坏。 错误日志分析 从错误日志中，我们可以看到以下关键信息：
> 
> 报错信息：sqlite3.DatabaseError: database disk image is malformed 这表明 SQLite 数据库文件结构不正确，数据库文件已经损坏。

那，是不是 只能重新来过，删了所有，重新安装了？之前的就都没了？？？

**Comment by jxxghp** [comment]
没人出现过你这种情况，数据库文件损坏，相关的数据都丢失了，如果你没有备份的话。
损坏的原因不清楚，以上是ChatGPT的回答，从应用程序看是不太可能出现损坏数据库的（也没听说别人出现过），可能是你的环境出现了什么问题。

**Comment by 705058548** [comment]
> 没人出现过你这种情况，数据库文件损坏，相关的数据都丢失了，如果你没有备份的话。 损坏的原因不清楚，以上是ChatGPT的回答，从应用程序看是不太可能出现损坏数据库的（也没听说别人出现过），可能是你的环境出现了什么问题。

好吧，我重新搞一下吧，MoviePilot里自动备份插件备份出来的数据库文件和配置文件，复制进去，也是不行
