### ISSUE TITLE
[错误报告]: plexapi报错

### ISSUE THREAD

**Issue by yyned2501** [jxxghp/MoviePilot#2104]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

提前订阅的剧集，当plex搜索不到媒体时，media_exists模块，plexapi会报错，10分钟报错一次，一天报错上百次。

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-05-18 05:52:10,832 - subscribe.py - 订阅 大奉打更人 S01 缺失集：[]

plexapi.exceptions.BadRequest: (500) internal_server_error; http://192.168.31.10:32400/library/all?title=%E5%A4%A7%E5%A5%89%E6%89%93%E6%9B%B4%E4%BA%BA&type=2&year=None <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
    raise BadRequest(message)
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 769, in query
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    data = self._server.query(ekey, headers=headers, params=params)
  File "/usr/local/lib/python3.11/site-packages/plexapi/base.py", line 281, in fetchItems
           ^^^^^^^^^^^^^^^^^^^^
    return self.fetchItems(key)
  File "/usr/local/lib/python3.11/site-packages/plexapi/library.py", line 177, in search
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    videos = self._plex.library.search(title=title,
  File "/app/app/modules/plex/plex.py", line 240, in get_tv_episodes
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    item_id, tvs = self.plex.get_tv_episodes(title=mediainfo.title,
  File "/app/app/modules/plex/__init__.py", line 87, in media_exists
             ^^^^^^^^^^^^^^^^^^^^^
    result = func(*args, **kwargs)
  File "/app/app/chain/__init__.py", line 101, in run_module
Traceback (most recent call last):
【ERROR】2024-05-18 05:52:10,831 - chain - 运行模块 media_exists 出错：PlexModule - (500) internal_server_error; http://192.168.31.10:32400/library/all?title=%E5%A4%A7%E5%A5%89%E6%89%93%E6%9B%B4%E4%BA%BA&type=2&year=None <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>
【INFO】2024-05-18 05:52:10,820 - themoviedb - 大奉打更人 TMDB识别结果：电视剧 大奉打更人 233912
```

**Comment by jxxghp** [comment]
看起来是Plex内部报500，我没有Plex环境，不确定是否共性问题。
