### ISSUE TITLE
日志报错No module named 'app.chain.downloaderh

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#2110]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

最新版，应该是添加下载时报错，好像没有实际影响

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-05-18 17:39:09,454 - chain - 发送消息：channel=None，title=我的英雄学院 (2016) S07 E03 开始下载, text=用户：RSS订阅
站点：观众
质量： WEB-DL 1080p
大小：1.35G
种子：Boku no Hero Academia S07E03 2024 1080p CR WEB-DL x264 AAC-AnimeS@ADWeb[2024年4月新番 我的英雄学院 第7季 / 僕のヒーローアカデミア 第七期 第03集 *内封简繁英多国软字幕*]
发布时间：2024-05-18 17:32:15，userid=None
【INFO】2024-05-18 17:39:09,458 - command.py - 处理事件：notice.message - []
【INFO】2024-05-18 17:39:10,201 - command.py - 处理事件：download.added - [<function DownloaderHelper.listen_download_added_event at 0x7f5836325b20>, <function DownloadSiteTag.DownloadAdded at 0x7f58363d6e80>, <function SubscribeGroup.download_notice at 0x7f5836136160>]
【ERROR】2024-05-18 17:39:10,203 - command.py - 事件处理出错：No module named 'app.chain.downloaderh' - Traceback (most recent call last):
  File "/app/app/command.py", line 204, in __run
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app.chain.downloaderh'
```

**Comment by jxxghp** [comment]
使用文件管理，看下/app/app/plugins目录下是不是有个downloadrh的文件夹，有的话删掉，估计是插件之前遗留的错误文件。

**Comment by dlovew** [comment]
> 使用文件管理，看下/app/app/plugins目录下是不是有个downloadrh的文件夹，有的话删掉，估计是插件之前遗留的错误文件。

按照大佬得操作以后暂时没问题，我先close了
