### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by dcshow** [jxxghp/MoviePilot#2120]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.8-V.1.8.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我使用的是mac MINI  M2 版本的docker，外挂12T HDD作为下载盘。在文件管理中，打不开目录，也无法整理文件。

### 发生问题时系统日志和配置文件

```bash
2024-05-20 00:04:54 INFO:     192.168.65.1:0 - "GET /api/v1/system/env HTTP/1.1" 200 OK
2024-05-20 00:04:54 INFO:     192.168.65.1:0 - "GET /api/v1/filebrowser/list?path=%2FVolumes%2F12t%2F&sort=name HTTP/1.1" 500 Internal Server Error
2024-05-20 00:04:54 ERROR:    Exception in ASGI application
2024-05-20 00:04:54 Traceback (most recent call last):
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024-05-20 00:04:54     result = await app(  # type: ignore[func-returns-value]
2024-05-20 00:04:54              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-05-20 00:04:54     return await self.app(scope, receive, send)
2024-05-20 00:04:54            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2024-05-20 00:04:54     await super().__call__(scope, receive, send)
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2024-05-20 00:04:54     await self.middleware_stack(scope, receive, send)
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-05-20 00:04:54     raise exc
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-05-20 00:04:54     await self.app(scope, receive, _send)
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-05-20 00:04:54     await self.app(scope, receive, send)
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-05-20 00:04:54     raise exc
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-05-20 00:04:54     await self.app(scope, receive, sender)
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024-05-20 00:04:54     raise e
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024-05-20 00:04:54     await self.app(scope, receive, send)
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2024-05-20 00:04:54     await route.handle(scope, receive, send)
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2024-05-20 00:04:54     await self.app(scope, receive, send)
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2024-05-20 00:04:54     response = await func(request)
2024-05-20 00:04:54                ^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
2024-05-20 00:04:54     raw_response = await run_endpoint_function(
2024-05-20 00:04:54                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
2024-05-20 00:04:54     return await run_in_threadpool(dependant.call, **values)
2024-05-20 00:04:54            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2024-05-20 00:04:54     return await anyio.to_thread.run_sync(func, *args)
2024-05-20 00:04:54            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-05-20 00:04:54     return await get_async_backend().run_sync_in_worker_thread(
2024-05-20 00:04:54            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
2024-05-20 00:04:54     return await future
2024-05-20 00:04:54            ^^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
2024-05-20 00:04:54     result = context.run(func, *args)
2024-05-20 00:04:54              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/app/app/api/endpoints/filebrowser.py", line 69, in list_path
2024-05-20 00:04:54     for item in SystemUtils.list_sub_directory(path_obj):
2024-05-20 00:04:54                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/app/app/utils/system.py", line 289, in list_sub_directory
2024-05-20 00:04:54     if path.is_dir():
2024-05-20 00:04:54        ^^^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/pathlib.py", line 1250, in is_dir
2024-05-20 00:04:54     return S_ISDIR(self.stat().st_mode)
2024-05-20 00:04:54                    ^^^^^^^^^^^
2024-05-20 00:04:54   File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
2024-05-20 00:04:54     return os.stat(self, follow_symlinks=follow_symlinks)
2024-05-20 00:04:54            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-20 00:04:54 PermissionError: [Errno 1] Operation not permitted: '/Volumes/12t/.TemporaryItems'
```

**Comment by jxxghp** [comment]
Operation not permitted

**Comment by dcshow** [comment]
是的我看到了，但是我不知道这个问题是系统问题还是容器问题。nastools是可以访问整理的，求帮组
