### ISSUE TITLE
[错误报告]: 升级后目录监控插件报错

### ISSUE THREAD

**Issue by Enderiose** [jxxghp/MoviePilot#2191]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.2-beta

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

NAS重启自动升级了1.9.2-beta

详细错误信息看mp日志和docker日志……谢谢大佬

### 发生问题时系统日志和配置文件

```bash
ValueError: Error validating expression '0': the first value (0) is lower than the minimum value (1)
  File "<string>", line 3, in raise_from
    six.raise_from(exc, None)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/fields.py", line 70, in compile_expression
    self.compile_expression(expr)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/fields.py", line 58, in compile_expressions
    self.compile_expressions(exprs)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/fields.py", line 33, in __init__
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    field = field_class(field_name, exprs, is_default)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/__init__.py", line 83, in __init__
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return cls(minute=values[0], hour=values[1], day=values[2], month=values[3],
  File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/__init__.py", line 103, in from_crontab
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    "trigger": CronTrigger.from_crontab(self._cron),
  File "/app/app/plugins/dirmonitor/__init__.py", line 655, in get_service
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return getattr(plugin, method)(*args, **kwargs)
  File "/app/app/core/plugin.py", line 509, in run_plugin_method
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    plugin_services = PluginManager().run_plugin_method(pid, "get_service") or []
  File "/app/app/scheduler.py", line 391, in update_plugin_job
【ERROR】2024-05-26 22:34:40,437 - scheduler.py - 运行插件 DirMonitor 服务失败：Error validating expression '0': the first value (0) is lower than the minimum value (1) - Traceback (most recent call last):



下面是docker日志
<html>
<body>
<!--StartFragment-->
2024/05/26 22:34:40 | stdout | ValueError: Error validating expression '0': the first value (0) is lower than the minimum value (1)
-- | -- | --
2024/05/26 22:34:40 | stdout | File "<string>", line 3, in raise_from
2024/05/26 22:34:40 | stdout | six.raise_from(exc, None)
2024/05/26 22:34:40 | stdout | File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/fields.py", line 70, in compile_expression
2024/05/26 22:34:40 | stdout | self.compile_expression(expr)
2024/05/26 22:34:40 | stdout | File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/fields.py", line 58, in compile_expressions
2024/05/26 22:34:40 | stdout | self.compile_expressions(exprs)
2024/05/26 22:34:40 | stdout | File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/fields.py", line 33, in __init__
2024/05/26 22:34:40 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/05/26 22:34:40 | stdout | field = field_class(field_name, exprs, is_default)
2024/05/26 22:34:40 | stdout | File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/__init__.py", line 83, in __init__
2024/05/26 22:34:40 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/05/26 22:34:40 | stdout | return cls(minute=values[0], hour=values[1], day=values[2], month=values[3],
2024/05/26 22:34:40 | stdout | File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/__init__.py", line 103, in from_crontab
2024/05/26 22:34:40 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/05/26 22:34:40 | stdout | "trigger": CronTrigger.from_crontab(self._cron),
2024/05/26 22:34:40 | stdout | File "/app/app/plugins/dirmonitor/__init__.py", line 655, in get_service
2024/05/26 22:34:40 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/05/26 22:34:40 | stdout | return getattr(plugin, method)(*args, **kwargs)
2024/05/26 22:34:40 | stdout | File "/app/app/core/plugin.py", line 509, in run_plugin_method
2024/05/26 22:34:40 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/05/26 22:34:40 | stdout | plugin_services = PluginManager().run_plugin_method(pid, "get_service") or []
2024/05/26 22:34:40 | stdout | File "/app/app/scheduler.py", line 391, in update_plugin_job
2024/05/26 22:34:40 | stdout | [31mERROR:[0m   scheduler.py - 运行插件 DirMonitor 服务失败：Error validating expression '0': the first value (0) is lower than the minimum value (1) - Traceback (most recent call last):
2024/05/26 22:34:40 | stdout | DirMonitor.send_msg (trigger: interval[0:00:15], pending)
2024/05/26 22:34:40 | stdout | Pending jobs:

<!--EndFragment-->
</body>
</html>
```

**Comment by jxxghp** [comment]
你周期表达式写错了，跟升级没关系。
