### ISSUE TITLE
我遇到的问题：订阅刷新报错，正则匹配出现异常

### ISSUE THREAD

**Issue by envyafish** [jxxghp/MoviePilot#2198]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.2-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅《恋爱兄妹》报错，订阅规则如下
![image](https://github.com/jxxghp/MoviePilot/assets/125949466/8e1f2daa-170f-455e-b776-e1b75a931bc8)
异常提示如下
![image](https://github.com/jxxghp/MoviePilot/assets/125949466/487de68b-87c9-4760-a06e-aa2f640441a3)
新一集资源已出，无法正常入库

### 发生问题时系统日志和配置文件

```bash
re.error: nothing to repeat at position 0
    raise source.error("nothing to repeat",
  File "/usr/local/lib/python3.11/re/_parser.py", line 682, in _parse
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.11/re/_parser.py", line 455, in _parse_sub
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.11/re/_parser.py", line 980, in parse
        ^^^^^^^^^^^^^^^^^^^^^^^
    p = _parser.parse(p, flags)
  File "/usr/local/lib/python3.11/re/_compiler.py", line 743, in compile
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    p = _compiler.compile(pattern, flags)
  File "/usr/local/lib/python3.11/re/__init__.py", line 294, in _compile
           ^^^^^^^^^^^^^^^^^^^^^^^^
    return _compile(pattern, flags).search(string)
  File "/usr/local/lib/python3.11/re/__init__.py", line 176, in search
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    if not re.search(r"%s" % include, content, re.I):
  File "/app/app/helper/torrent.py", line 367, in filter_torrent
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    if not self.torrenthelper.filter_torrent(torrent_info=torrent_info,
  File "/app/app/chain/subscribe.py", line 715, in match
    self.match(
  File "/app/app/chain/subscribe.py", line 456, in refresh
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 367, in start
【ERROR】2024-05-27 13:14:38,533 - scheduler.py - 定时任务 订阅刷新 执行失败：nothing to repeat at position 0 - Traceback (most recent call last):
【DEBUG】2024-05-27 13:14:38,531 - chain - 请求模块执行：filter_torrents ...
【INFO】2024-05-27 13:14:38,530 - subscribe.py - 恋爱兄妹 (2024) 通过媒体信ID匹配到资源：彩虹岛 - My Sibling'S Romance S01 1080p Linetv WEB-DL AAC2.0 H.264-CHDWEB
【DEBUG】2024-05-27 13:14:38,529 - subscribe.py - 开始匹配站点：ptchdbits.co，共缓存了 50 个种子...
【INFO】2024-05-27 13:14:38,528 - subscribe.py - 订阅 恋爱兄妹 (2024) S01 缺失集：[13, 14, 15]
【DEBUG】2024-05-27 13:14:38,527 - download.py - 媒体库中已存在部分剧集，缺失：{247085: {1: NotExistMediaInfo(season=1, episodes=[13, 14, 15], total_episode=15, start_episode=13)}}
【INFO】2024-05-27 13:14:38,523 - emby - 恋爱兄妹 (2024) 媒体库中已存在：{1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]}
【DEBUG】2024-05-27 13:14:38,513 - chain - 请求模块执行：media_exists ...
【INFO】2024-05-27 13:14:38,511 - themoviedb - 恋爱兄妹 TMDB识别结果：电视剧 恋爱兄妹 (2024) 247085
【DEBUG】2024-05-27 13:14:38,509 - tmdbapi.py - 247085 查询结果：恋爱兄妹
【DEBUG】2024-05-27 13:14:38,508 - tmdbapi.py - 正在查询TMDB电视剧：247085 ...
【DEBUG】2024-05-27 13:14:38,503 - chain - 请求模块执行：recognize_media ...
【INFO】2024-05-27 13:14:38,500 - subscribe.py - 开始匹配订阅，标题：恋爱兄妹 ...
```

**Comment by jxxghp** [comment]
这就是正则式写错了报的错啊
