### ISSUE TITLE
[错误报告]: 使用目录同步插件进行整理时，不开启自动分类的情况下，会通知报错

### ISSUE THREAD

**Issue by xiaobaiwaf** [jxxghp/MoviePilot#2292]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/97422881/d1bd0e81-750f-497c-adc5-14cead66a08a)
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/d1715489-4965-4721-a6c9-3f0706835d1e)
图1画线处，我没有开启自动分类，系统通知就会有图2的错误，实际并没有问题，是不是可以优化一下这个通知

**Comment by jxxghp** [comment]
提供一下日志

**Comment by xiaobaiwaf** [comment]
我在mp日志和目录同步日志里没看到相关信息......

**Comment by xiaobaiwaf** [comment]
佬，这个是不是分类的问题啊，但实际情况是整理成功了，我是rclone网盘挂载，然后直接移动进去

**Comment by jxxghp** [comment]
没有日志，看不出来问题在哪里。
另外，用的是哪个源的目录监控插件？

**Comment by xiaobaiwaf** [comment]
官方插件的，找到日志了
2024-06-14T01:58:15.699904358Z INFO:    filetransfer - 获取转移目标路径：/media3/国产剧
2024-06-14T01:58:15.705307189Z INFO:    filetransfer - 正在转移文件：/downloads/下载目录/3国产剧/显微镜下的大明之丝绢案.Under.the.Microscope.S01.2023.IQ.2160p.WEB-DL.H265.AAC-HHWEB/Under.the.Microscope.S01E09.2023.IQ.2160p.WEB-DL.H265.AAC-HHWEB.mp4 到 /media3/国产剧/显微镜下的大明之丝绢案(2023)[tmdbid=139169]/Season1/S01E09 - 2160p - WEB-DL - IQ - HHWEB.mp4
2024-06-14T01:58:16.274941156Z INFO:     74.48.85.59:0 - "GET /api/v1/plugin/dashboard/DouBanWatching HTTP/1.1" 200 OK
2024-06-14T01:58:16.446640317Z ERROR:   chain - 运行模块 EmbyModule.media_exists 出错：'dict' object has no attribute 'type'
2024-06-14T01:58:16.446666587Z Traceback (most recent call last):
2024-06-14T01:58:16.446670004Z   File "/app/app/chain/__init__.py", line 107, in run_module
2024-06-14T01:58:16.446673170Z     result = func(*args, **kwargs)
2024-06-14T01:58:16.446676105Z              ^^^^^^^^^^^^^^^^^^^^^
2024-06-14T01:58:16.446679262Z   File "/app/app/modules/emby/__init__.py", line 72, in media_exists
2024-06-14T01:58:16.446682388Z     if mediainfo.type == MediaType.MOVIE:
2024-06-14T01:58:16.446685334Z        ^^^^^^^^^^^^^^
2024-06-14T01:58:16.446688209Z AttributeError: 'dict' object has no attribute 'type'
2024-06-14T01:58:16.446691094Z 
2024-06-14T01:58:16.456877976Z INFO:    command.py - 处理事件：system.error - []
2024-06-14T01:58:16.458133751Z ERROR:   chain - 运行模块 FileTransferModule.media_exists 出错：'dict' object has no attribute 'type'
2024-06-14T01:58:16.458165612Z Traceback (most recent call last):
2024-06-14T01:58:16.458170762Z   File "/app/app/chain/__init__.py", line 107, in run_module
2024-06-14T01:58:16.458175081Z     result = func(*args, **kwargs)
2024-06-14T01:58:16.458179098Z              ^^^^^^^^^^^^^^^^^^^^^
2024-06-14T01:58:16.458183106Z   File "/app/app/modules/filetransfer/__init__.py", line 720, in media_exists
2024-06-14T01:58:16.458187384Z     if mediainfo.type == MediaType.TV else settings.MOVIE_RENAME_FORMAT
2024-06-14T01:58:16.458191451Z        ^^^^^^^^^^^^^^
2024-06-14T01:58:16.458195610Z AttributeError: 'dict' object has no attribute 'type'
2024-06-14T01:58:16.458199748Z 
2024-06-14T01:58:16.461271736Z INFO:    command.py - 处理事件：system.error - []
2024-06-14T01:58:18.556602023Z INFO:     74.48.85.59:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
2024-06-14T01:58:22.227437572Z INFO:     74.48.85.59:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK

**Comment by xiaobaiwaf** [comment]
应该不是插件的问题吧，我用的官方的目录监控
