### ISSUE TITLE
[错误报告]: MP开启豆瓣榜单订阅后导致NAS磁盘空间满了，遂腾出空间重建容器后，发现站点数据统计插件不工作

### ISSUE THREAD

**Issue by kingcard1131** [jxxghp/MoviePilot#2317]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

前端版本：v1.9.4-1，后端版本：v1.9.4-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

 MP开启豆瓣榜单订阅后导致NAS磁盘空间满了，遂腾出空间重建容器后，发现站点数据统计插件不工作。不知道是不是个问题，烦请大佬帮忙看下如何解决，谢谢

### 发生问题时系统日志和配置文件

```bash
moviepilot-moviepilot-1  | ERROR:    Exception in ASGI application
moviepilot-moviepilot-1  | Traceback (most recent call last):
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/cursor.py", line 1135, in fetchall
moviepilot-moviepilot-1  |     rows = dbapi_cursor.fetchall()
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  | sqlite3.DatabaseError: database disk image is malformed
moviepilot-moviepilot-1  | 
moviepilot-moviepilot-1  | The above exception was the direct cause of the following exception:
moviepilot-moviepilot-1  | 
moviepilot-moviepilot-1  | Traceback (most recent call last):
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
moviepilot-moviepilot-1  |     result = await app(  # type: ignore[func-returns-value]
moviepilot-moviepilot-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
moviepilot-moviepilot-1  |     return await self.app(scope, receive, send)
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
moviepilot-moviepilot-1  |     await super().__call__(scope, receive, send)
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
moviepilot-moviepilot-1  |     await self.middleware_stack(scope, receive, send)
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
moviepilot-moviepilot-1  |     raise exc
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
moviepilot-moviepilot-1  |     await self.app(scope, receive, _send)
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
moviepilot-moviepilot-1  |     await self.app(scope, receive, send)
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/app/app/plugins/sitestatistic/__init__.py", line 935, in get_page
moviepilot-moviepilot-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2693, in all
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1786, in all
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1693, in _fetchall_impl
moviepilot-moviepilot-1  |     return self._real_result._fetchall_impl()
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 2293, in _fetchall_impl
moviepilot-moviepilot-1  |     return list(self.iterator)
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 215, in chunks
moviepilot-moviepilot-1  |     fetch = cursor._raw_all_rows()
moviepilot-moviepilot-1  |             ^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 546, in _raw_all_rows
moviepilot-moviepilot-1  |     rows = self._fetchall_impl()
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/cursor.py", line 2102, in _fetchall_impl
moviepilot-moviepilot-1  |     return self.cursor_strategy.fetchall(self, self.cursor)
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/cursor.py", line 1139, in fetchall
moviepilot-moviepilot-1  |     self.handle_exception(result, dbapi_cursor, e)
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/cursor.py", line 1080, in handle_exception
moviepilot-moviepilot-1  |     result.connection._handle_dbapi_exception(
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
moviepilot-moviepilot-1  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/cursor.py", line 1135, in fetchall
moviepilot-moviepilot-1  |     rows = dbapi_cursor.fetchall()
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  | sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
moviepilot-moviepilot-1  | (Background on this error at: https://sqlalche.me/e/20/4xp6)
```

**Comment by kingcard1131** [comment]
删除userDB，然后恢复之前的userDB解决了

**Comment by kingcard1131** [comment]
删掉userDB 恢复之前的userDB是可以的，但是还是报上述错误，不知道有什么影响没有。

**Comment by jxxghp** [comment]
这个错误是由于 SQLite 数据库文件损坏所导致的。具体的报错信息是 sqlite3.DatabaseError: database disk image is malformed，表示 SQLite 数据库文件的磁盘镜像损坏。
