### ISSUE TITLE
[错误报告]: 重命名格式报错

### ISSUE THREAD

**Issue by uploadrclone** [jxxghp/MoviePilot#237]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.5

### 问题类型

其他问题

### 问题描述

把之前nas-tool的重命名格式复制过来后moviepiolt的文件转移一直不能报错

### 发生问题时系统日志和配置文件

```bash
#电影重命名格式
MOVIE_RENAME_FORMAT='{title} {original_title} ({year}) {{tmdb-{tmdbid}}}/{videoFormat} {edition} {videoCodec} {releaseGroup}/{original_name}'
# 电视剧重命名格式
TV_RENAME_FORMAT='{title} {original_title} ({year}) {{tmdb-{tmdbid}}}/Season {season:0>2}/{videoFormat} {edition} {videoCodec} {releaseGroup}/{original_name}'


docker日志
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 90, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filetransfer/__init__.py", line 50, in transfer
    return self.transfer_media(in_path=path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filetransfer/__init__.py", line 421, in transfer_media
    new_path = target_dir / (self.get_rename_path(
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filetransfer/__init__.py", line 549, in get_rename_path
    template = Template(template_string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1208, in __new__
    return env.from_string(source, template_class=cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
2023-08-23 09:52:54,089 - __init__.py -【ERROR】运行模块 transfer 出错：FileTransferModule - expected token ':', got '}'
None
2023-08-23 09:52:54,090 - transfer.py -【ERROR】文件转移模块运行失败
```

**Comment by jxxghp** [comment]
@uploadrclone 你是要干啥。。。

**Comment by uploadrclone** [comment]
就是在刮削的时候自定义下电影和电视剧的重命名格式

**Comment by jxxghp** [comment]
@uploadrclone 看下github文档吧，没说过是跟NT一样的格式啊

**Comment by uploadrclone** [comment]
> @uploadrclone 看下github文档吧，没说过是跟NT一样的格式啊

看过每个字段都是有的

**Comment by mjsoftking** [comment]
你在好好看看这个示例

{{title}}{% if year %} ({{year}}){% endif %}/{{title}}{% if year %} ({{year}}){% endif %}{% if part %}-{{part}}{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{{fileExt}}

**Comment by uploadrclone** [comment]
> @uploadrclone
> 
> ```
> {{title}} {% if original_title %}{{original_title}}{% endif %}{% if year %} ({{year}}){% endif %}{% if tmdbid %} tmdb-{{tmdbid}}{% endif %}/{% if videoFormat %}{{videoFormat}}{% endif %}{% if edition %} {{edition}}{% endif %}{% if videoCodec %} {{videoCodec}}{% endif %}{% if releaseGroup %} {{releaseGroup}}{% endif %}/{% if original_name %} {{original_name}}{% endif %}{{fileExt}}
> ```
> 
> 未测试，按规则写的

刚才搞定了 tmdbid那括号卡了半天 谢谢哥们了

**Comment by mjsoftking** [comment]
@uploadrclone 刚才看到你的那个了，最好加上判断，万一那个字段没有不一定出来个什么
