### ISSUE TITLE
[错误报告]: 无法进行搜索，搜索会一直loading，无结果

### ISSUE THREAD

**Issue by lmaoxswl** [jxxghp/MoviePilot#238]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.5

### 问题类型

主程序运行问题

### 问题描述

已经添加好站点，5个站点，全部勾选了，然后在推荐里随便找了个电影搜索资源，一直显示“正在搜索，请稍后”

### 发生问题时系统日志和配置文件

```bash
实时日志
File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 212, in _new_conn
raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f5dbc705210>, 'Connection to api.telegram.org timed out. (connect timeout=15)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
resp = conn.urlopen(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
retries = retries.increment(
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6095295273:AAETriJmkO0rC_v2_l5dZ13Hgl6fQ8dHvZc/getMe (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5dbc705210>, 'Connection to api.telegram.org timed out. (connect timeout=15)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 955, in infinity_polling
self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 1040, in polling
logger.info('Starting your bot with username: [@%s]', self.user.username)
^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 273, in user
self._user = self.get_me()
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 1236, in get_me
result = apihelper.get_me(self.token)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/apihelper.py", line 196, in get_me
return _make_request(token, method_url)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/apihelper.py", line 156, in _make_request
result = _get_req_session().request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6095295273:AAETriJmkO0rC_v2_l5dZ13Hgl6fQ8dHvZc/getMe (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5dbc705210>, 'Connection to api.telegram.org timed out. (connect timeout=15)'))
2023-08-23 12:37:32,096 - tmdbapi.py -【INFO】正在发现电影：{'sort_by': 'popularity.desc', 'with_genres': '', 'with_original_language': '', 'page': 1}...
2023-08-23 12:37:32,096 - tmdbapi.py -【INFO】正在发现电视剧：{'sort_by': 'popularity.desc', 'with_genres': '', 'with_original_language': 'zh|en|ja|ko', 'page': 1}...
2023-08-23 12:37:46,501 - __init__.py -【ERROR】Infinity polling exception: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6095295273:AAETriJmkO0rC_v2_l5dZ13Hgl6fQ8dHvZc/getMe (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5dbc655350>, 'Connection to api.telegram.org timed out. (connect timeout=15)'))
2023-08-23 12:37:46,502 - __init__.py -【ERROR】Exception traceback:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
sock = connection.create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
raise err
File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
sock.connect(sa)
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
raise new_e
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
self.sock = sock = self._new_conn()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 212, in _new_conn
raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f5dbc655350>, 'Connection to api.telegram.org timed out. (connect timeout=15)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
resp = conn.urlopen(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
retries = retries.increment(
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6095295273:AAETriJmkO0rC_v2_l5dZ13Hgl6fQ8dHvZc/getMe (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5dbc655350>, 'Connection to api.telegram.org timed out. (connect timeout=15)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 955, in infinity_polling
self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 1040, in polling
logger.info('Starting your bot with username: [@%s]', self.user.username)
^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 273, in user
self._user = self.get_me()
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 1236, in get_me
result = apihelper.get_me(self.token)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/apihelper.py", line 196, in get_me
return _make_request(token, method_url)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/apihelper.py", line 156, in _make_request
result = _get_req_session().request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot6095295273:AAETriJmkO0rC_v2_l5dZ13Hgl6fQ8dHvZc/getMe (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5dbc655350>, 'Connection to api.telegram.org timed out. (connect timeout=15)'))
```

**Comment by jxxghp** [comment]
网络连不上，自行解决网络问题
