### ISSUE TITLE
[错误报告]: 下载器文件转移无法正常刮削

### ISSUE THREAD

**Issue by GilgameshXI** [jxxghp/MoviePilot#2412]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

下载器文件转移无法正常刮削

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-06-24 18:03:15,355 - transfer.py - 下载器文件转移执行完成
【INFO】2024-06-24 18:03:15,348 - transfer.py - /Theatre/downloads/TV Shows/EU&US Series/House.Of.The.Dragon.S02.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb/House.Of.The.Dragon.S02E02.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv 转移完成，共 1 个文件，失败 0 个，跳过 0 个
【INFO】2024-06-24 18:03:15,348 - command.py - 处理事件：transfer.complete - [<function PersonMeta.scrap_rt at 0x7fd692665760>]
【INFO】2024-06-24 18:03:13,895 - command.py - 处理事件：notice.message - []
【INFO】2024-06-24 18:03:13,892 - chain - 发送消息：channel=None，title=龙之家族 (2022) S02 E02 已入库, text=评分：8.4，类型：电视剧，类别：EU&US Series，质量： WEB-DL HDR DV 2160p，共1个文件，大小：10.71G，userid=None
【INFO】2024-06-24 18:03:13,891 - themoviedb - /Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/Season 2/龙之家族 - S02E02 - 2160p - MAX - WEB-DL - X265 - HDR DV - DDP 5.1 Atmos - ADWeb.mkv 刮削完成

NotADirectoryError: [Errno 20] Not a directory: '/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/Season 2/龙之家族 - S02E02 - 2160p - MAX - WEB-DL - X265 - HDR DV - DDP 5.1 Atmos - ADWeb.mkv/season.nfo'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return io.open(self, mode, buffering, encoding, errors, newline)
  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
         ^^^^^^^^^^^^^^^^^^^^
    with self.open(mode='wb') as f:
  File "/usr/local/lib/python3.11/pathlib.py", line 1067, in write_bytes
    file_path.write_bytes(xml_str)
  File "/app/app/modules/themoviedb/scraper.py", line 441, in __save_nfo
    self.__save_nfo(doc, season_path.joinpath("season.nfo"))
  File "/app/app/modules/themoviedb/scraper.py", line 343, in __gen_tv_season_nfo_file
    self.__gen_tv_season_nfo_file(seasoninfo=seasoninfo,
  File "/app/app/modules/themoviedb/scraper.py", line 169, in gen_scraper_files
【ERROR】2024-06-24 18:03:13,889 - scraper.py - /Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/Season 2/龙之家族 - S02E02 - 2160p - MAX - WEB-DL - X265 - HDR DV - DDP 5.1 Atmos - ADWeb.mkv 刮削失败：[Errno 20] Not a directory: '/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/Season 2/龙之家族 - S02E02 - 2160p - MAX - WEB-DL - X265 - HDR DV - DDP 5.1 Atmos - ADWeb.mkv/season.nfo' - Traceback (most recent call last):
【INFO】2024-06-24 18:03:13,886 - scraper.py - 正在生成季NFO文件：龙之家族 - S02E02 - 2160p - MAX - WEB-DL - X265 - HDR DV - DDP 5.1 Atmos - ADWeb.mkv
【INFO】2024-06-24 18:03:13,881 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/season01-thumb.jpg
【INFO】2024-06-24 18:03:11,836 - scraper.py - 正在下载season01-thumb图片：https://assets.fanart.tv/fanart/tv/371572/seasonthumb/house-of-the-dragon--6313c3014936c.jpg ...
【INFO】2024-06-24 18:03:11,833 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/thumb.jpg
【INFO】2024-06-24 18:03:09,828 - scraper.py - 正在下载thumb图片：https://assets.fanart.tv/fanart/tv/371572/tvthumb/house-of-the-dragon--6303510d17085.jpg ...
【INFO】2024-06-24 18:03:09,825 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/banner.jpg
【INFO】2024-06-24 18:03:08,060 - scraper.py - 正在下载banner图片：https://assets.fanart.tv/fanart/tv/371572/tvbanner/house-of-the-dragon--63035085b8c32.jpg ...
【INFO】2024-06-24 18:03:08,057 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/season01-poster.jpg
【INFO】2024-06-24 18:03:05,769 - scraper.py - 正在下载season01-poster图片：https://assets.fanart.tv/fanart/tv/371572/seasonposter/house-of-the-dragon--63127cf2562ed.jpg ...
【INFO】2024-06-24 18:03:05,766 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/season01-banner.jpg
【INFO】2024-06-24 18:03:04,213 - scraper.py - 正在下载season01-banner图片：https://assets.fanart.tv/fanart/tv/371572/seasonbanner/house-of-the-dragon--63127d965fd76.jpg ...
【INFO】2024-06-24 18:03:04,206 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/background.jpg
【INFO】2024-06-24 18:03:02,020 - scraper.py - 正在下载background图片：https://assets.fanart.tv/fanart/tv/371572/showbackground/house-of-the-dragon--62cef6eb3d3a0.jpg ...
【INFO】2024-06-24 18:03:02,017 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/clearart.png
【INFO】2024-06-24 18:02:59,573 - scraper.py - 正在下载clearart图片：https://assets.fanart.tv/fanart/tv/371572/hdclearart/house-of-the-dragon--6249daeaf3052.png ...
【INFO】2024-06-24 18:02:59,570 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/logo.png
【INFO】2024-06-24 18:02:57,252 - scraper.py - 正在下载logo图片：https://assets.fanart.tv/fanart/tv/371572/hdtvlogo/house-of-the-dragon--6249da9eaac45.png ...
【INFO】2024-06-24 18:02:57,249 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/poster.jpg
【INFO】2024-06-24 18:02:56,777 - scraper.py - 正在下载poster图片：https://image.tmdb.org/t/p/original/laZcaAXraBbBu6hgmwqJDLUXX3r.jpg ...
【INFO】2024-06-24 18:02:56,775 - scraper.py - 图片已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/backdrop.jpg
【INFO】2024-06-24 18:02:56,118 - scraper.py - 正在下载backdrop图片：https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg ...
【INFO】2024-06-24 18:02:56,116 - scraper.py - NFO文件已保存：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/tvshow.nfo
【INFO】2024-06-24 18:02:56,113 - scraper.py - 正在生成电视剧NFO文件：龙之家族 (2022)
【INFO】2024-06-24 18:02:56,111 - themoviedb - 开始刮削媒体库文件：/Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/Season 2/龙之家族 - S02E02 - 2160p - MAX - WEB-DL - X265 - HDR DV - DDP 5.1 Atmos - ADWeb.mkv ...
【INFO】2024-06-24 18:02:56,082 - filetransfer - 文件 /Theatre/downloads/TV Shows/EU&US Series/House.Of.The.Dragon.S02.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb/House.Of.The.Dragon.S02E02.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv 转移成功
【INFO】2024-06-24 18:02:56,076 - filetransfer - 文件 /Theatre/downloads/TV Shows/EU&US Series/House.Of.The.Dragon.S02.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb/House.Of.The.Dragon.S02E02.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv link完成
【INFO】2024-06-24 18:02:56,074 - filetransfer - 正在转移文件：/Theatre/downloads/TV Shows/EU&US Series/House.Of.The.Dragon.S02.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb/House.Of.The.Dragon.S02E02.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv 到 /Theatre/links/TV Shows/EU&US Series/龙之家族 (2022)/Season 2/龙之家族 - S02E02 - 2160p - MAX - WEB-DL - X265 - HDR DV - DDP 5.1 Atmos - ADWeb.mkv
【INFO】2024-06-24 18:02:56,069 - filetransfer - 目标路径不存在，正在创建：/Theatre/links/TV Shows/EU&US Series ...
【INFO】2024-06-24 18:02:56,067 - filetransfer - 获取转移目标路径：/Theatre/links/TV Shows/EU&US Series
【INFO】2024-06-24 18:02:55,799 - doh.py - 已解析 [api.themoviedb.org] 为 [13.224.163.26] (缓存)
【INFO】2024-06-24 18:02:55,793 - transfer.py - House.Of.The.Dragon.S02E02.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv 识别为：电视剧 龙之家族 (2022)
【INFO】2024-06-24 18:02:55,784 - themoviedb - 94997 TMDB识别结果：电视剧 龙之家族 (2022)
【INFO】2024-06-24 18:02:55,772 - transfer.py - 获取到 1 个已完成的下载任务
【INFO】2024-06-24 18:02:55,740 - transfer.py - 开始执行下载器文件转移 ...
```

**Comment by lutian98** [comment]
确实 遇到同样的报错了

**Comment by lx129** [comment]
手动刮削也无法出刮削图片
【INFO】2024-06-25 12:49:34,196 - media.py - 仙逆 - S01E42 - 第 42 集.mkv 刮削完成
【INFO】2024-06-25 12:49:34,194 - media.py - /volume3/Download/media/links/tv/仙逆 (2023)/Season 1/仙逆 - S01E42 - 第 42 集.nfo 已保存
【INFO】2024-06-25 12:49:34,187 - media.py - 正在保存 仙逆 - S01E42 - 第 42 集.nfo ...
【INFO】2024-06-25 12:49:34,039 - themoviedb - 仙逆 TMDB识别结果：电视剧 仙逆 (2023) 223911
【INFO】2024-06-25 12:49:34,025 - themoviedb - 仙逆 使用TMDB识别缓存：仙逆
【INFO】2024-06-25 12:49:34,009 - media.py - 开始刮削：/volume3/Download/media/links/tv/仙逆 (2023)/Season 1/仙逆 - S01E42 - 第 42 集.mkv ...
【INFO】2024-06-25 12:49:32,773 - media.py - 仙逆 - S01E42 - 第 42 集.mkv 识别到媒体信息：电视剧 仙逆 (2023)
【INFO】2024-06-25 12:49:32,629 - themoviedb - 仙逆 TMDB识别结果：电视剧 仙逆 (2023) 223911
【INFO】2024-06-25 12:49:32,400 - themoviedb - 仙逆 使用TMDB识别缓存：仙逆
