### ISSUE TITLE
[错误报告]: 突然启动失败

### ISSUE THREAD

**Issue by Kev1nT** [jxxghp/MoviePilot#2428]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.8-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

今天突然启动不起来了，麻烦帮忙看下是什么原因导致的。
昨天最后的操作应该是安装了Plex演职人员刮削的插件，如果是插件问题，请问要怎么在目录里删除插件。

### 发生问题时系统日志和配置文件

```bash
2024/06/26 11:52:50	stdout	[31mERROR[0m:    Application startup failed. Exiting.
2024/06/26 11:52:50	stdout	
2024/06/26 11:52:50	stdout	apscheduler.jobstores.base.ConflictingIdError: 'Job identifier (PersonMeta) conflicts with an existing job'
2024/06/26 11:52:50	stdout	    raise ConflictingIdError(job.id)
2024/06/26 11:52:50	stdout	  File "/usr/local/lib/python3.11/site-packages/apscheduler/jobstores/memory.py", line 41, in add_job
2024/06/26 11:52:50	stdout	    store.add_job(job)
2024/06/26 11:52:50	stdout	  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 881, in _real_add_job
2024/06/26 11:52:50	stdout	    self._real_add_job(job, jobstore_alias, replace_existing)
2024/06/26 11:52:50	stdout	  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 177, in start
2024/06/26 11:52:50	stdout	    BaseScheduler.start(self, *args, **kwargs)
2024/06/26 11:52:50	stdout	  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/background.py", line 35, in start
2024/06/26 11:52:50	stdout	    self._scheduler.start()
2024/06/26 11:52:50	stdout	  File "/app/app/scheduler.py", line 354, in init
2024/06/26 11:52:50	stdout	    self.init()
2024/06/26 11:52:50	stdout	  File "/app/app/scheduler.py", line 57, in __init__
2024/06/26 11:52:50	stdout	                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/06/26 11:52:50	stdout	    cls._instances[key] = super().__call__(*args, **kwargs)
2024/06/26 11:52:50	stdout	  File "/app/app/utils/singleton.py", line 14, in __call__
2024/06/26 11:52:50	stdout	    Scheduler()
2024/06/26 11:52:50	stdout	  File "/app/app/main.py", line 224, in start_module
2024/06/26 11:52:50	stdout	    handler()
2024/06/26 11:52:50	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 656, in startup
2024/06/26 11:52:50	stdout	    await self._router.startup()
2024/06/26 11:52:50	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
2024/06/26 11:52:50	stdout	    async with self.lifespan_context(app) as maybe_state:
2024/06/26 11:52:50	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
2024/06/26 11:52:49	stdout	[31mERROR[0m:    Traceback (most recent call last):
2024/06/26 11:52:49	stdout	    Plex演职人员刮削 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='0'], pending)
2024/06/26 11:52:49	stdout	    Plex中文本地化 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='0'], pending)
2024/06/26 11:52:49	stdout	    Plex元数据刷新 (trigger: cron[month='*', day='*', day_of_week='*', hour='*/3', minute='0'], pending)
2024/06/26 11:52:49	stdout	    定时推送天气通知 (trigger: cron[month='*', day='*', day_of_week='*', hour='8', minute='0'], pending)
2024/06/26 11:52:49	stdout	    定时获取天气信息 (trigger: interval[1:00:00], pending)
2024/06/26 11:52:49	stdout	    演职人员刮削服务 (trigger: cron[month='*', day='*', day_of_week='*', hour='2', minute='0'], pending)
2024/06/26 11:52:49	stdout	    获取远端识别词 (trigger: cron[month='*', day='*', day_of_week='*', hour='4', minute='30'], pending)
2024/06/26 11:52:49	stdout	    自动删种服务 (trigger: cron[month='*', day='*', day_of_week='*', hour='*/12', minute='0'], pending)
2024/06/26 11:52:49	stdout	    媒体库刮削 (trigger: cron[month='*', day='*/7', day_of_week='*', hour='0', minute='0'], pending)
2024/06/26 11:52:49	stdout	    豆瓣想看同步服务 (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='*/30'], pending)
2024/06/26 11:52:49	stdout	    站点数据统计服务 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='5'], pending)
2024/06/26 11:52:49	stdout	    站点自动签到服务 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='0'], pending)
2024/06/26 11:52:49	stdout	    用户认证检查 (trigger: interval[0:10:00], pending)
2024/06/26 11:52:49	stdout	    缓存清理 (trigger: interval[3 days, 0:00:00], pending)
2024/06/26 11:52:49	stdout	    公共定时服务 (trigger: interval[0:10:00], pending)
2024/06/26 11:52:49	stdout	    壁纸缓存 (trigger: interval[0:30:00], next run at: 2024-06-26 11:52:52 CST)
2024/06/26 11:52:49	stdout	    下载文件整理 (trigger: interval[0:05:00], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='22', minute='42'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='22', minute='17'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='21', minute='48'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='21', minute='23'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='20', minute='57'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='20', minute='36'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='20', minute='7'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='19', minute='46'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='19', minute='6'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='18', minute='39'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='18', minute='14'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='17', minute='35'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='17', minute='5'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='16', minute='25'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='16', minute='1'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='15', minute='24'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='15', minute='0'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='14', minute='36'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='14', minute='4'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='13', minute='44'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='13', minute='22'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='12', minute='59'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='12', minute='28'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='11', minute='50'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='11', minute='20'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='10', minute='53'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='10', minute='18'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='9', minute='52'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='9', minute='24'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='8', minute='47'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='8', minute='8'], pending)
2024/06/26 11:52:49	stdout	    订阅刷新 (trigger: cron[hour='7', minute='37'], pending)
2024/06/26 11:52:49	stdout	    订阅搜索补全 (trigger: interval[1 day, 0:00:00], pending)
2024/06/26 11:52:49	stdout	    订阅元数据更新 (trigger: interval[6:00:00], pending)
2024/06/26 11:52:49	stdout	    新增订阅搜索 (trigger: interval[0:05:00], pending)
2024/06/26 11:52:49	stdout	    同步媒体服务器 (trigger: interval[6:00:00], next run at: 2024-06-26 11:57:49 CST)
2024/06/26 11:52:49	stdout	    同步CookieCloud站点 (trigger: interval[1 day, 0:00:00], next run at: 2024-06-26 11:53:49 CST)
2024/06/26 11:52:49	stdout	Pending jobs:
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件Plex演职人员刮削服务：Plex演职人员刮削 - cron[month='*', day='*', day_of_week='*', hour='1', minute='0']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plexpersonmeta - Plex演职人员刮削定时服务启动，时间间隔 0 1 * * * 
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件Plex中文本地化服务：Plex中文本地化 - cron[month='*', day='*', day_of_week='*', hour='1', minute='0']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plexlocalization - Plex中文本地化定时服务启动，时间间隔 0 1 * * * 
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件Plex元数据刷新服务：Plex元数据刷新 - cron[month='*', day='*', day_of_week='*', hour='*/3', minute='0']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plexrefreshrecent - 刷新Plex最近入库元数据定时服务启动，时间间隔 0 */3 * * * 
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件天气服务：定时推送天气通知 - cron[month='*', day='*', day_of_week='*', hour='8', minute='0']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件天气服务：定时获取天气信息 - interval
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件演职人员刮削服务：演职人员刮削服务 - cron[month='*', day='*', day_of_week='*', hour='2', minute='0']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件共享识别词服务：获取远端识别词 - cron[month='*', day='*', day_of_week='*', hour='4', minute='30']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件自动删种服务：自动删种服务 - cron[month='*', day='*', day_of_week='*', hour='*/12', minute='0']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件媒体库刮削服务：媒体库刮削 - cron[month='*', day='*/7', day_of_week='*', hour='0', minute='0']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件豆瓣想看服务：豆瓣想看同步服务 - cron[month='*', day='*', day_of_week='*', hour='*', minute='*/30']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件站点数据统计服务：站点数据统计服务 - cron[month='*', day='*', day_of_week='*', hour='1', minute='5']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    scheduler.py - 注册插件站点自动签到服务：站点自动签到服务 - cron[month='*', day='*', day_of_week='*', hour='1', minute='0']
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：TrendingShow 版本：1.3
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：PluginAutoUpdate 版本：1.9
2024/06/26 11:52:49	stdout	    插件自动更新 (trigger: cron[month='*', day='*', day_of_week='*', hour='2', minute='0'], pending)
2024/06/26 11:52:49	stdout	Pending jobs:
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：PlexPersonMeta 版本：1.0
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：PlexLocalization 版本：1.6
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：PlexRefreshRecent 版本：1.4
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：WeatherWidget 版本：1.8
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：SubscribeReminder 版本：1.1
2024/06/26 11:52:49	stdout	    订阅提醒 (trigger: cron[month='*', day='*', day_of_week='*', hour='9', minute='0'], pending)
2024/06/26 11:52:49	stdout	Pending jobs:
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：SubscribeClear 版本：1.0
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：PersonMeta 版本：1.4
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：MediaServerRefresh 版本：1.2
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：RemoteIdentifiers 版本：2.2
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：MediaSyncDel 版本：1.7
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：TorrentRemover 版本：1.2.2
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：LibraryScraper 版本：1.4.1
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：ChineseSubFinder 版本：1.1
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：CategoryEditor 版本：1.2
2024/06/26 11:52:49	stdout	[32mINFO:[0m    category.py - 已加载二级分类策略 category.yaml
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：LinkMonitor 版本：1.6
2024/06/26 11:52:49	stdout	[32mINFO:[0m    linkmonitor - /downloads2/cosplay 的目录监控服务启动
2024/06/26 11:52:49	stdout	[32mINFO:[0m    linkmonitor - /downloads2/hanime 的目录监控服务启动
2024/06/26 11:52:49	stdout	[32mINFO:[0m    linkmonitor - /downloads2/gc 的目录监控服务启动
2024/06/26 11:52:49	stdout	[32mINFO:[0m    linkmonitor - /downloads2/fc2 的目录监控服务启动
2024/06/26 11:52:49	stdout	[32mINFO:[0m    linkmonitor - /downloads2/onlyfans 的目录监控服务启动
2024/06/26 11:52:49	stdout	[32mINFO:[0m    linkmonitor - /downloads2/portrait 的目录监控服务启动
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：DoubanSync 版本：1.8
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：SiteUnreadMsg 版本：1.9
2024/06/26 11:52:49	stdout	    站点未读消息 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='5'], pending)
2024/06/26 11:52:49	stdout	Pending jobs:
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：SiteStatistic 版本：3.8
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：ConfigCenter 版本：2.5
2024/06/26 11:52:49	stdout	[32mINFO:[0m    plugin.py - 加载插件：AutoSignIn 版本：2.4
2024/06/26 11:52:48	stdout	[32mINFO:[0m    plugin.py - 第三方插件安装完成
2024/06/26 11:52:47	stdout	[32mINFO:[0m    plugin.py - 插件 Plex演职人员刮削 安装成功，版本：1.0
2024/06/26 11:52:47	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:46	stdout	[32mINFO:[0m    doh.py - 已解析 [api.github.com] 为 [20.205.243.168] (缓存)
2024/06/26 11:52:46	stdout	[32mINFO:[0m    plugin.py - 插件 天气 安装成功，版本：1.8
2024/06/26 11:52:45	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:45	stdout	[32mINFO:[0m    doh.py - 已解析 [api.github.com] 为 [20.205.243.168] (缓存)
2024/06/26 11:52:45	stdout	[32mINFO:[0m    plugin.py - 插件 Plex中文本地化 安装成功，版本：1.6
2024/06/26 11:52:42	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:41	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:41	stdout	[32mINFO:[0m    doh.py - 已解析 [api.github.com] 为 [20.205.243.168] (缓存)
2024/06/26 11:52:41	stdout	[32mINFO:[0m    plugin.py - 插件 Plex元数据刷新 安装成功，版本：1.4
2024/06/26 11:52:40	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:39	stdout	[32mINFO:[0m    doh.py - 已解析 [api.github.com] 为 [20.205.243.168] (缓存)
2024/06/26 11:52:39	stdout	[32mINFO:[0m    plugin.py - 插件 订阅提醒 安装成功，版本：1.1
2024/06/26 11:52:38	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:37	stdout	[32mINFO:[0m    doh.py - 已解析 [api.github.com] 为 [20.205.243.168] (缓存)
2024/06/26 11:52:37	stdout	[32mINFO:[0m    plugin.py - 插件 插件更新管理 安装成功，版本：1.9
2024/06/26 11:52:37	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:36	stdout	[32mINFO:[0m    doh.py - 已解析 [api.github.com] 为 [20.205.243.168] (缓存)
2024/06/26 11:52:36	stdout	[32mINFO:[0m    plugin.py - 插件 清理订阅缓存 安装成功，版本：1.0
2024/06/26 11:52:35	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:35	stdout	[32mINFO:[0m    doh.py - 已解析 [api.github.com] 为 [20.205.243.168] (缓存)
2024/06/26 11:52:35	stdout	[32mINFO:[0m    plugin.py - 插件 站点未读消息 安装成功，版本：1.9
2024/06/26 11:52:33	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:32	stdout	[32mINFO:[0m    doh.py - 已解析 [api.github.com] 为 [20.205.243.168]
2024/06/26 11:52:32	stdout	[32mINFO:[0m    plugin.py - 共获取到 141 个线上插件
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133] (缓存)
2024/06/26 11:52:31	stdout	[32mINFO:[0m    plugin.py - 开始安装第三方插件...
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：WechatModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：WebPushModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：TransmissionModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：TheTvDbModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：TheMovieDbModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    category.py - 已加载二级分类策略 category.yaml
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：SubtitleModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：PlexModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：IndexerModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：FilterModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：FileTransferModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：FanartModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：EmbyModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：DoubanModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    module.py - Moudle Loaded：BangumiModule
2024/06/26 11:52:31	stdout	[32mINFO:[0m    resource.py - 所有资源已最新，无需更新
2024/06/26 11:52:31	stdout	[32mINFO:[0m    resource.py - 最新资源包版本：v26
2024/06/26 11:52:30	stdout	[32mINFO:[0m    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.109.133]
2024/06/26 11:52:30	stdout	[32mINFO:[0m    resource.py - 开始检测资源包版本...
2024/06/26 11:52:30	stdout	[32mINFO:[0m    main.py - agsvpt 用户认证成功！
2024/06/26 11:52:30	stdout	[32mINFO:[0m    main.py - 认证资源版本：1.3.0
2024/06/26 11:52:30	stdout	[32mINFO:[0m    main.py - 站点资源版本：1.4.3
2024/06/26 11:52:29	stdout	[32mINFO[0m:     Waiting for application startup.
2024/06/26 11:52:29	stdout	[32mINFO[0m:     Started server process [[36m72[0m]
2024/06/26 11:52:26	stdout	未发现新版本，跳过更新步骤...
2024/06/26 11:52:26	stdout	最新版本号：v1.9.8-1
2024/06/26 11:52:26	stdout	当前版本号：v1.9.8-1
2024/06/26 11:52:26	stdout	Release 更新模式
2024/06/26 11:52:26	stdout	不使用代理更新程序
```

**Comment by mizb** [comment]
一样的问题，安装这个插件后，无法启动了

**Comment by Kev1nT** [comment]
> 一样的问题，安装这个插件后，无法启动了

# 是否开发模式，打开后后台服务将不会启动
DEV=true
添加这边环境变量后，重启MoviePilot，升级Plex演职人员刮削插件，然后再把这个环境变量拿掉或者设置为False
