### ISSUE TITLE
[错误报告]: arm64的docker安装mp时一直重启

### ISSUE THREAD

**Issue by n0thing2speak** [jxxghp/MoviePilot#2457]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

arm64的docker安装mp时一直重启

### 发生问题时系统日志和配置文件

```bash
操作系统：debian 11 aarch64 5.10.79
运行环境：`Docker version 20.10.17, build 100c701`


~/moviepilot# docker compose up
[+] Running 1/0
 ⠿ Container moviepilot  Created                                                                                                                                                                 0.0s
Attaching to moviepilot
moviepilot  | 不使用代理更新程序
moviepilot  | 当前版本号：v1.9.9
moviepilot  | 最新版本号：v1.9.9
moviepilot  | 未发现新版本，跳过更新步骤...
moviepilot  | usermod: no changes
moviepilot  | Proxy dockerbackend started.
moviepilot  | Proxy dockerfrontend started.
moviepilot  | Traceback (most recent call last):
moviepilot  |   File "/app/app/main.py", line 23, in <module>
moviepilot  |     from app.core.plugin import PluginManager
moviepilot  |   File "/app/app/core/plugin.py", line 20, in <module>
moviepilot  |     from app.helper.sites import SitesHelper
moviepilot exited with code 1
moviepilot  | 当前版本号：v1.9.9
moviepilot  | 最新版本号：v1.9.9
moviepilot  | 未发现新版本，跳过更新步骤...
moviepilot  | usermod: no changes
moviepilot  | Proxy dockerbackend started.
moviepilot  | Proxy dockerfrontend started.
moviepilot  | Traceback (most recent call last):
moviepilot  |   File "/app/app/main.py", line 23, in <module>
moviepilot  |     from app.core.plugin import PluginManager
moviepilot  |   File "/app/app/core/plugin.py", line 20, in <module>
moviepilot  |     from app.helper.sites import SitesHelper
moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
moviepilot exited with code 1
moviepilot  | 最新版本号：v1.9.9
moviepilot  | 未发现新版本，跳过更新步骤...
moviepilot  | usermod: no changes
moviepilot  | Proxy dockerbackend started.
moviepilot  | Proxy dockerfrontend started.
moviepilot  | Traceback (most recent call last):
moviepilot  |   File "/app/app/main.py", line 23, in <module>
moviepilot  |     from app.core.plugin import PluginManager
moviepilot  |   File "/app/app/core/plugin.py", line 20, in <module>
moviepilot  |     from app.helper.sites import SitesHelper
moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
moviepilot exited with code 1
moviepilot  | 最新版本号：v1.9.9
moviepilot  | 未发现新版本，跳过更新步骤...
moviepilot  | usermod: no changes
moviepilot  | Proxy dockerbackend started.
moviepilot  | Proxy dockerfrontend started.
moviepilot  | Traceback (most recent call last):
moviepilot  |   File "/app/app/main.py", line 23, in <module>
moviepilot  |     from app.core.plugin import PluginManager
moviepilot  |   File "/app/app/core/plugin.py", line 20, in <module>
moviepilot  |     from app.helper.sites import SitesHelper
moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
moviepilot exited with code 1
moviepilot  | 最新版本号：v1.9.9
moviepilot  | 未发现新版本，跳过更新步骤...
moviepilot  | usermod: no changes
moviepilot  | Proxy dockerbackend started.
moviepilot  | Proxy dockerfrontend started.
moviepilot  | Traceback (most recent call last):
moviepilot  |   File "/app/app/main.py", line 23, in <module>
moviepilot  |     from app.core.plugin import PluginManager
moviepilot  |   File "/app/app/core/plugin.py", line 20, in <module>
moviepilot  |     from app.helper.sites import SitesHelper
moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
moviepilot exited with code 1
moviepilot  | 最新版本号：v1.9.9
moviepilot  | 未发现新版本，跳过更新步骤...
moviepilot  | usermod: no changes
moviepilot  | Proxy dockerbackend started.
moviepilot  | Proxy dockerfrontend started.
moviepilot  | Traceback (most recent call last):
moviepilot  |   File "/app/app/main.py", line 23, in <module>
moviepilot  |     from app.core.plugin import PluginManager
moviepilot  |   File "/app/app/core/plugin.py", line 20, in <module>
moviepilot  |     from app.helper.sites import SitesHelper
moviepilot  | ModuleNotFoundError: No module named 'app.helper.sites'
moviepilot exited with code 1
日志就是一直循环跳这个。
```

**Comment by Whichbfj28** [comment]
![G4 9$MZE6 R77P1T){XUCW4](https://github.com/jxxghp/MoviePilot/assets/47915665/c128e64b-4636-47b9-8662-6442654ce562)
### 配置呢。
猜测更新功能关掉就好了。【      - MOVIEPILOT_AUTO_UPDATE=false】

**Comment by AisukaYuki** [comment]
配置文件备好号，删了容器重新 docker compose up。下载依赖的时候github连接不稳定，下失败了，文件损坏。
MOVIEPILOT_AUTO_UPDATE=release

**Comment by n0thing2speak** [comment]
> ![G4 9$MZE6 R77P1T){XUCW4](https://private-user-images.githubusercontent.com/47915665/344377141-c128e64b-4636-47b9-8662-6442654ce562.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MTA4MDQsIm5iZiI6MTcxOTcxMDUwNCwicGF0aCI6Ii80NzkxNTY2NS8zNDQzNzcxNDEtYzEyOGU2NGItNDYzNi00N2I5LTg2NjItNjQ0MjY1NGNlNTYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDAxMjE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YmIxYTdjZDk3ZDMzN2QxM2JiYmVmZDNhYjMyNTk0ZTFhZjE3YzAxNmU4MTdiZDBmMTA5MzdjNjM3Mjc3MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QT2pu3Lf4kMtKdfBeV96QHEc5cV1K91Vey_RB_V6X8s)
> 
> ### 配置呢。
> 猜测更新功能关掉就好了。【 - MOVIEPILOT_AUTO_UPDATE=false】

sorry忘记贴了，配置就是wiki里面建议的那个，确实关掉自动更新好了。
