### ISSUE TITLE
运行模块 TheMovieDbModule.recognize_media 出错：'NoneType' object is not iterable

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#2508]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.10-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

搜索 ”萨利机长“ 时候提示 
<img width="471" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51367628/3409a1af-7ac9-4932-909f-368f0d6779a2">

<img width="1546" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51367628/bc4c586b-359d-44a2-83ba-8fe79acc0cd9">

其他资源暂未发现问题，目前仅 “萨利机长“ 这一部资源出现

### 发生问题时系统日志和配置文件

ERROR:   chain - 运行模块 TheMovieDbModule.recognize_media 出错：'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 107, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/themoviedb/__init__.py", line 177, in recognize_media
    mediainfo = MediaInfo(tmdb_info=info)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 56, in __init__
  File "/app/app/core/context.py", line 246, in __post_init__
    self.set_tmdb_info(self.tmdb_info)
  File "/app/app/core/context.py", line 433, in set_tmdb_info
    self.directors, self.actors = __directors_actors(info)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/core/context.py", line 350, in __directors_actors
    for cast in _credits.get("cast"):
TypeError: 'NoneType' object is not iterable

INFO:    command.py - 处理事件：system.error - []
ERROR:   search.py - 363676 媒体信息识别失败！

**Comment by paysenyu** [comment]
![telegram-cloud-photo-size-5-6070993499496496547-y](https://github.com/jxxghp/MoviePilot/assets/51367628/9fb5f1fc-9a39-4b4d-9910-ddb2383289ae)

这是tg群 其他人也遇到的问题， 应该不是个例
