### ISSUE TITLE
[错误报告]: 无法获取到TMDB媒体信息

### ISSUE THREAD

**Issue by ezerear** [jxxghp/MoviePilot#256]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.6

### 问题类型

主程序运行问题

### 问题描述

在搜索框搜索电影，很快就会返回 无法获取到TMDB媒体信息。

![image](https://github.com/jxxghp/MoviePilot/assets/34952287/f8e69589-7000-4f33-a203-6a97fb9b957c)

网络测试都是正常的

![image](https://github.com/jxxghp/MoviePilot/assets/34952287/966de627-905c-40df-aec0-23a8ff5e59b2)

### 发生问题时系统日志和配置文件

```bash
2023/8/24 17:08:06  【WARNING】 media.py - 恶鬼 没有找到对应的媒体信息！
2023/8/24 17:08:06  None
2023/8/24 17:08:06  【ERROR】  __init__.py - 运行模块 search_medias 出错：TheMovieDbModule - Expecting value: line 1 column 1 (char 0)
2023/8/24 17:08:06  requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023/8/24 17:08:06      raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2023/8/24 17:08:06    File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
2023/8/24 17:08:06             ^^^^^^^^^^
2023/8/24 17:08:06      json = req.json()
2023/8/24 17:08:06    File "/app/app/modules/themoviedb/tmdbv3api/tmdb.py", line 175, in _request_obj
2023/8/24 17:08:06             ^^^^^^^^^^^^^^^^^^
2023/8/24 17:08:06      return self._request_obj(
2023/8/24 17:08:06    File "/app/app/modules/themoviedb/tmdbv3api/objs/search.py", line 100, in multi
2023/8/24 17:08:06               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/8/24 17:08:06      multis = self.search.multi(term=title) or []
2023/8/24 17:08:06    File "/app/app/modules/themoviedb/tmdbapi.py", line 57, in search_multiis
2023/8/24 17:08:06                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/8/24 17:08:06      results = self.tmdb.search_multiis(meta.name)
2023/8/24 17:08:06    File "/app/app/modules/themoviedb/__init__.py", line 163, in search_medias
2023/8/24 17:08:06               ^^^^^^^^^^^^^^^^^^^^^
2023/8/24 17:08:06      result = func(*args, **kwargs)
2023/8/24 17:08:06    File "/app/app/chain/__init__.py", line 90, in run_module
2023/8/24 17:08:06  Traceback (most recent call last):
2023/8/24 17:08:06  
2023/8/24 17:08:06  During handling of the above exception, another exception occurred:
2023/8/24 17:08:06  
2023/8/24 17:08:06  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023/8/24 17:08:06      raise JSONDecodeError("Expecting value", s, err.value) from None
2023/8/24 17:08:06    File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
2023/8/24 17:08:06                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/8/24 17:08:06      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023/8/24 17:08:06    File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
2023/8/24 17:08:06             ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/8/24 17:08:06      return _default_decoder.decode(s)
2023/8/24 17:08:06    File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
2023/8/24 17:08:06             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/8/24 17:08:06      return complexjson.loads(self.text, **kwargs)
2023/8/24 17:08:06    File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
2023/8/24 17:08:06  Traceback (most recent call last):
2023/8/24 17:08:06  【INFO】 media.py - 开始搜索媒体信息：恶鬼
```

**Comment by rotent** [comment]
同样的问题

**Comment by rotent** [comment]
【INFO】2023-08-29 14:53:17,118 - migration.py - Context impl SQLiteImpl.
【INFO】2023-08-29 14:53:17,119 - migration.py - Will assume non-transactional DDL.
【INFO】2023-08-29 14:53:18,220 - singleton.py - 用户认证成功！
【INFO】2023-08-29 14:53:18,451 - module.py - Moudle Loaded：DoubanModule
【INFO】2023-08-29 14:53:18,475 - module.py - Moudle Loaded：EmbyModule
【INFO】2023-08-29 14:53:18,475 - module.py - Moudle Loaded：FanartModule
【INFO】2023-08-29 14:53:18,476 - module.py - Moudle Loaded：FileTransferModule
【INFO】2023-08-29 14:53:18,481 - module.py - Moudle Loaded：FilterModule
【INFO】2023-08-29 14:53:18,481 - module.py - Moudle Loaded：IndexerModule
【INFO】2023-08-29 14:53:18,685 - module.py - Moudle Loaded：QbittorrentModule
【INFO】2023-08-29 14:53:18,687 - module.py - Moudle Loaded：SubtitleModule
【INFO】2023-08-29 14:53:18,687 - module.py - Moudle Loaded：TelegramModule
【INFO】2023-08-29 14:53:18,687 - module.py - Moudle Loaded：TheMovieDbModule
【INFO】2023-08-29 14:53:18,687 - module.py - Moudle Loaded：TheTvDbModule
【ERROR】2023-08-29 14:53:19,673 - __init__.py - 运行模块 tmdb_trending 出错：TheMovieDbModule - HTTPSConnectionPool(host='f6b4ef0e30fd06f9c01cf0d81d3d950f', port=443): Max retries exceeded with url: /3/trending/all/week?api_key=db55323b8d3e4154498498a75642b381&page=1&language=zh (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x146b12b3f350>: Failed to resolve 'f6b4ef0e30fd06f9c01cf0d81d3d950f' ([Errno -2] Name or service not known)"))
None
【INFO】2023-08-29 14:53:49,413 - media.py - 开始搜索媒体信息：恶鬼
【ERROR】2023-08-29 14:53:49,419 - __init__.py - 运行模块 search_medias 出错：TheMovieDbModule - HTTPSConnectionPool(host='f6b4ef0e30fd06f9c01cf0d81d3d950f', port=443): Max retries exceeded with url: /3/search/multi?api_key=db55323b8d3e4154498498a75642b381&query=%E6%81%B6%E9%AC%BC&page=1&language=zh (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x146b12bb7bd0>: Failed to resolve 'f6b4ef0e30fd06f9c01cf0d81d3d950f' ([Errno -2] Name or service not known)"))
None
【WARNING】2023-08-29 14:53:49,419 - media.py - 恶鬼 没有找到对应的媒体信息！

**Comment by rotent** [comment]
![272c2ae63ac1a5317b196edbf8897fd](https://github.com/jxxghp/MoviePilot/assets/93746829/8993ac4f-9ae4-406b-a39a-746139ef8895)

**Comment by rotent** [comment]
网络测试也都是通的，搜索就会404
