### ISSUE TITLE
[错误报告]: 下载转移失败，无法搜索

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#259]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.6

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/cf698e83-ae71-4fbf-8713-8e77a70bb90c)

### 发生问题时系统日志和配置文件

```bash
【WARNING】2023-08-24 20:03:00,915 - search.py - 馒头 - 紧急救援S01-S03 9-1-1 2018-2020 1080p WEB-DL x265 AC3￡cXcY@FRDS 标题不匹配
【INFO】2023-08-24 20:03:00,917 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 2018-2019 1080p WEB-DL x265 AC3￡cXcY@FRDS
【WARNING】2023-08-24 20:03:00,919 - search.py - 馒头 - 9-1-1 Lone Star S01 2020 1080p WEB-DL x265 AC3￡cXcY@FRDS 年份不匹配
【INFO】2023-08-24 20:03:00,921 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 S03 1080p AMZN WEB-DL DDP5.1 H.264-NTb
【INFO】2023-08-24 20:03:00,923 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1.S03E03.The.Searchers.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
【INFO】2023-08-24 20:03:00,925 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 S02 1080p AMZN WEB-DL DDP5.1 H.264-NTb
【INFO】2023-08-24 20:03:00,927 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 S02E18 This Life We Choose 1080p AMZN WEB-DL DDP5.1 H.264-NTb
【INFO】2023-08-24 20:03:00,930 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 S02E17 Careful What You Wish For 1080p AMZN WEB-DL DDP5.1 H.264-NTb
【INFO】2023-08-24 20:03:00,932 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 S02E16 Bobby Begins Again 1080p AMZN WEB-DL DDP5.1 H.264-NTb
【INFO】2023-08-24 20:03:00,934 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 S02E15 Oceans 9-1-1 1080p AMZN WEB-DL DDP5.1 H.264-NTb
【INFO】2023-08-24 20:03:00,936 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 S02E14 Broken 1080p AMZN WEB-DL DDP5.1 H.264-TVSmash
【INFO】2023-08-24 20:03:00,938 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 Season 2 WEBRip 1080p x264-l&YY
【INFO】2023-08-24 20:03:00,940 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 Season 1 WEBRip 1080p x264-l&YY
【INFO】2023-08-24 20:03:00,941 - search.py - 紧急呼救 匹配到资源：馒头 - 9-1-1 S01 1080p AMZN WEB-DL DDP5 1 H 264-NTb
【INFO】2023-08-24 20:03:00,942 - search.py - 匹配完成，共匹配到 78 个资源
【ERROR】2023-08-24 20:04:03,910 - base.py - Job "SubscribeChain.search (trigger: interval[0:05:00], next run at: 2023-08-24 20:09:03 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/chain/subscribe.py", line 189, in search
    subscribes = self.subscribeoper.list(state)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/subscribe_oper.py", line 55, in list
    return Subscribe.get_by_state(self._db, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/models/subscribe.py", line 70, in get_by_state
    return db.query(Subscribe).filter(Subscribe.state == state).all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2688, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2134, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 912, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: transferhistory.id
[SQL: INSERT INTO transferhistory (id, src, dest, mode, type, category, title, year, tmdbid, imdbid, tvdbid, doubanid, seasons, episodes, image, download_hash, status, errmsg, date, files) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (20361, '/volume1/Media1/downloads1/Tv Shows/一路朝阳.All.The.Way.To.The.Sun.2023.S01.2160p.HQ.WEB-DL.H265.AAC-HHWEB', '/volume1/Media1/连续剧/国产剧/一路朝阳 (2023)', 'link', '电视剧', '国产剧', '一路朝阳', '2023', 228085, None, 437622, None, 'S01', 'E16-E19', 'https://image.tmdb.org/t/p/w500/tdQBgUoRVTL9GYoLMtAl8yBGHRa.jpg', '391319a3f1215b802c47f88db33847d40f48b35c', 1, None, '2023-08-24 11:29:05', '["/volume1/Media1/downloads1/Tv Shows/\\u4e00\\u8def\\u671d\\u9633.All.The.Way.To.The.Sun.2023.S01.2160p.HQ.WEB-DL.H265.AAC-HHWEB/All.The.Way.To.The. ... (908 characters truncated) ... \\u671d\\u9633.All.The.Way.To.The.Sun.2023.S01.2160p.HQ.WEB-DL.H265.AAC-HHWEB/All.The.Way.To.The.Sun.2023.S01E15.2160p.HQ.WEB-DL.H265.AAC-HHWEB.mp4"]')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
【INFO】2023-08-24 20:04:03,922 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2023-08-24 20:04:04,237 - transfer.py - 获取到 1 个已完成的下载任务
【ERROR】2023-08-24 20:04:04,242 - base.py - Job "下载文件整理 (trigger: interval[0:05:00], next run at: 2023-08-24 20:09:03 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/chain/transfer.py", line 76, in process
    downloadhis: DownloadHistory = self.downloadhis.get_by_hash(torrent.hash)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/downloadhistory_oper.py", line 25, in get_by_hash
    return DownloadHistory.get_by_hash(self._db, download_hash)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/models/downloadhistory.py", line 43, in get_by_hash
    return db.query(DownloadHistory).filter(DownloadHistory.download_hash == download_hash).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2743, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2134, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 912, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: transferhistory.id
[SQL: INSERT INTO transferhistory (id, src, dest, mode, type, category, title, year, tmdbid, imdbid, tvdbid, doubanid, seasons, episodes, image, download_hash, status, errmsg, date, files) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (20361, '/volume1/Media1/downloads1/Tv Shows/一路朝阳.All.The.Way.To.The.Sun.2023.S01.2160p.HQ.WEB-DL.H265.AAC-HHWEB', '/volume1/Media1/连续剧/国产剧/一路朝阳 (2023)', 'link', '电视剧', '国产剧', '一路朝阳', '2023', 228085, None, 437622, None, 'S01', 'E16-E19', 'https://image.tmdb.org/t/p/w500/tdQBgUoRVTL9GYoLMtAl8yBGHRa.jpg', '391319a3f1215b802c47f88db33847d40f48b35c', 1, None, '2023-08-24 11:29:05', '["/volume1/Media1/downloads1/Tv Shows/\\u4e00\\u8def\\u671d\\u9633.All.The.Way.To.The.Sun.2023.S01.2160p.HQ.WEB-DL.H265.AAC-HHWEB/All.The.Way.To.The. ... (908 characters truncated) ... \\u671d\\u9633.All.The.Way.To.The.Sun.2023.S01.2160p.HQ.WEB-DL.H265.AAC-HHWEB/All.The.Way.To.The.Sun.2023.S01E15.2160p.HQ.WEB-DL.H265.AAC-HHWEB.mp4"]')]
(Background on this error at: https://sqlalche.me/e/20/gkpj) (Background on this error at: https://sqlalche.me/e/20/7s2a)
```

**Comment by paysenyu** [comment]
> 

再次pull  蓝光还是失败
