### ISSUE TITLE
[错误报告]: 部分文件自动订阅下载完成后整理出错。

### ISSUE THREAD

**Issue by yangc-vip** [jxxghp/MoviePilot#2966]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.0-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

部分文件自动整理与手动整理均出现同样出错，硬连接视频文件会生成，但不生成刮削图片与nfo文件，已附上报错日志。

### 发生问题时系统日志和配置文件

```bash
INFO:    transfer.py - 开始整理下载器中已经完成下载的文件 ...
INFO:    transfer.py - 获取到 1 个已完成的下载任务
INFO:    themoviedb - 10257 TMDB识别结果：电影 千机变Ⅱ花都大战 (2004)
INFO:    transfer.py - 正在整理 1 个文件...
INFO:    transfer.py - 千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer.mkv 识别为：电影 千机变Ⅱ花都大战 (2004)
INFO:    filemanager - 获取整理目标路径：【local】/data/Movies/电影
INFO:    filemanager - 正在整理文件：【local】/data/Down/电影/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer.mkv 到 【local】/data/Movies/电影/千机变Ⅱ花都大战 (2004)/千机变Ⅱ花都大战 (2004) - 1080p HEVC 10bit PTer.mkv
ERROR:   chain - 运行模块 FileManagerModule.transfer 出错：'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 112, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 352, in transfer
    return self.transfer_media(fileitem=fileitem,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 977, in transfer_media
    new_item, err_msg = self.__transfer_file(fileitem=fileitem,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 780, in __transfer_file
    self.__transfer_other_files(fileitem=fileitem,
  File "/app/app/modules/filemanager/__init__.py", line 524, in __transfer_other_files
    state, errmsg = self.__transfer_subtitles(fileitem=fileitem,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 581, in __transfer_subtitles
    if f".{sub_item.extension.lower()}" not in settings.RMT_SUBEXT:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

ERROR:   transfer.py - 文件整理模块运行失败
INFO:    systemnotification - Sending notification: 【文件整理发生了错误】 - 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 112, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 352, in transfer
    return self.transfer_media(fileitem=fileitem,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 977, in transfer_media
    new_item, err_msg = self.__transfer_file(fileitem=fileitem,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 780, in __transfer_file
    self.__transfer_other_files(fileitem=fileitem,
  File "/app/app/modules/filemanager/__init__.py", line 524, in __transfer_other_files
    state, errmsg = self.__transfer_subtitles(fileitem=fileitem,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 581, in __transfer_subtitles
    if f".{sub_item.extension.lower()}" not in settings.RMT_SUBEXT:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

INFO:    transfer.py - 所有下载器中下载完成的文件已整理完成
INFO:    chain - 发送消息：channel=None，source=None,title=【文件整理发生了错误】, text='NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 112, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 352, in transfer
    return self.transfer_media(fileitem=fileitem,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 977, in transfer_media
    new_item, err_msg = self.__transfer_file(fileitem=fileitem,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 780, in __transfer_file
    self.__transfer_other_files(fileitem=fileitem,
  File "/app/app/modules/filemanager/__init__.py", line 524, in __transfer_other_files
    state, errmsg = self.__transfer_subtitles(fileitem=fileitem,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filemanager/__init__.py", line 581, in __transfer_subtitles
    if f".{sub_item.extension.lower()}" not in settings.RMT_SUBEXT:
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
，userid=None
```

**Comment by yangc-vip** [comment]
又重新测了一下。目前测试应该是因为目录结构的原因。供参考（已有两部影片手动添加一层目录后均成功能整理入库）

失败目录结构： /data/Down/电影/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer.mkv
更改后成功整理的目录结构：/data/Down/电影/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer.mkv

以下是更换目录后的成功日志：
INFO:    transfer.py - 手动整理：/data/Down/电影/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer/ ...
INFO:     10.10.10.190:0 - "GET /api/v1/system/progress/filetransfer HTTP/1.1" 200 OK
INFO:    transfer.py - 正在整理 1 个文件...
INFO:    themoviedb - The Twins Effect Ii 使用TMDB识别缓存：千机变Ⅱ花都大战
INFO:    themoviedb - The Twins Effect Ii TMDB识别结果：电影 千机变Ⅱ花都大战 (2004) 10257
INFO:    media.py - 千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer.mkv 识别到媒体信息：电影 千机变Ⅱ花都大战 (2004)
INFO:    transfer.py - 千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer.mkv 识别为：电影 千机变Ⅱ花都大战 (2004)
INFO:    filemanager - 获取整理目标路径：【local】/data/Movies/电影
INFO:    filemanager - 正在整理文件：【local】/data/Down/电影/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer.mkv 到 【local】/data/Movies/电影/千机变Ⅱ花都大战 (2004)/千机变Ⅱ花都大战 (2004) - 1080p HEVC 10bit PTer.mkv
INFO:    filemanager - 文件 /data/Down/电影/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer.mkv 整理成功
INFO:    chain - 发送消息：channel=None，source=None,title=千机变Ⅱ花都大战 (2004)  已入库, text=评分：5.1，类型：电影，类别：电影，质量： BluRay 1080p，共1个文件，大小：5.86G，userid=None
INFO:    transfer.py - /data/Down/电影/千机变2：花都大战.The.Twins.Effect.II.2004.BluRay.1080p.HEVC.10bit.2Audio.MiniFHD-XPcl@PTer/ 整理完成，共 1 个文件，失败 0 个，跳过 0 个
INFO:    media.py - 开始刮削：/data/Movies/电影/千机变Ⅱ花都大战 (2004) ...
INFO:     10.10.10.190:0 - "POST /api/v1/transfer/manual HTTP/1.1" 200 OK
INFO:    emby.py - 开始刷新Emby媒体库...
INFO:    media.py - 开始刮削：/data/Movies/电影/千机变Ⅱ花都大战 (2004)/千机变Ⅱ花都大战 (2004) - 1080p HEVC 10bit PTer.mkv ...
INFO:    media.py - 正在生成电影nfo：千机变Ⅱ花都大战 (2004) - 千机变Ⅱ花都大战 (2004) - 1080p HEVC 10bit PTer.mkv
INFO:    media.py - 保存文件：【local】/data/Movies/电影/千机变Ⅱ花都大战 (2004)/千机变Ⅱ花都大战 (2004) - 1080p HEVC 10bit PTer.nfo
INFO:    media.py - 千机变Ⅱ花都大战 (2004) - 1080p HEVC 10bit PTer.mkv 刮削完成
INFO:    media.py - 正在下载图片：https://image.tmdb.org/t/p/original/aDgysYfiPZBgGSaOjxYooYSvNxG.jpg ...
INFO:     10.10.10.190:0 - "POST /api/v1/storage/list?sort=time HTTP/1.1" 200 OK
INFO:    media.py - 保存文件：【local】/data/Movies/电影/千机变Ⅱ花都大战 (2004)/backdrop.jpg
INFO:    media.py - 正在下载图片：https://image.tmdb.org/t/p/original/oRSMIg7QyullI9mKxpVBKy7m8Us.jpg ...
INFO:    media.py - 保存文件：【local】/data/Movies/电影/千机变Ⅱ花都大战 (2004)/poster.jpg
INFO:    media.py - 正在下载图片：https://assets.fanart.tv/fanart/movies/10257/hdmovielogo/the-twins-effect-ii-5cd111641de60.png ...
INFO:     10.10.10.190:0 - "GET /api/v1/system/logging HTTP/1.1" 200 OK
INFO:    media.py - 保存文件：【local】/data/Movies/电影/千机变Ⅱ花都大战 (2004)/logo.png
INFO:    media.py - 正在下载图片：https://assets.fanart.tv/fanart/movies/10257/moviethumb/the-twins-effect-ii-64729c5b903fe.jpg ...
INFO:    media.py - 保存文件：【local】/data/Movies/电影/千机变Ⅱ花都大战 (2004)/thumb.jpg
INFO:    media.py - 千机变Ⅱ花都大战 (2004) 刮削完成

**Comment by yangc-vip** [comment]
又测试了一遍。问题依旧。同样的UNRAID环境下同样的文件1.X系列整理正常。2.0系列出错，奇怪。我再观察观察。
