### ISSUE TITLE
[错误报告]: RCLONE转移时报错

### ISSUE THREAD

**Issue by shixiaolong777** [jxxghp/MoviePilot#2983]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

设置rclone路径的时候可以选到，但转移时报错
如果从/里选择路径/视频/电视剧，但显示出的路径是/视频电视剧，依然无法转移

### 发生问题时系统日志和配置文件

```bash
INFO:    filemanager - 获取整理目标路径：【rclone】/视频电视剧

ERROR:   chain - 运行模块 FileManagerModule.transfer 出错：Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

Traceback (most recent call last):

  File "/app/app/chain/__init__.py", line 112, in run_module

    result = func(*args, **kwargs)

             ^^^^^^^^^^^^^^^^^^^^^

  File "/app/app/modules/filemanager/__init__.py", line 368, in transfer

    return self.transfer_media(fileitem=fileitem,

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/app/modules/filemanager/__init__.py", line 929, in transfer_media

    new_file = self.get_rename_path(

               ^^^^^^^^^^^^^^^^^^^^^

  File "/app/app/modules/filemanager/__init__.py", line 1120, in get_rename_path

    template = Template(template_string)

               ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1211, in __new__

    return env.from_string(source, template_class=cls)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1108, in from_string

    return cls.from_code(self, self.compile(source), gs, None)

                               ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile

    self.handle_exception(source=source_hint)

  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception

    raise rewrite_traceback_stack(source=source)

  File "<unknown>", line 1, in template

jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

ERROR:   transfer.py - 文件整理模块运行失败
```

**Comment by NASA0719** [comment]
你修改过电视剧重命名格式？这报错看着是重命名格式错误

**Comment by shixiaolong777** [comment]
自定义名称识别是对的，但不论手动还是自动转移都没重命名
还有个问题 路径是/电视剧    上传一个小巷人家（2024） 云盘里直接变成 根目录是/电视剧小巷人家（2024） 中间少一个/
