### ISSUE TITLE
[错误报告]: 1、站点数据统计报错：exception in asgi application 2、显示downloadingmsg-未配置管理员用户和qb、tr配置不完整

### ISSUE THREAD

**Issue by liuyie** [jxxghp/MoviePilot#2992]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

1、mp-v2初安装：站点数据统计正常，运行一段时间或重启后就无数据显示了。在日志报错exception in asgi application 。具体如下！
2、mp-v2安装后显示qb和tr配置不完整，但qb和tr用mp调用：下载、转种、辅种、二级分类都是正常的，不知道是什么原因？

### 发生问题时系统日志和配置文件

```bash
1、以下是站点数据统计的日志：
2024/11/02 08:05:44	stdout	TypeError: unsupported operand type(s) for -: 'str' and 'str'
2024/11/02 08:05:44	stdout	            ~~~~~~~~~~^~~~~~~~~~~
2024/11/02 08:05:44	stdout	    d = {k: d1.get(k) - d2.get(k) for k in d1
2024/11/02 08:05:44	stdout	  File "/app/app/plugins/sitestatistic/__init__.py", line 257, in <dictcomp>
2024/11/02 08:05:44	stdout	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    d = {k: d1.get(k) - d2.get(k) for k in d1
2024/11/02 08:05:44	stdout	  File "/app/app/plugins/sitestatistic/__init__.py", line 257, in __sub_data
2024/11/02 08:05:44	stdout	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    inc = __sub_data(data.to_dict(), yesterday_data.to_dict() if yesterday_data else None)
2024/11/02 08:05:44	stdout	  File "/app/app/plugins/sitestatistic/__init__.py", line 565, in __get_total_elements
2024/11/02 08:05:44	stdout	               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    'content': self.__get_total_elements(
2024/11/02 08:05:44	stdout	  File "/app/app/plugins/sitestatistic/__init__.py", line 692, in get_dashboard
2024/11/02 08:05:44	stdout	                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    dashboard: Tuple = plugin.get_dashboard(key=key, **kwargs)
2024/11/02 08:05:44	stdout	  File "/app/app/core/plugin.py", line 441, in get_plugin_dashboard
2024/11/02 08:05:44	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    return PluginManager().get_plugin_dashboard(plugin_id, user_agent=user_agent)
2024/11/02 08:05:44	stdout	  File "/app/app/api/endpoints/plugin.py", line 256, in plugin_dashboard
2024/11/02 08:05:44	stdout	             ^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    result = context.run(func, *args)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 943, in run
2024/11/02 08:05:44	stdout	           ^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    return await future
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
2024/11/02 08:05:44	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    return await get_async_backend().run_sync_in_worker_thread(
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024/11/02 08:05:44	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    return await anyio.to_thread.run_sync(func, *args)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2024/11/02 08:05:44	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    return await run_in_threadpool(dependant.call, **values)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
2024/11/02 08:05:44	stdout	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    raw_response = await run_endpoint_function(
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
2024/11/02 08:05:44	stdout	               ^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    response = await func(request)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2024/11/02 08:05:44	stdout	    await self.app(scope, receive, send)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2024/11/02 08:05:44	stdout	    await route.handle(scope, receive, send)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2024/11/02 08:05:44	stdout	    await self.app(scope, receive, send)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024/11/02 08:05:44	stdout	    raise e
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024/11/02 08:05:44	stdout	    await self.app(scope, receive, sender)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024/11/02 08:05:44	stdout	    raise exc
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024/11/02 08:05:44	stdout	    await self.app(scope, receive, send)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024/11/02 08:05:44	stdout	    await self.app(scope, receive, _send)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024/11/02 08:05:44	stdout	    raise exc
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024/11/02 08:05:44	stdout	    await self.middleware_stack(scope, receive, send)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2024/11/02 08:05:44	stdout	    await super().__call__(scope, receive, send)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2024/11/02 08:05:44	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    return await self.app(scope, receive, send)
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024/11/02 08:05:44	stdout	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/02 08:05:44	stdout	    result = await app(  # type: ignore[func-returns-value]
2024/11/02 08:05:44	stdout	  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024/11/02 08:05:44	stdout	Traceback (most recent call last):
2024/11/02 08:05:44	stdout	[31mERROR[0m:    Exception in ASGI application

2、以下是qb和tr日志显示的错误：见下面的截图
a、显示qb和tr配置不完整，但在yaml和web内都是配置完整的。域名位置也试了加和不加http均报错
     - QB_HOST=http://192.168.110.44:8085  
      - QB_USER=
      - QB_PASSWORD=
      - QB_CATEGORY=false                                                  
      - QB_SEQUENTIAL=true                                                
      - QB_FORCE_RESUME=true     
      

      - TR_HOST=http://192.168.110.44:9091  
      - TR_USER=admin                                                     
      - TR_PASSWORD=adminadmin 

b、另就是显示：         downloadingmsg- 未配置管理员帐户。

**Comment by liuyie** [comment]
![屏幕截图_2-11-2024_9217_liuyie myds me](https://github.com/user-attachments/assets/bb976cbf-ad93-4936-852e-6b7d09bb1913)
![屏幕截图_2-11-2024_92259_liuyie myds me](https://github.com/user-attachments/assets/6630b390-ba0e-44a8-b422-1fcb748ab497)

**Comment by liuyie** [comment]
谢谢

**Comment by liuyie** [comment]
![屏幕截图_2-11-2024_93842_liuyie myds me](https://github.com/user-attachments/assets/2f23e1c8-5c71-4df5-b5f5-4d1ea6ae845a)
![屏幕截图_2-11-2024_94441_liuyie myds me](https://github.com/user-attachments/assets/cc6c0e41-1abe-4123-a126-c6407c25a9fe)
![屏幕截图_2-11-2024_9446_liuyie myds me](https://github.com/user-attachments/assets/457cc273-8cc6-41fd-8e0d-e0119f8b9021)
![屏幕截图_2-11-2024_94426_liuyie myds me](https://github.com/user-attachments/assets/b3475302-f6b5-4998-9fc3-d8dc87c71170)

**Comment by liuyie** [comment]
![屏幕截图_2-11-2024_93546_liuyie myds me](https://github.com/user-attachments/assets/2a7337c3-e3b7-4419-aa86-c41e8f2ae46a)
![屏幕截图_2-11-2024_93842_liuyie myds me](https://github.com/user-attachments/assets/932481c8-36fe-483c-91a0-99d11c4a9b63)
![屏幕截图_2-11-2024_94351_liuyie myds me](https://github.com/user-attachments/assets/2a732e88-5524-421d-92dc-58a5834207a0)
![屏幕截图_2-11-2024_94441_liuyie myds me](https://github.com/user-attachments/assets/cae1329b-b8b2-42a6-9de6-534ba92b0eb3)
![屏幕截图_2-11-2024_9446_liuyie myds me](https://github.com/user-attachments/assets/dd353d59-a500-4af9-a4a2-2ab9bf967e29)
![屏幕截图_2-11-2024_94426_liuyie myds me](https://github.com/user-attachments/assets/83a66bf1-c326-4d44-8060-fcf75a64aca8)

**Comment by liuyie** [comment]
谢谢
