### ISSUE TITLE
[错误报告]: v2版本站点数据统计插件运行到TorrentLeech 刷新数据时保存然后终止运行了

### ISSUE THREAD

**Issue by lzcer** [jxxghp/MoviePilot#3019]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

1、由于不能配置运行时间，选择了每日数据，但是第二天并没有更新数据，是根据系统启动时间来计算的？间隔24小时吗？

2、手动执行了一次，发现获取TorrentLeech 站点数据的时候报错了，然后终止了运行。是一个数值转换错误。

3、IPT 未找到站点解析器

4、v1版本中可以使用的自定义索引站点配置在v2中无法使用吗，不清楚是不适用了还是没有处理这个逻辑，所以一起提交了。

### 发生问题时系统日志和配置文件

```bash
value is not a valid integer (type=type_error.integer)
userid
pydantic.error_wrappers.ValidationError: 1 validation error for SiteUserData
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
           ^^^^^^^^^^^^^
    return SiteUserData(
  File "/app/app/modules/indexer/__init__.py", line 260, in refresh_userdata
             ^^^^^^^^^^^^^^^^^^^^^
    result = func(*args, **kwargs)
  File "/app/app/chain/__init__.py", line 112, in run_module
Traceback (most recent call last):
  value is not a valid integer (type=type_error.integer)
userid
【ERROR】2024-11-07 08:37:30,128 - chain - 运行模块 IndexerModule.refresh_userdata 出错：1 validation error for SiteUserData
【INFO】2024-11-07 08:37:25,843 - indexer - 站点 TorrentLeech 开始以 TorrentLeech 模型解析数据...
【WARNING】2024-11-07 08:37:16,025 - indexer - 站点  海豹 未找到站点解析器，schema：None
【WARNING】2024-11-07 08:46:48,752 - indexer - 站点  IPT 未找到站点解析器，schema：Ipt
###########################自定义索引站点问题################################
自定义索引站点插件配置内容：
greatposterwall.com|ewogICAgImlkIjogImdyZWF0cG9zdGVyd2FsbCIsCiAgICAibmFtZSI6ICLmtbfosbkiLAogICAgImRvbWFpbiI6ICJodHRwczovL2dyZWF0cG9zdGVyd2FsbC5jb20iLAogICAgImV4dF9kb21haW5zIjogW10sCiAgICAiZW5jb2RpbmciOiAiVVRGLTgiLAogICAgInB1YmxpYyI6IGZhbHNlLAogICAgInNlYXJjaCI6IHsKICAgICAgInBhdGhzIjogWwogICAgICAgIHsKICAgICAgICAgICJwYXRoIjogInRvcnJlbnRzLnBocCIsCiAgICAgICAgICAibWV0aG9kIjogImdldCIKICAgICAgICB9CiAgICAgIF0sCiAgICAgICJwYXJhbXMiOiB7CiAgICAgICAgInNlYXJjaHN0ciI6ICJ7a2V5d29yZH0iLAogICAgICAgICJzZWFyY2hzdWJtaXQiOiAxLAogICAgICAgICJncm91cF9yZXN1bHRzIjogMAogICAgICB9LAogICAgICAiYmF0Y2giOiB7CiAgICAgICAgImRlbGltaXRlciI6ICIgIiwKICAgICAgICAic3BhY2VfcmVwbGFjZSI6ICJfIgogICAgICB9CiAgICB9LAogICAgInRvcnJlbnRzIjogewogICAgICAibGlzdCI6IHsKICAgICAgICAic2VsZWN0b3IiOiAiI3RvcnJlbnRfdGFibGUgPiB0ci5UYWJsZVRvcnJlbnQtcm93VGl0bGUiCiAgICAgIH0sCiAgICAgICJmaWVsZHMiOiB7CiAgICAgICAgImlkIjogewogICAgICAgICAgInNlbGVjdG9yIjogImFbaHJlZio9XCJ0b3JyZW50cy5waHA/aWQ9XCJdIiwKICAgICAgICAgICJhdHRyaWJ1dGUiOiAiaHJlZiIsCiAgICAgICAgICAiZmlsdGVycyI6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICJuYW1lIjogInJlX3NlYXJjaCIsCiAgICAgICAgICAgICAgImFyZ3MiOiBbCiAgICAgICAgICAgICAgICAidG9ycmVudGlkXFxkKyIsCiAgICAgICAgICAgICAgICAwCiAgICAgICAgICAgICAgXQogICAgICAgICAgICB9CiAgICAgICAgICBdCiAgICAgICAgfSwKICAgICAgICAidGl0bGVfZGVmYXVsdCI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJhW2hyZWYqPVwidG9ycmVudHMucGhwP2lkPVwiXSIsCiAgICAgICAgICAiYXR0cmlidXRlIjogImRhdGEtdG9vbHRpcCIKICAgICAgICB9LAogICAgICAgICJ0aXRsZV9vcHRpb25hbCI6IHsKICAgICAgICAgICJvcHRpb25hbCI6IHRydWUsCiAgICAgICAgICAic2VsZWN0b3IiOiAiYVtocmVmKj1cInRvcnJlbnRzLnBocD9pZD1cIl0iLAogICAgICAgICAgImF0dHJpYnV0ZSI6ICJkYXRhLXRvb2x0aXAiCiAgICAgICAgfSwKICAgICAgICAidGl0bGUiOiB7CiAgICAgICAgICAidGV4dCI6ICJ7JSBpZiBmaWVsZHNbJ3RpdGxlX29wdGlvbmFsJ10gJX17eyBmaWVsZHNbJ3RpdGxlX29wdGlvbmFsJ10gfX17JSBlbHNlICV9e3sgZmllbGRzWyd0aXRsZV9kZWZhdWx0J10gfX17JSBlbmRpZiAlfSIKICAgICAgICB9LAogICAgICAgICJkZXRhaWxzIjogewogICAgICAgICAgInNlbGVjdG9yIjogImFbaHJlZio9XCJ0b3JyZW50cy5waHA/aWQ9XCJdIiwKICAgICAgICAgICJhdHRyaWJ1dGUiOiAiaHJlZiIKICAgICAgICB9LAogICAgICAgICJkb3dubG9hZCI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJhW2hyZWYqPVwidG9ycmVudHMucGhwP2FjdGlvbj1kb3dubG9hZCZpZD1cIl0iLAogICAgICAgICAgImF0dHJpYnV0ZSI6ICJocmVmIgogICAgICAgIH0sCiAgICAgICAgImltZGJpZCI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJkaXYuaW1kYl8xMDAgPiBhIiwKICAgICAgICAgICJhdHRyaWJ1dGUiOiAiaHJlZiIsCiAgICAgICAgICAiZmlsdGVycyI6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICJuYW1lIjogInJlX3NlYXJjaCIsCiAgICAgICAgICAgICAgImFyZ3MiOiBbCiAgICAgICAgICAgICAgICAidHRcXGQrIiwKICAgICAgICAgICAgICAgIDAKICAgICAgICAgICAgICBdCiAgICAgICAgICAgIH0KICAgICAgICAgIF0KICAgICAgICB9LAogICAgICAgICJkYXRlX2VsYXBzZWQiOiB7CiAgICAgICAgICAic2VsZWN0b3IiOiAidGQuVGFibGUtY2VsbCA+IHNwYW4udGxfZnJlZSIsCiAgICAgICAgICAib3B0aW9uYWwiOiB0cnVlCiAgICAgICAgfSwKICAgICAgICAiZGF0ZV9hZGRlZCI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJ0ZC5UYWJsZVRvcnJlbnQtY2VsbFN0YXRUaW1lID4gc3BhbiIsCiAgICAgICAgICAib3B0aW9uYWwiOiB0cnVlCiAgICAgICAgfSwKICAgICAgICAic2l6ZSI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJ0ZC5UYWJsZVRvcnJlbnQtY2VsbFN0YXRTaXplIgogICAgICAgIH0sCiAgICAgICAgInNlZWRlcnMiOiB7CiAgICAgICAgICAic2VsZWN0b3IiOiAidGQuVGFibGVUb3JyZW50LWNlbGxTdGF0U2VlZGVycyIKICAgICAgICB9LAogICAgICAgICJsZWVjaGVycyI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJ0ZC5UYWJsZVRvcnJlbnQtY2VsbFN0YXRMZWVjaGVycyIKICAgICAgICB9LAogICAgICAgICJncmFicyI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJ0ZC5UYWJsZVRvcnJlbnQtY2VsbFN0YXRTbmF0Y2hlcyIKICAgICAgICB9LAogICAgICAgICJkb3dubG9hZHZvbHVtZWZhY3RvciI6IHsKICAgICAgICAgICJjYXNlIjogewogICAgICAgICAgICAic3Bhbi50bF9mcmVlIjogMCwKICAgICAgICAgICAgInNwYW4udHdvX2ZvdXJ0aF9vZmYiOiAwLjUsCiAgICAgICAgICAgICIqIjogMQogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgInVwbG9hZHZvbHVtZWZhY3RvciI6IHsKICAgICAgICAgICJjYXNlIjogewogICAgICAgICAgICAiKiI6IDEKICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJsYWJlbHMiOiB7CiAgICAgICAgICAic2VsZWN0b3IiOiAic3Bhbi5Ub3JyZW50VGl0bGUgPiBzcGFuOm50aC1vZi10eXBlKDJuKzEpIgogICAgICAgIH0KICAgICAgfQogICAgfQogIH0=
```

**Comment by lzcer** [comment]
刚刚数了下，TorrentLeech 刚好是最后一个执行的站点，所以不太清楚是不是终止了，但是由于tg没有收到通知，而且日志戛然而止，推测还是终止了的。

**Comment by lzcer** [comment]
点错了。。。。

**Comment by lzcer** [comment]
补充：猫站未获取到保种信息，其他信息获取正常
做种数	做种体积为0
