### ISSUE TITLE
[错误报告]: 订阅列表无法加载

### ISSUE THREAD

**Issue by yuan488** [jxxghp/MoviePilot#3068]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v2.0.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅列表无法加载，但日志无报错
![image](https://github.com/user-attachments/assets/1e5cfb9b-5f6f-4090-bd5e-ae8e1a1c53f9)

### 发生问题时系统日志和配置文件

```bash
2024/11/11 22:08:57  [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/message HTTP/1.1[0m" [32m200 OK[0m
```

**Comment by yuan488** [comment]
> ### 确认
> * [x]  我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
> * [x]  我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经修改标题，将标题中的 描述 替换为我遇到的问题。
> 
> ### 当前程序版本
> v2.0.2
> 
> ### 运行环境
> Docker
> 
> ### 问题类型
> 主程序运行问题
> 
> ### 问题描述
> 订阅列表无法加载 ![image](https://private-user-images.githubusercontent.com/69119229/384953268-1e5cfb9b-5f6f-4090-bd5e-ae8e1a1c53f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjMzOTIsIm5iZiI6MTczMTQyMzA5MiwicGF0aCI6Ii82OTExOTIyOS8zODQ5NTMyNjgtMWU1Y2ZiOWItNWY2Zi00MDkwLWJkNWUtYWU4ZTFhMWM1M2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE0NTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMzQyZDNhOWU3OWU1NzA0MjI4ZmE5YTg4NWRkZjIxYTJiNGFhOGVjZWI0ZDViYTRjNjBiMmEyMWVhN2VkMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TdV92F4wMVGIvVtX441S71lPYAH96vvU-Ja4AAdI_1w)
> 
> ### 发生问题时系统日志和配置文件
> ```shell
> `2024-11-12T14:50:12.027150762Z pydantic.error_wrappers.ValidationError: 2 validation errors for Subscribe
2024-11-12T14:50:12.027155853Z response -> 1 -> sites
2024-11-12T14:50:12.027160926Z   value is not a valid list (type=type_error.list)
2024-11-12T14:50:12.027165839Z response -> 2 -> sites
2024-11-12T14:50:12.027170863Z   value is not a valid list (type=type_error.list)
2024-11-12T14:50:12.915739265Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/global HTTP/1.1[0m" [32m200 OK[0m
2024-11-12T14:50:12.997066199Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/setting/UserCustomCSS HTTP/1.1[0m" [32m200 OK[0m
2024-11-12T14:50:13.000084146Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/subscribe/ HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024-11-12T14:50:13.002092867Z [31mERROR[0m:    Exception in ASGI application
2024-11-12T14:50:13.002154684Z Traceback (most recent call last):
2024-11-12T14:50:13.002167294Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024-11-12T14:50:13.002175359Z     result = await app(  # type: ignore[func-returns-value]
2024-11-12T14:50:13.002181748Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:13.002187627Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-11-12T14:50:13.002193604Z     return await self.app(scope, receive, send)
2024-11-12T14:50:13.002199177Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:13.002205703Z   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2024-11-12T14:50:13.002212218Z     await super().__call__(scope, receive, send)
2024-11-12T14:50:13.002218068Z   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2024-11-12T14:50:13.002223910Z     await self.middleware_stack(scope, receive, send)
2024-11-12T14:50:13.002230205Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-11-12T14:50:13.002236690Z     raise exc
2024-11-12T14:50:13.002242623Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-11-12T14:50:13.002253806Z     await self.app(scope, receive, _send)
2024-11-12T14:50:13.002260080Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-11-12T14:50:13.002265971Z     await self.app(scope, receive, send)
2024-11-12T14:50:13.002271604Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-11-12T14:50:13.002277806Z     raise exc
2024-11-12T14:50:13.002283675Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-11-12T14:50:13.002290148Z     await self.app(scope, receive, sender)
2024-11-12T14:50:13.002323736Z   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024-11-12T14:50:13.002334074Z     raise e
2024-11-12T14:50:13.002340022Z   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024-11-12T14:50:13.002345771Z     await self.app(scope, receive, send)
2024-11-12T14:50:13.002351158Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2024-11-12T14:50:13.002356823Z     await route.handle(scope, receive, send)
2024-11-12T14:50:13.002362326Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2024-11-12T14:50:13.002369610Z     await self.app(scope, receive, send)
2024-11-12T14:50:13.002389441Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2024-11-12T14:50:13.002396943Z     response = await func(request)
2024-11-12T14:50:13.002402730Z                ^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:13.002408106Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 255, in app
2024-11-12T14:50:13.002413898Z     content = await serialize_response(
2024-11-12T14:50:13.002419352Z               ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:13.002424870Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 141, in serialize_response
2024-11-12T14:50:13.002430515Z     raise ValidationError(errors, field.type_)
2024-11-12T14:50:13.002436040Z pydantic.error_wrappers.ValidationError: 2 validation errors for Subscribe
2024-11-12T14:50:13.002441704Z response -> 1 -> sites
2024-11-12T14:50:13.002447528Z   value is not a valid list (type=type_error.list)
2024-11-12T14:50:13.002452922Z response -> 2 -> sites
2024-11-12T14:50:13.002458470Z   value is not a valid list (type=type_error.list)
2024-11-12T14:50:15.967680506Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/message HTTP/1.1[0m" [32m200 OK[0m
2024-11-12T14:50:31.961732115Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/global HTTP/1.1[0m" [32m200 OK[0m
2024-11-12T14:50:32.043592785Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/setting/UserCustomCSS HTTP/1.1[0m" [32m200 OK[0m
2024-11-12T14:50:32.045590432Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/subscribe/ HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024-11-12T14:50:32.046923356Z [31mERROR[0m:    Exception in ASGI application
2024-11-12T14:50:32.046943228Z Traceback (most recent call last):
2024-11-12T14:50:32.046948658Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024-11-12T14:50:32.046952825Z     result = await app(  # type: ignore[func-returns-value]
2024-11-12T14:50:32.046956790Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:32.046960207Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-11-12T14:50:32.046963726Z     return await self.app(scope, receive, send)
2024-11-12T14:50:32.046966849Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:32.046969915Z   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2024-11-12T14:50:32.046973210Z     await super().__call__(scope, receive, send)
2024-11-12T14:50:32.046976398Z   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2024-11-12T14:50:32.046998892Z     await self.middleware_stack(scope, receive, send)
2024-11-12T14:50:32.047003597Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-11-12T14:50:32.047007508Z     raise exc
2024-11-12T14:50:32.047010952Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-11-12T14:50:32.047014249Z     await self.app(scope, receive, _send)
2024-11-12T14:50:32.047017407Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-11-12T14:50:32.047020607Z     await self.app(scope, receive, send)
2024-11-12T14:50:32.047023800Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-11-12T14:50:32.047027097Z     raise exc
2024-11-12T14:50:32.047030359Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-11-12T14:50:32.047033652Z     await self.app(scope, receive, sender)
2024-11-12T14:50:32.047036810Z   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024-11-12T14:50:32.047040055Z     raise e
2024-11-12T14:50:32.047045329Z   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024-11-12T14:50:32.047048565Z     await self.app(scope, receive, send)
2024-11-12T14:50:32.047051711Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2024-11-12T14:50:32.047054927Z     await route.handle(scope, receive, send)
2024-11-12T14:50:32.047058054Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2024-11-12T14:50:32.047062020Z     await self.app(scope, receive, send)
2024-11-12T14:50:32.047065210Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2024-11-12T14:50:32.047087296Z     response = await func(request)
2024-11-12T14:50:32.047091760Z                ^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:32.047094972Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 255, in app
2024-11-12T14:50:32.047098291Z     content = await serialize_response(
2024-11-12T14:50:32.047101311Z               ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:32.047104489Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 141, in serialize_response
2024-11-12T14:50:32.047107719Z     raise ValidationError(errors, field.type_)
2024-11-12T14:50:32.047110797Z pydantic.error_wrappers.ValidationError: 2 validation errors for Subscribe
2024-11-12T14:50:32.047113966Z response -> 1 -> sites
2024-11-12T14:50:32.047117148Z   value is not a valid list (type=type_error.list)
2024-11-12T14:50:32.047126528Z response -> 2 -> sites
2024-11-12T14:50:32.047130611Z   value is not a valid list (type=type_error.list)
2024-11-12T14:50:35.014226974Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/message HTTP/1.1[0m" [32m200 OK[0m
2024-11-12T14:50:42.612967267Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/logging HTTP/1.1[0m" [32m200 OK[0m
`
> ```

**Comment by yuan488** [comment]
```
2024-11-12T14:50:31.961732115Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/global HTTP/1.1[0m" [32m200 OK[0m
2024-11-12T14:50:32.043592785Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/setting/UserCustomCSS HTTP/1.1[0m" [32m200 OK[0m
2024-11-12T14:50:32.045590432Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/subscribe/ HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024-11-12T14:50:32.046923356Z [31mERROR[0m:    Exception in ASGI application
2024-11-12T14:50:32.046943228Z Traceback (most recent call last):
2024-11-12T14:50:32.046948658Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024-11-12T14:50:32.046952825Z     result = await app(  # type: ignore[func-returns-value]
2024-11-12T14:50:32.046956790Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:32.046960207Z   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-11-12T14:50:32.046963726Z     return await self.app(scope, receive, send)
2024-11-12T14:50:32.046966849Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:32.046969915Z   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2024-11-12T14:50:32.046973210Z     await super().__call__(scope, receive, send)
2024-11-12T14:50:32.046976398Z   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2024-11-12T14:50:32.046998892Z     await self.middleware_stack(scope, receive, send)
2024-11-12T14:50:32.047003597Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-11-12T14:50:32.047007508Z     raise exc
2024-11-12T14:50:32.047010952Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-11-12T14:50:32.047014249Z     await self.app(scope, receive, _send)
2024-11-12T14:50:32.047017407Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-11-12T14:50:32.047020607Z     await self.app(scope, receive, send)
2024-11-12T14:50:32.047023800Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-11-12T14:50:32.047027097Z     raise exc
2024-11-12T14:50:32.047030359Z   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-11-12T14:50:32.047033652Z     await self.app(scope, receive, sender)
2024-11-12T14:50:32.047036810Z   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024-11-12T14:50:32.047040055Z     raise e
2024-11-12T14:50:32.047045329Z   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024-11-12T14:50:32.047048565Z     await self.app(scope, receive, send)
2024-11-12T14:50:32.047051711Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2024-11-12T14:50:32.047054927Z     await route.handle(scope, receive, send)
2024-11-12T14:50:32.047058054Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2024-11-12T14:50:32.047062020Z     await self.app(scope, receive, send)
2024-11-12T14:50:32.047065210Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2024-11-12T14:50:32.047087296Z     response = await func(request)
2024-11-12T14:50:32.047091760Z                ^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:32.047094972Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 255, in app
2024-11-12T14:50:32.047098291Z     content = await serialize_response(
2024-11-12T14:50:32.047101311Z               ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-12T14:50:32.047104489Z   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 141, in serialize_response
2024-11-12T14:50:32.047107719Z     raise ValidationError(errors, field.type_)
2024-11-12T14:50:32.047110797Z pydantic.error_wrappers.ValidationError: 2 validation errors for Subscribe
2024-11-12T14:50:32.047113966Z response -> 1 -> sites
2024-11-12T14:50:32.047117148Z   value is not a valid list (type=type_error.list)
2024-11-12T14:50:32.047126528Z response -> 2 -> sites
2024-11-12T14:50:32.047130611Z   value is not a valid list (type=type_error.list)
2024-11-12T14:50:35.014226974Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/message HTTP/1.1[0m" [32m200 OK[0m
2024-11-12T14:50:42.612967267Z [32mINFO[0m:     192.168.31.178:0 - "[1mGET /api/v1/system/logging HTTP/1.1[0m" [32m200 OK[0m
```
补充报错日志，更新2.0.3也有同样问题

**Comment by yuan488** [comment]
重置数据库，再次订阅后，还会报错

**Comment by jxxghp** [comment]
是用V1的数据库升级过来的？

**Comment by f4cker** [comment]
> 是用V1的数据库升级过来的？

新装 v2.0.7 也遇到这个问题，过程中有多次重新部署

**Comment by zhouchiyan82** [comment]
我直接用的V2，一样，也发生了这个bug

**Comment by thsrite** [comment]
临时解决方案

安装`Sql执行器`插件执行以下sql，缺点是订阅设置的订阅站点会被清空

update subscribe set sites = [];

**Comment by 2604836155** [comment]
我也有这类问题
