### ISSUE TITLE
目录监控失败

### ISSUE THREAD

**Issue by Ikeleee** [jxxghp/MoviePilot#310]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.0.8

### 问题类型

插件问题

### 问题描述

运行目录监控，转移失败。
我是通过订阅电视剧下载资源，下载资源后，目录监控未硬链接文件，同时订阅资源处未记录已下载的集数

### 发生问题时系统日志和配置文件

```bash
2023-08-28 15:13:26 INFO:    __init__.py - Shrouding.the.Heavens.2023.S01E03.1080p.WEB-DL.H264.AAC-PTerWEB.mp4 识别为：电视剧 遮天 (2023)
2023-08-28 15:13:26 WARNING: __init__.py - 没有获取到 遮天 (2023) 的Fanart图片数据
2023-08-28 15:13:26 INFO:    tmdbapi.py - 正在获取电视剧图片：224839...
2023-08-28 15:13:26 Traceback (most recent call last):
2023-08-28 15:13:26   File "/app/app/chain/__init__.py", line 90, in run_module
2023-08-28 15:13:26     result = func(*args, **kwargs)
2023-08-28 15:13:26              ^^^^^^^^^^^^^^^^^^^^^
2023-08-28 15:13:26   File "/app/app/modules/filetransfer/__init__.py", line 56, in transfer
2023-08-28 15:13:26     return self.transfer_media(in_path=path,
2023-08-28 15:13:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-28 15:13:26   File "/app/app/modules/filetransfer/__init__.py", line 436, in transfer_media
2023-08-28 15:13:26     new_path = target_dir / (self.get_rename_path(
2023-08-28 15:13:28 INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect
2023-08-28 15:13:28 INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK
2023-08-28 15:13:26                              ^^^^^^^^^^^^^^^^^^^^^
2023-08-28 15:13:26   File "/app/app/modules/filetransfer/__init__.py", line 575, in get_rename_path
2023-08-28 15:13:26     template = Template(template_string)
2023-08-28 15:13:26                ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-28 15:13:26   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1208, in __new__
2023-08-28 15:13:26     return env.from_string(source, template_class=cls)
2023-08-28 15:13:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-28 15:13:26   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string
2023-08-28 15:13:26     return cls.from_code(self, self.compile(source), gs, None)
2023-08-28 15:13:26                                ^^^^^^^^^^^^^^^^^^^^
2023-08-28 15:13:26   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
2023-08-28 15:13:26     self.handle_exception(source=source_hint)
2023-08-28 15:13:26   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
2023-08-28 15:13:26     raise rewrite_traceback_stack(source=source)
2023-08-28 15:13:26   File "<unknown>", line 1, in template
2023-08-28 15:13:26 jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2023-08-28 15:13:26 ERROR:   __init__.py - 运行模块 transfer 出错：FileTransferModule - Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
```

**Comment by Ikeleee** [comment]
老大你好，我再检查了yaml，修改了环境重新点目录监控，这次是显示目录监控成功，但又没提示错误，但也没进行同步。查询日志未显示错误原因，请问我还能在哪里查呢

**Comment by jxxghp** [comment]
增量才会同步
