### ISSUE TITLE
[错误报告]: 带有 Site_url 的 alist 无法挂载

### ISSUE THREAD

**Issue by yfdoor** [jxxghp/MoviePilot#3207]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

Alist docker 部署地址：http://192.168.100.3:5244/alist  （带有 site_url）
MP Alist 设置如下：
![image](https://github.com/user-attachments/assets/e73eeda5-e5f9-42f2-801e-c6ee83bfb8b8)

现在无法挂载 Alist 且报错 
【ERROR】2024-11-22 20:20:30,615 - chain - 运行模块 FileManagerModule.list_files 出错：Expecting value: line 1 column 1 (char 0)

### 发生问题时系统日志和配置文件

```bash
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 978, in json
             ^^^^^^^^^^^
    result = resp.json()
  File "/app/app/modules/filemanager/storages/alist.py", line 109, in __generate_token
        ^^^^^^^^^^^^^^^^^^^^^
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/cachetools/__init__.py", line 737, in wrapper
           ^^^^^^^^^^^^^^^^^^^^^
    return self.__generate_token
  File "/app/app/modules/filemanager/storages/alist.py", line 67, in __get_valuable_toke
                             ^^^^^^^^^^^^^^^^^^^^^^^^
    return {"Authorization": self.__get_valuable_toke}
  File "/app/app/modules/filemanager/storages/alist.py", line 122, in __get_header_with_token
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    headers=self.__get_header_with_token()
  File "/app/app/modules/filemanager/storages/alist.py", line 152, in list
             ^^^^^^^^^^^^^^^^^^^^^^^^
    _items = storage_oper.list(_item)
  File "/app/app/modules/filemanager/__init__.py", line 180, in __get_files
    __get_files(fileitem, recursion)
  File "/app/app/modules/filemanager/__init__.py", line 193, in list_files
             ^^^^^^^^^^^^^^^^^^^^^
    result = func(*args, **kwargs)
  File "/app/app/chain/__init__.py", line 112, in run_module
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 974, in json
Traceback (most recent call last):
【ERROR】2024-11-22 20:21:07,216 - chain - 运行模块 FileManagerModule.list_files 出错：Expecting value: line 1 column 1 (char 0)

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 978, in json
             ^^^^^^^^^^^
    result = resp.json()
  File "/app/app/modules/filemanager/storages/alist.py", line 109, in __generate_token
        ^^^^^^^^^^^^^^^^^^^^^
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/cachetools/__init__.py", line 737, in wrapper
           ^^^^^^^^^^^^^^^^^^^^^
    return self.__generate_token
  File "/app/app/modules/filemanager/storages/alist.py", line 67, in __get_valuable_toke
                             ^^^^^^^^^^^^^^^^^^^^^^^^
    return {"Authorization": self.__get_valuable_toke}
  File "/app/app/modules/filemanager/storages/alist.py", line 122, in __get_header_with_token
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    headers=self.__get_header_with_token()
  File "/app/app/modules/filemanager/storages/alist.py", line 152, in list
             ^^^^^^^^^^^^^^^^^^^^^^^^
    _items = storage_oper.list(_item)
  File "/app/app/modules/filemanager/__init__.py", line 180, in __get_files
    __get_files(fileitem, recursion)
  File "/app/app/modules/filemanager/__init__.py", line 193, in list_files
             ^^^^^^^^^^^^^^^^^^^^^
    result = func(*args, **kwargs)
  File "/app/app/chain/__init__.py", line 112, in run_module
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 974, in json
Traceback (most recent call last):
```

**Comment by yfdoor** [comment]
@jxxghp 当前最新版本 2.1.1 该问题依然存在，有机会的希望可以修复，谢谢。
