### ISSUE TITLE
媒体库刮削 执行失败：'NoneType' object has no attribute 'path' 

### ISSUE THREAD

**Issue by Lancer907** [jxxghp/MoviePilot#3253]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

自动/手动整理文件时，提示“媒体库刮削 执行失败：'NoneType' object has no attribute 'path' ”。可以正常的硬链接到媒体库位置，但是电影文件夹里面只有视频、nfo两个文件，没有图片。电视剧里也是一样，并且Season文件夹没有附属的文件，只有season 1
 这样的文件夹。
<img width="225" alt="Snipaste_2024-11-26_21-51-33" src="https://github.com/user-attachments/assets/51a7efb6-b12a-42d1-b440-8e1b835ee682">
<img width="232" alt="Snipaste_2024-11-26_21-41-54" src="https://github.com/user-attachments/assets/940a7acc-65b0-4f53-a503-c843efd82b39">
<img width="513" alt="Snipaste_2024-11-26_21-49-23" src="https://github.com/user-attachments/assets/876a1110-d02c-4994-8c32-2dcc05c48d64">
<img width="404" alt="Snipaste_2024-11-26_21-49-41" src="https://github.com/user-attachments/assets/489b26b8-fca4-467a-875b-d9160e1064fa">

### 发生问题时系统日志和配置文件

```bash
【DEBUG】2024-11-26 21:47:04,048 - event.py - Handler app.plugins.webhook.WebHook.send is disabled. Skipping execution
【DEBUG】2024-11-26 21:47:04,047 - event.py - Triggering broadcast event: <Broadcast Event: system.error, ID: c538e429-e388-4319-9df0-987e808e70bb, Priority: 10>

AttributeError: 'NoneType' object has no attribute 'path'
                          ^^^^^^^^^
    logger.warn(f"文件保存失败：{item.path}")
  File "/app/app/chain/media.py", line 377, in __save_file
    __save_file(_fileitem=fileitem, _path=image_path, _content=content)
  File "/app/app/chain/media.py", line 466, in scrape_metadata
    self.mediachain.scrape_metadata(
  File "/app/app/plugins/libraryscraper/__init__.py", line 408, in __scrape_dir
    self.__scrape_dir(path=item[0], mtype=item[1])
  File "/app/app/plugins/libraryscraper/__init__.py", line 363, in __libraryscraper
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 385, in start
【ERROR】2024-11-26 21:47:04,040 - scheduler.py - 定时任务 媒体库刮削 执行失败：'NoneType' object has no attribute 'path' - Traceback (most recent call last):
【DEBUG】2024-11-26 21:46:03,966 - event.py - Handler app.plugins.webhook.WebHook.send is disabled. Skipping execution
【DEBUG】2024-11-26 21:46:03,964 - event.py - Triggering broadcast event: <Broadcast Event: system.error, ID: 898a149d-6323-4d18-9755-4ca70645532b, Priority: 10>

AttributeError: 'NoneType' object has no attribute 'path'
                          ^^^^^^^^^
    logger.warn(f"文件保存失败：{item.path}")
  File "/app/app/chain/media.py", line 377, in __save_file
    __save_file(_fileitem=fileitem, _path=image_path, _content=content)
  File "/app/app/chain/media.py", line 466, in scrape_metadata
    self.mediachain.scrape_metadata(
  File "/app/app/plugins/libraryscraper/__init__.py", line 408, in __scrape_dir
    self.__scrape_dir(path=item[0], mtype=item[1])
  File "/app/app/plugins/libraryscraper/__init__.py", line 363, in __libraryscraper
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 385, in start
【ERROR】2024-11-26 21:46:03,958 - scheduler.py - 定时任务 媒体库刮削 执行失败：'NoneType' object has no attribute 'path' - Traceback (most recent call last):
【DEBUG】2024-11-26 21:45:03,339 - event.py - Handler app.plugins.webhook.WebHook.send is disabled. Skipping execution
【DEBUG】2024-11-26 21:45:03,338 - event.py - Triggering broadcast event: <Broadcast Event: system.error, ID: 889cdc5e-44fb-4ca2-8f38-8b688b17ea2e, Priority: 10>

AttributeError: 'NoneType' object has no attribute 'path'
                          ^^^^^^^^^
    logger.warn(f"文件保存失败：{item.path}")
  File "/app/app/chain/media.py", line 377, in __save_file
    __save_file(_fileitem=fileitem, _path=image_path, _content=content)
  File "/app/app/chain/media.py", line 466, in scrape_metadata
    self.mediachain.scrape_metadata(
  File "/app/app/plugins/libraryscraper/__init__.py", line 408, in __scrape_dir
    self.__scrape_dir(path=item[0], mtype=item[1])
  File "/app/app/plugins/libraryscraper/__init__.py", line 363, in __libraryscraper
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 385, in start
【ERROR】2024-11-26 21:45:03,336 - scheduler.py - 定时任务 媒体库刮削 执行失败：'NoneType' object has no attribute 'path' - Traceback (most recent call last):
【DEBUG】2024-11-26 21:44:02,739 - event.py - Handler app.plugins.webhook.WebHook.send is disabled. Skipping execution
【DEBUG】2024-11-26 21:44:02,737 - event.py - Triggering broadcast event: <Broadcast Event: system.error, ID: 0875f13c-1d25-4df7-be46-b5ea36e2270f, Priority: 10>

AttributeError: 'NoneType' object has no attribute 'path'
                          ^^^^^^^^^
    logger.warn(f"文件保存失败：{item.path}")
  File "/app/app/chain/media.py", line 377, in __save_file
    __save_file(_fileitem=fileitem, _path=image_path, _content=content)
  File "/app/app/chain/media.py", line 466, in scrape_metadata
    self.mediachain.scrape_metadata(
  File "/app/app/plugins/libraryscraper/__init__.py", line 408, in __scrape_dir
    self.__scrape_dir(path=item[0], mtype=item[1])
  File "/app/app/plugins/libraryscraper/__init__.py", line 363, in __libraryscraper
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 385, in start
【ERROR】2024-11-26 21:44:02,736 - scheduler.py - 定时任务 媒体库刮削 执行失败：'NoneType' object has no attribute 'path' - Traceback (most recent call last):
【DEBUG】2024-11-26 21:43:13,457 - chain - 请求模块执行：scheduler_job ...
【DEBUG】2024-11-26 21:43:03,122 - event.py - Handler app.plugins.webhook.WebHook.send is disabled. Skipping execution
【DEBUG】2024-11-26 21:43:03,119 - event.py - Triggering broadcast event: <Broadcast Event: system.error, ID: bc8ad064-1bc2-4d55-a6cc-9beda03cd2b1, Priority: 10>

AttributeError: 'NoneType' object has no attribute 'path'
                          ^^^^^^^^^
    logger.warn(f"文件保存失败：{item.path}")
  File "/app/app/chain/media.py", line 377, in __save_file
    __save_file(_fileitem=fileitem, _path=image_path, _content=content)
  File "/app/app/chain/media.py", line 466, in scrape_metadata
    self.mediachain.scrape_metadata(
  File "/app/app/plugins/libraryscraper/__init__.py", line 408, in __scrape_dir
    self.__scrape_dir(path=item[0], mtype=item[1])
  File "/app/app/plugins/libraryscraper/__init__.py", line 363, in __libraryscraper
    job["func"](*args, **kwargs)
  File "/app/app/scheduler.py", line 385, in start
【ERROR】2024-11-26 21:43:03,117 - scheduler.py - 定时任务 媒体库刮削 执行失败：'NoneType' object has no attribute 'path' - Traceback (most recent call last):
【DEBUG】2024-11-26 21:42:07,198 - event.py - Handler app.plugins.webhook.WebHook.send is disabled. Skipping execution
【DEBUG】2024-11-26 21:42:07,192 - event.py - Triggering broadcast event: <Broadcast Event: system.error, ID: 21c2edeb-78eb-4812-b967-477a5c20f280, Priority: 10>
```

**Comment by Lancer907** [comment]
Docker安装TrueNas (ElectricEel-24.10.0.2)上，UID尝试过0和568都不行

**Comment by DoraTiger** [comment]
监控模式改兼容

**Comment by Lancer907** [comment]
已解决：权限问题，Truenas设置数据集时，可以选择ACL mode，以前设置成restricted就不行，改成passthrough就ok了。（但是v1不需要改也能正常刮削）
