### ISSUE TITLE
[错误报告]: 发现一个日志中的数据库操作错误，细看了一下日志，应该是数据库发生死锁了

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#330]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.9

### 问题类型

主程序运行问题

### 问题描述

发现一个日志中的数据库操作错误，细看了一下日志，应该是数据库发生死锁了

### 发生问题时系统日志和配置文件

```bash
【ERROR】2023-08-30 05:22:07,800 - base.py - Job "同步媒体服务器 (trigger: interval[1:00:00], next run at: 2023-08-30 06:22:02 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/chain/mediaserver.py", line 63, in sync
    self.mediaserverdb.empty(server=settings.MEDIASERVER)
  File "/app/app/db/mediaserver_oper.py", line 32, in empty
    MediaServerItem.empty(self._db, server)
  File "/app/app/db/models/mediaserver.py", line 49, in empty
    db.query(MediaServerItem).filter(MediaServerItem.server == server).delete()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 3176, in delete
    result: CursorResult[Any] = self.session.execute(
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2144, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1950, in orm_execute_statement
    return super().orm_execute_statement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: DELETE FROM mediaserveritem WHERE mediaserveritem.server = ?]
[parameters: ('jellyfin',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
【INFO】2023-08-30 05:47:02,793 - rss.py - 开始刷新RSS订阅数据 ...
【INFO】2023-08-30 05:47:02,794 - rss.py - 刷新RSS订阅数据完成
【INFO】2023-08-30 06:00:00,002 - __init__.py - 开始刷新站点数据 ...
【INFO】2023-08-30 06:00:00,005 - __init__.py - 开始同步用户 的豆瓣想看数据 ...
【INFO】2023-08-30 06:00:00,193 - __init__.py - 用户 豆瓣想看同步完成
【ERROR】2023-08-30 06:00:15,216 - base.py - Job "站点数据统计 (trigger: cron[month='*', day='*', day_of_week='*', hour='*/6', minute='0'], next run at: 2023-08-30 12:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/sitestatistic/__init__.py", line 1041, in refresh_all_site_data
    self.save_data(key, self._sites_data)
  File "/app/app/plugins/__init__.py", line 157, in save_data
    return self.plugindata.save(plugin_id, key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/plugindata_oper.py", line 26, in save
    plugin.update(self._db, {
  File "/app/app/db/models/__init__.py", line 24, in update
    db.commit()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1923, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1239, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1214, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4179, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4314, in _flush
    with util.safe_reraise():
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4275, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 909, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE plugindata SET value=? WHERE plugindata.id = ?]
[parameters: ('{"\\u9ad8\\u6e05\\u675c\\u6bd4": {"upload": 4760885348270, "username": "xxx", "user_level": "(\\u8425\\u957f)Crazy User", "join_at": "2023-05- ... (2080 characters truncated) ... eeding": 342, "seeding_size": 2642564528212, "leeching": 0, "bonus": 167835.2, "url": "https://xp.m-team.io/", "err_msg": null, "message_unread": 0}}', 57)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by mjsoftking** [comment]
目前重启了一下，暂时未发生这个问题

**Comment by mjsoftking** [comment]
每次重启挺不了多久就会再次发生，应该是某个后台任务导致的

**Comment by dlovew** [comment]
很多定时任务都会出现这个i情况，解决方法现在就是重启

**Comment by mjsoftking** [comment]
订阅刷新也有报错
`
【ERROR】2023-08-30 13:48:43,632 - base.py - Job "订阅刷新 (trigger: cron[hour='13', minute='48'], next run at: 2023-08-31 13:48:00 CST)" raised an exception
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app/chain/subscribe.py", line 379, in refresh
self.match(
File "/app/app/chain/subscribe.py", line 540, in match
downloads, lefts = self.downloadchain.batch_download(contexts=_match_context, no_exists=no_exists)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app/chain/download.py", line 459, in batch_download
torrent_path, _, torrent_files = self.download_torrent(torrent, userid=userid)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app/chain/download.py", line 77, in download_torrent
torrent_file, _, download_folder, files, error_msg = self.torrent.download_torrent(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app/helper/torrent.py", line 37, in download_torrent
if url.startswith("magnet:"):
^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
`

**Comment by mjsoftking** [comment]
@jxxghp 在db.commit()的数据库方法体中加线程锁能不能阻止这个问题，不懂python

**Comment by mjsoftking** [comment]
database is locked 百度一下，应该是多线程同时写导致的

**Comment by jxxghp** [comment]
> database is locked 百度一下，应该是多线程同时写导致的

最新的程序减小了会话数， 看下有没有改善。

**Comment by mjsoftking** [comment]
> > database is locked 百度一下，应该是多线程同时写导致的
> 
> 最新的程序减小了会话数， 看下有没有改善。

好的，稍后更新镜像，持续关注下

**Comment by mjsoftking** [comment]
@jxxghp 好像还是存在问题

···
【ERROR】2023-09-01 19:00:00,008 - base.py - Job "站点自动签到 (trigger: cron[month='*', day='*', day_of_week='*', hour='4-20', minute='0'], next run at: 2023-09-01 20:00:00 CST)" raised an exception
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app/plugins/autosignin/__init__.py", line 569, in sign_in
self.del_data(key=yesterday_str)
File "/app/app/plugins/__init__.py", line 175, in del_data
return self.plugindata.del_data(plugin_id, key)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app/db/plugindata_oper.py", line 52, in del_data
PluginData.del_plugin_data_by_key(self._db, plugin_id, key)
File "/app/app/db/models/plugin.py", line 26, in del_plugin_data_by_key
return db.query(PluginData).filter(PluginData.plugin_id == plugin_id, PluginData.key == key).delete()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 3176, in delete
result: CursorResult[Any] = self.session.execute(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
return self._execute_internal(
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2134, in _execute_internal
conn = self._connection_for_bind(bind)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
return trans._connection_for_bind(engine, execution_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<string>", line 2, in _connection_for_bind
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
self._raise_for_prerequisite_state(fn.__name__, current_state)
File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 929, in _raise_for_prerequisite_state
raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is provisioning a new connection; concurrent operations are not permitted (Background on this error at: https://sqlalche.me/e/20/isce)
···

**Comment by mjsoftking** [comment]
@jxxghp 辅种插件出现的错误，另外首页显示的电影数量总是多一个，看了下数据库记录451，但是首页显示452

```
【ERROR】2023-09-02 06:53:26,056 - base.py - Job "IYUUAutoSeed.auto_seed (trigger: date[2023-09-02 06:53:10 CST], next run at: 2023-09-02 06:53:10 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/iyuuautoseed/__init__.py", line 452, in auto_seed
    self.__seed_torrents(hash_strs=chunk,
  File "/app/app/plugins/iyuuautoseed/__init__.py", line 564, in __seed_torrents
    success = self.__download_torrent(seed=seed,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/iyuuautoseed/__init__.py", line 686, in __download_torrent
    site_info = self.sites.get_indexer(site_domain)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "app/helper/sites.py", line 111, in app.helper.sites.SitesHelper.get_indexer
  File "/app/app/db/site_oper.py", line 58, in get_by_domain
    return Site.get_by_domain(self._db, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/models/site.py", line 51, in get_by_domain
    return db.query(Site).filter(Site.domain == domain).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2743, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2134, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 935, in _raise_for_prerequisite_state
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
```

**Comment by jxxghp** [comment]
又重新调整了下，进入容器终端，执行以下命令，并重启容器再跑跑看：
```
chmod +x dev.sh
./dev.sh
```

**Comment by mjsoftking** [comment]
@jxxghp 这样应该是更新完了吧
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/8380eb8f-373f-4674-8574-aadadb537eef)

**Comment by mjsoftking** [comment]
@jxxghp 更新了，前端被更新到1.1.1了
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/4b2188a0-9b33-42e0-9389-650653483137)

**Comment by jxxghp** [comment]
> @jxxghp 更新了，前端被更新到1.1.1了
> 
> ![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/4b2188a0-9b33-42e0-9389-650653483137)
> 
> 

没关系，都是嫌容的。

**Comment by mjsoftking** [comment]
> > @jxxghp 更新了，前端被更新到1.1.1了
> > ![图片](https://user-images.githubusercontent.com/23021469/265154069-4b2188a0-9b33-42e0-9389-650653483137.png)
> 
> 没关系，都是嫌容的。

重启后容器启动失败，无限重启了，这种方式我这个nas可能无法运行

**Comment by mjsoftking** [comment]
我在试试其他方式更新下看看

**Comment by jxxghp** [comment]
@mjsoftking 那等下一个版本也行

**Comment by mjsoftking** [comment]
我在试试吧，不行就下版本试试，要是能验证解决了，下版本也稳定了，这个锁库挺难受的会导致任务运行没结果

**Comment by mjsoftking** [comment]
还是不行，下版本持续关注这个问题吧

**Comment by mjsoftking** [comment]
@jxxghp 老大，我下载项目的所有文件，然后docker映射运行文件夹指向这个我下载的代码目录能行不

**Comment by jxxghp** [comment]
@mjsoftking 比较复杂，不好搞，要不1.1.0我再重新打次包吧，你再拉一下

**Comment by mjsoftking** [comment]
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/23a805fb-22ea-4c0f-92e4-adfe0607086d)
运行起来了，我修改下版本，显示的是我修改的

**Comment by mjsoftking** [comment]
这样应该就是运行的外置代码程序了，我先跑着

**Comment by jxxghp** [comment]
@mjsoftking 行

**Comment by dlovew** [comment]
可以重新打包一下么？dev.sh更新失败。。。重启不了 @jxxghp

**Comment by mjsoftking** [comment]
@jxxghp 目前为止未发生数据库锁定错误 

#367 发生过这个错误

**Comment by mjsoftking** [comment]
> 可以重新打包一下么？dev.sh更新失败。。。重启不了 @jxxghp

映射 /app 目录，宿主机的目录就是下载的源代码解压后的文件夹

**Comment by mjsoftking** [comment]
@jxxghp 后台任务基本都是1小时一执行，截至到18点为止未发生数据库锁定问题
