### ISSUE TITLE
[错误报告]: 不定时报错提醒，提示站点索引发生错误

### ISSUE THREAD

**Issue by dick86114** [jxxghp/MoviePilot#3318]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

时不时会收到后台的报错提醒，提示站点索引发生了错误，具体报错内容如下：

### 发生问题时系统日志和配置文件

```bash
【站点索引发生了错误】
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 112, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/indexer/__init__.py", line 259, in refresh_userdata
    site_obj.parse()
  File "/app/app/modules/indexer/parser/__init__.py", line 198, in parse
    self._parse_seeding_pages()
  File "/app/app/modules/indexer/parser/__init__.py", line 251, in _parse_seeding_pages
    next_page = self._parse_user_torrent_seeding_info(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/indexer/parser/tnode.py", line 66, in _parse_user_torrent_seeding_info
    seeding_info = json.loads(html_text)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by js393505397** [comment]
我也有这个问题，请问解决了吗？

**Comment by 954708775** [comment]
我也一直有这个问题
<img width="365" alt="image" src="https://github.com/user-attachments/assets/5607b61e-a6d8-4fed-88a4-7bb7f90cb511" />

**Comment by dick86114** [comment]
> 我也有这个问题，请问解决了吗？

没解决，我删掉了提醒插件
