### ISSUE TITLE
[错误报告]: 整理队列未执行

### ISSUE THREAD

**Issue by AisukaYuki** [jxxghp/MoviePilot#3648]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

整理队列未执行，无反应

### 发生问题时系统日志和配置文件

```bash
2024/12/31 15:00:29	stdout	[32mINFO[0m:     172.20.0.1:0 - "[1mPOST /api/v1/storage/list?sort=name HTTP/1.1[0m" [32m200 OK[0m
2024/12/31 15:00:29	stdout	re.error: unterminated character set at position 0
2024/12/31 15:00:29	stdout	    raise source.error("unterminated character set",
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/re/_parser.py", line 563, in _parse
2024/12/31 15:00:29	stdout	                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    itemsappend(_parse(source, state, verbose, nested + 1,
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/re/_parser.py", line 455, in _parse_sub
2024/12/31 15:00:29	stdout	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/re/_parser.py", line 980, in parse
2024/12/31 15:00:29	stdout	        ^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    p = _parser.parse(p, flags)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/re/_compiler.py", line 743, in compile
2024/12/31 15:00:29	stdout	        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    p = _compiler.compile(pattern, flags)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/re/__init__.py", line 294, in _compile
2024/12/31 15:00:29	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    return _compile(pattern, flags).search(string)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/re/__init__.py", line 176, in search
2024/12/31 15:00:29	stdout	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    if keyword and re.search(r"%s" % keyword, file_item.path, re.IGNORECASE):
2024/12/31 15:00:29	stdout	  File "/app/app/chain/transfer.py", line 1004, in do_transfer
2024/12/31 15:00:29	stdout	                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    state, errmsg = self.do_transfer(fileitem=fileitem,
2024/12/31 15:00:29	stdout	  File "/app/app/chain/transfer.py", line 1282, in manual_transfer
2024/12/31 15:00:29	stdout	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    state, errormsg = TransferChain().manual_transfer(
2024/12/31 15:00:29	stdout	  File "/app/app/api/endpoints/transfer.py", line 141, in manual_transfer
2024/12/31 15:00:29	stdout	             ^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    result = context.run(func, *args)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
2024/12/31 15:00:29	stdout	           ^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    return await future
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
2024/12/31 15:00:29	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    return await get_async_backend().run_sync_in_worker_thread(
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024/12/31 15:00:29	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    return await anyio.to_thread.run_sync(func, *args)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2024/12/31 15:00:29	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    return await run_in_threadpool(dependant.call, **values)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
2024/12/31 15:00:29	stdout	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    raw_response = await run_endpoint_function(
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
2024/12/31 15:00:29	stdout	               ^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    response = await func(request)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2024/12/31 15:00:29	stdout	    await self.app(scope, receive, send)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2024/12/31 15:00:29	stdout	    await route.handle(scope, receive, send)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2024/12/31 15:00:29	stdout	    await self.app(scope, receive, send)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024/12/31 15:00:29	stdout	    raise e
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024/12/31 15:00:29	stdout	    await self.app(scope, receive, sender)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024/12/31 15:00:29	stdout	    raise exc
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024/12/31 15:00:29	stdout	    await self.app(scope, receive, send)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024/12/31 15:00:29	stdout	    await self.simple_response(scope, receive, send, request_headers=headers)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024/12/31 15:00:29	stdout	    await self.app(scope, receive, _send)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024/12/31 15:00:29	stdout	    raise exc
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024/12/31 15:00:29	stdout	    await self.middleware_stack(scope, receive, send)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2024/12/31 15:00:29	stdout	    await super().__call__(scope, receive, send)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2024/12/31 15:00:29	stdout	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    return await self.app(scope, receive, send)
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024/12/31 15:00:29	stdout	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/31 15:00:29	stdout	    result = await app(  # type: ignore[func-returns-value]
2024/12/31 15:00:29	stdout	  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024/12/31 15:00:29	stdout	Traceback (most recent call last):
2024/12/31 15:00:29	stdout	[31mERROR[0m:    Exception in ASGI application
2024/12/31 15:00:29	stdout	[32mINFO[0m:     172.20.0.1:0 - "[1mPOST /api/v1/transfer/manual?background=false HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024/12/31 15:00:29	stdout	[32mINFO:[0m    transfer.py - 开始整理，共 30 个文件 ...
2024/12/31 15:00:29	stdout	[32mINFO:[0m    transfer.py - 正在计划整理 30 个文件...
2024/12/31 15:00:29	stdout	[32mINFO:[0m    transfer.py - 手动整理：/volume1/Media/Downloads/动漫/[CASO][Natsume_Yuujinchou]/ ...
2024/12/31 15:00:29	stdout	[32mINFO[0m:     172.20.0.1:0 - "[1mGET /api/v1/system/progress/filetransfer HTTP/1.1[0m" [32m200 OK[0m
2024/12/31 15:00:28	stdout	[32mINFO[0m:     172.20.0.1:0 - "[1mGET /api/v1/system/setting/Directories HTTP/1.1[0m" [32m200 OK[0m
2024/12/31 15:00:27	stdout	[32mINFO[0m:     172.20.0.1:0 - "[1mPOST /api/v1/storage/list?sort=name HTTP/1.1[0m" [32m200 OK[0m
2024/12/31 15:00:25	stdout	[32mINFO[0m:     172.20.0.1:0 - "[1mPOST /api/v1/storage/list?sort=name HTTP/1.1[0m" [32m200 OK[0m
```

**Comment by AisukaYuki** [comment]
没事了屏蔽词。[ 少写了个转义。 \[
