### ISSUE TITLE
[错误报告]: 自动同步下载器文件记录 提示属性get_completed_torrents未找到错误

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#367]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.0

### 问题类型

插件问题

### 问题描述

自动同步下载器文件记录 提示属性get_completed_torrents未找到错误
同步终端为 TR3.00

### 发生问题时系统日志和配置文件

```bash
【ERROR】2023-09-02 08:06:32,832 - base.py - Job "自动同步下载器文件记录 (trigger: interval[1:00:00], next run at: 2023-09-02 09:06:32 CST)" raised an exception
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/app/plugins/syncdownloadfiles/__init__.py", line 122, in sync
torrents = downloader_obj.get_completed_torrents()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_completed_torrents'
```

**Comment by jxxghp** [comment]
下载器的参数没配置好？提供下全一点的日志。

**Comment by mjsoftking** [comment]
> 下载器的参数没配置好？提供下全一点的日志。

第一次运行顺利结束了，之后的定时任务报出来的
立即运行一次也没问题
```
【INFO】2023-09-02 16:53:41,473 - __init__.py - 开始同步下载器任务文件记录
【INFO】2023-09-02 16:53:41,475 - __init__.py - 开始扫描下载器 transmission ...
【INFO】2023-09-02 16:53:41,830 - __init__.py - 下载器 transmission 已完成种子数：1397
【INFO】2023-09-02 16:53:41,838 - __init__.py - 下载器 transmission 去除辅种，获取到源种子数：506
【INFO】2023-09-02 16:53:41,839 - __init__.py - 最后同步时间2023-09-02 06:49:11, 之前种子已被同步，结束当前下载器 transmission 任务
【INFO】2023-09-02 16:53:41,839 - __init__.py - 下载器种子文件同步完成！
【INFO】2023-09-02 16:53:41,861 - __init__.py - 下载器任务文件记录已同步完成。总耗时 0 秒
【INFO】2023-09-02 16:53:41,863 - __init__.py - 自动同步下载器文件记录服务启动，时间间隔 1 小时
```
