### ISSUE TITLE
[错误报告]:容器构建完成后自己疯狂重启

### ISSUE THREAD

**Issue by Smart-zsw** [jxxghp/MoviePilot#398]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.0

### 问题类型

Docker或运行环境问题

### 问题描述

设备是极空间的设备，构建都配置好了，就一直自己疯狂重启，之前版本也遇到过这个问题，但是也没做什么自己就突然好了，这次这个最新版本我把旧版本删除，想重新构建一下，又遇到这个问题了，就是启动后一直容器疯狂自动重启，这个次不管怎么手动重启就是不好了，以下是这个问题遇到的日志（我尝试了切换代理，发现应该不是代理的问题，像是组件差在哪了），感谢大佬开发！

### 发生问题时系统日志和配置文件

```bash
82023-09-02T09:55:20.136547509Z 使用代理更新程序
82023-09-02T09:55:20.141773694Z 当前版本号：v1.1.0
M2023-09-02T09:55:23.589154043Z 最新版本号获取失败，继续启动...
B2023-09-02T09:55:24.858023787Z Traceback (most recent call last):
N2023-09-02T09:55:24.858055789Z   File "/app/app/main.py", line 8, in <module>
C2023-09-02T09:55:24.858075420Z     from app.command import Command
Q2023-09-02T09:55:24.858088158Z   File "/app/app/command.py", line 5, in <module>
C2023-09-02T09:55:24.858185876Z     from app.chain import ChainBase
Y2023-09-02T09:55:24.858197293Z   File "/app/app/chain/__init__.py", line 13, in <module>
H2023-09-02T09:55:24.858275984Z     from app.core.config import settings
W2023-09-02T09:55:24.858286682Z   File "/app/app/core/config.py", line 266, in <module>
92023-09-02T09:55:24.858447037Z     settings = Settings()
92023-09-02T09:55:24.858461880Z                ^^^^^^^^^^
W2023-09-02T09:55:24.858467816Z   File "/app/app/core/config.py", line 251, in __init__
62023-09-02T09:55:24.858619169Z     super().__init__()
z2023-09-02T09:55:24.858627352Z   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
h2023-09-02T09:55:24.858731261Z   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
h2023-09-02T09:55:24.858898740Z pydantic.error_wrappers.ValidationError: 1 validation error for Settings
92023-09-02T09:55:24.858911368Z MEDIASERVER_SYNC_INTERVAL
X2023-09-02T09:55:24.858917069Z   value is not a valid integer (type=type_error.integer)
82023-09-02T09:55:30.338680622Z 使用代理更新程序
82023-09-02T09:55:30.342482821Z 当前版本号：v1.1.0
M2023-09-02T09:55:30.674316472Z 最新版本号获取失败，继续启动...
32023-09-02T09:55:30.687701114Z usermod: no changes
B2023-09-02T09:55:31.763949649Z Traceback (most recent call last):
N2023-09-02T09:55:31.763980958Z   File "/app/app/main.py", line 8, in <module>
C2023-09-02T09:55:31.763987805Z     from app.command import Command
Q2023-09-02T09:55:31.763992258Z   File "/app/app/command.py", line 5, in <module>
C2023-09-02T09:55:31.764059645Z     from app.chain import ChainBase
Y2023-09-02T09:55:31.764084078Z   File "/app/app/chain/__init__.py", line 13, in <module>
H2023-09-02T09:55:31.764177294Z     from app.core.config import settings
W2023-09-02T09:55:31.764198967Z   File "/app/app/core/config.py", line 266, in <module>
92023-09-02T09:55:31.764430425Z     settings = Settings()
92023-09-02T09:55:31.764454942Z                ^^^^^^^^^^
W2023-09-02T09:55:31.764462904Z   File "/app/app/core/config.py", line 251, in __init__
62023-09-02T09:55:31.764619902Z     super().__init__()
z2023-09-02T09:55:31.764653527Z   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
h2023-09-02T09:55:31.764796341Z   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
h2023-09-02T09:55:31.764939548Z pydantic.error_wrappers.ValidationError: 1 validation error for Settings
92023-09-02T09:55:31.764948164Z MEDIASERVER_SYNC_INTERVAL
X2023-09-02T09:55:31.764953067Z   value is not a valid integer (type=type_error.integer)
82023-09-02T09:55:37.270806239Z 使用代理更新程序


Y2023-09-02T10:06:42.473703175Z   File "/app/app/chain/__init__.py", line 13, in <module>
H2023-09-02T10:06:42.473801390Z     from app.core.config import settings
W2023-09-02T10:06:42.473812219Z   File "/app/app/core/config.py", line 266, in <module>
92023-09-02T10:06:42.473994294Z     settings = Settings()
92023-09-02T10:06:42.474011281Z                ^^^^^^^^^^
W2023-09-02T10:06:42.474017210Z   File "/app/app/core/config.py", line 251, in __init__
62023-09-02T10:06:42.474153522Z     super().__init__()
z2023-09-02T10:06:42.474174880Z   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
h2023-09-02T10:06:42.474298426Z   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
h2023-09-02T10:06:42.474441334Z pydantic.error_wrappers.ValidationError: 1 validation error for Settings
92023-09-02T10:06:42.474488703Z MEDIASERVER_SYNC_INTERVAL
X2023-09-02T10:06:42.474495293Z   value is not a valid integer (type=type_error.integer)
;2023-09-02T10:06:47.485154021Z 不使用代理更新程序
82023-09-02T10:06:47.487901909Z 当前版本号：v1.1.0
82023-09-02T10:06:48.969447718Z 最新版本号：v1.1.0
J2023-09-02T10:06:48.969492979Z 未发现新版本，跳过更新步骤...
32023-09-02T10:06:48.981817307Z usermod: no changes
B2023-09-02T10:06:50.087497241Z Traceback (most recent call last):
N2023-09-02T10:06:50.087532996Z   File "/app/app/main.py", line 8, in <module>
C2023-09-02T10:06:50.087539658Z     from app.command import Command
Q2023-09-02T10:06:50.087545033Z   File "/app/app/command.py", line 5, in <module>
C2023-09-02T10:06:50.087701734Z     from app.chain import ChainBase
Y2023-09-02T10:06:50.087745584Z   File "/app/app/chain/__init__.py", line 13, in <module>
H2023-09-02T10:06:50.087827757Z     from app.core.config import settings
W2023-09-02T10:06:50.087863050Z   File "/app/app/core/config.py", line 266, in <module>
92023-09-02T10:06:50.088022334Z     settings = Settings()
92023-09-02T10:06:50.088057361Z                ^^^^^^^^^^
W2023-09-02T10:06:50.088065752Z   File "/app/app/core/config.py", line 251, in __init__
62023-09-02T10:06:50.088203257Z     super().__init__()
z2023-09-02T10:06:50.088236999Z   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
h2023-09-02T10:06:50.088372884Z   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
h2023-09-02T10:06:50.088639421Z pydantic.error_wrappers.ValidationError: 1 validation error for Settings
92023-09-02T10:06:50.088654579Z MEDIASERVER_SYNC_INTERVAL
X2023-09-02T10:06:50.088659532Z   value is not a valid integer (type=type_error.integer)
;2023-09-02T10:06:55.311136179Z 不使用代理更新程序
82023-09-02T10:06:55.315229098Z 当前版本号：v1.1.0
82023-09-02T10:06:55.785504413Z 最新版本号：v1.1.0
J2023-09-02T10:06:55.785539600Z 未发现新版本，跳过更新步骤...
32023-09-02T10:06:55.799089462Z usermod: no changes
B2023-09-02T10:06:56.969864689Z Traceback (most recent call last):
N2023-09-02T10:06:56.969899544Z   File "/app/app/main.py", line 8, in <module>
C2023-09-02T10:06:56.969931555Z     from app.command import Command
Q2023-09-02T10:06:56.969938551Z   File "/app/app/command.py", line 5, in <module>
C2023-09-02T10:06:56.970050324Z     from app.chain import ChainBase
Y2023-09-02T10:06:56.970061477Z   File "/app/app/chain/__init__.py", line 13, in <module>
H2023-09-02T10:06:56.970187422Z     from app.core.config import settings
W2023-09-02T10:06:56.970198498Z   File "/app/app/core/config.py", line 266, in <module>
92023-09-02T10:06:56.970353433Z     settings = Settings()
92023-09-02T10:06:56.970379170Z                ^^^^^^^^^^
W2023-09-02T10:06:56.970386400Z   File "/app/app/core/config.py", line 251, in __init__
62023-09-02T10:06:56.970510162Z     super().__init__()
z2023-09-02T10:06:56.970529604Z   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
h2023-09-02T10:06:56.970651541Z   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
h2023-09-02T10:06:56.970791044Z pydantic.error_wrappers.ValidationError: 1 validation error for Settings
92023-09-02T10:06:56.970801365Z MEDIASERVER_SYNC_INTERVAL
X2023-09-02T10:06:56.970806406Z   value is not a valid integer (type=type_error.integer)
;2023-09-02T10:07:01.786042515Z 不使用代理更新程序
82023-09-02T10:07:01.788955477Z 当前版本号：v1.1.0
82023-09-02T10:07:02.219992030Z 最新版本号：v1.1.0
J2023-09-02T10:07:02.220029193Z 未发现新版本，跳过更新步骤...
32023-09-02T10:07:02.231731051Z usermod: no changes
B2023-09-02T10:07:03.397516916Z Traceback (most recent call last):
N2023-09-02T10:07:03.397552622Z   File "/app/app/main.py", line 8, in <module>
C2023-09-02T10:07:03.397571116Z     from app.command import Command
Q2023-09-02T10:07:03.397592326Z   File "/app/app/command.py", line 5, in <module>
C2023-09-02T10:07:03.397720371Z     from app.chain import ChainBase
Y2023-09-02T10:07:03.397730060Z   File "/app/app/chain/__init__.py", line 13, in <module>
H2023-09-02T10:07:03.397818184Z     from app.core.config import settings
W2023-09-02T10:07:03.397845255Z   File "/app/app/core/config.py", line 266, in <module>
92023-09-02T10:07:03.398025216Z     settings = Settings()
92023-09-02T10:07:03.398036176Z                ^^^^^^^^^^
W2023-09-02T10:07:03.398041422Z   File "/app/app/core/config.py", line 251, in __init__
62023-09-02T10:07:03.398176824Z     super().__init__()
z2023-09-02T10:07:03.398189395Z   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
h2023-09-02T10:07:03.398322331Z   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
h2023-09-02T10:07:03.398474183Z pydantic.error_wrappers.ValidationError: 1 validation error for Settings
92023-09-02T10:07:03.398485173Z MEDIASERVER_SYNC_INTERVAL
X2023-09-02T10:07:03.398490070Z   value is not a valid integer (type=type_error.integer)
;2023-09-02T10:07:09.141533995Z 不使用代理更新程序
82023-09-02T10:07:09.145672069Z 当前版本号：v1.1.0
82023-09-02T10:07:09.599851851Z 最新版本号：v1.1.0
J2023-09-02T10:07:09.599887640Z 未发现新版本，跳过更新步骤...
32023-09-02T10:07:09.609291102Z usermod: no changes
B2023-09-02T10:07:10.713707179Z Traceback (most recent call last):
N2023-09-02T10:07:10.713741048Z   File "/app/app/main.py", line 8, in <module>
C2023-09-02T10:07:10.713746650Z     from app.command import Command
Q2023-09-02T10:07:10.713752042Z   File "/app/app/command.py", line 5, in <module>
C2023-09-02T10:07:10.713823337Z     from app.chain import ChainBase
Y2023-09-02T10:07:10.713847510Z   File "/app/app/chain/__init__.py", line 13, in <module>
H2023-09-02T10:07:10.713991968Z     from app.core.config import settings
W2023-09-02T10:07:10.714002875Z   File "/app/app/core/config.py", line 266, in <module>
92023-09-02T10:07:10.714202142Z     settings = Settings()
92023-09-02T10:07:10.714236495Z                ^^^^^^^^^^
W2023-09-02T10:07:10.714243364Z   File "/app/app/core/config.py", line 251, in __init__
62023-09-02T10:07:10.714364969Z     super().__init__()
z2023-09-02T10:07:10.714385544Z   File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
h2023-09-02T10:07:10.714520704Z   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
h2023-09-02T10:07:10.714660197Z pydantic.error_wrappers.ValidationError: 1 validation error for Settings
92023-09-02T10:07:10.714672422Z MEDIASERVER_SYNC_INTERVAL
X2023-09-02T10:07:10.714677559Z   value is not a valid integer (type=type_error.integer)
```

**Comment by amtoaer** [comment]
日志提示设置校验未通过： MEDIASERVER_SYNC_INTERVAL 必须是一个数字。
这个我最开始也踩了坑，以为把 MEDIASERVER_SYNC_INTERVAL 设置成空值就是“留空”的意思，但实际执行发现会报错，才知道这里的“留空”指的是不要写这条环境变量。

**Comment by Smart-zsw** [comment]
万分感谢，大佬！
