### ISSUE TITLE
[错误报告]: A request to the Telegram API was unsuccessful. Error code: 409

### ISSUE THREAD

**Issue by c939984606** [jxxghp/MoviePilot#400]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

A request to the Telegram API was unsuccessful. Error code: 409

### 问题类型

主程序运行问题

### 问题描述

A request to the Telegram API was unsuccessful. Error code: 409，后台日志疯狂报错

### 发生问题时系统日志和配置文件

```bash
【ERROR】2023-09-02 19:13:35,694 - __init__.py - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
【ERROR】2023-09-02 19:13:35,696 - __init__.py - Exception traceback:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 1073, in __threaded_polling
polling_thread.raise_exceptions()
File "/usr/local/lib/python3.11/site-packages/telebot/util.py", line 108, in raise_exceptions
raise self.exception_info
File "/usr/local/lib/python3.11/site-packages/telebot/util.py", line 90, in run
task(*args, **kwargs)
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 649, in __retrieve_updates
updates = self.get_updates(offset=(self.last_update_id + 1),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 623, in get_updates
json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/apihelper.py", line 321, in get_updates
return _make_request(token, method_url, params=payload)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/apihelper.py", line 162, in _make_request
json_result = _check_result(method_name, result)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/telebot/apihelper.py", line 189, in _check_result
raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
```

**Comment by jxxghp** [comment]
@c939984606 错误提示很明显了吧？

**Comment by c939984606** [comment]
> @c939984606 错误提示很明显了吧？

terminated by other getUpdates request; make sure that only one bot instance is running，不懂怎么解决，配置里只有一项tg设置，MOVIEPILOT_AUTO_UPDATE=true
![image](https://github.com/jxxghp/MoviePilot/assets/34211368/826485d2-2100-46ad-a1d9-9d97e84d4caa)

**Comment by jxxghp** [comment]
@c939984606 你这个bot在另外一个地方也用了，tg不允许在两个地方同时拉数据

**Comment by c939984606** [comment]
> @c939984606 你这个bot在另外一个地方也用了，tg不允许在两个地方同时拉数据

明白了，感谢
