### ISSUE TITLE
[错误报告]: 订阅刷新报错，应该是数据库写入报错，刚刚发现，之前几天订阅都没有问题

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#436]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.1.2

### 问题类型

主程序运行问题

### 问题描述

如图显示报错日志信息，今天早上更新了V1.1.2版本的时候，订阅突然报错，qb显示骄阳伴我的第十集已经下载，但是mp这边一直抛出数据库的异常信息，无法插入，导致无法进行后续订阅
<img width="1196" alt="2023-09-04 20 43 39" src="https://github.com/jxxghp/MoviePilot/assets/34505611/d06c83a8-bbe0-4848-a604-4cc372ce065a">

### 发生问题时系统日志和配置文件

```bash
[SQL: INSERT INTO downloadhistory (path, type, title, year, tmdbid, imdbid, tvdbid, doubanid, seasons, episodes, image, download_hash, torrent_name, torrent_description, torrent_site, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('骄阳伴我.Sunshine.by.My.Side.S01.2023.2160p.WEB-DL.H265.AAC-ADWeb', '电视剧', '骄阳伴我', '2023', 233571, 'tt28115920', 437513, None, 'S01', 'E10', 'https://image.tmdb.org/t/p/w500/7begpqVam3uMFuMQvmYGXYkAF8G.jpg', '47bddca6cd0c5f3434e76f9cadb420bd08596177', 'Sunshine by My Side S01E10 2023 2160p WEB-DL H265 AAC-DramaS@ADWeb', '骄阳伴我 第10集', '观众', None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a)
ERROR:   base.py - Job "订阅刷新 (trigger: cron[hour='20', minute='39'], next run at: 2023-09-05 20:39:00 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/chain/subscribe.py", line 381, in refresh
    subscribes = self.subscribeoper.list('R')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/subscribe_oper.py", line 57, in list
    return Subscribe.get_by_state(self._db, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/models/subscribe.py", line 72, in get_by_state
    return db.query(Subscribe).filter(Subscribe.state == state).all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2688, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2134, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 912, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO downloadhistory (path, type, title, year, tmdbid, imdbid, tvdbid, doubanid, seasons, episodes, image, download_hash, torrent_name, torrent_description, torrent_site, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('骄阳伴我.Sunshine.by.My.Side.S01.2023.2160p.WEB-DL.H265.AAC-ADWeb', '电视剧', '骄阳伴我', '2023', 233571, 'tt28115920', 437513, None, 'S01', 'E10', 'https://image.tmdb.org/t/p/w500/7begpqVam3uMFuMQvmYGXYkAF8G.jpg', '47bddca6cd0c5f3434e76f9cadb420bd08596177', 'Sunshine by My Side S01E10 2023 2160p WEB-DL H265 AAC-DramaS@ADWeb', '骄阳伴我 第10集', '观众', None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a)
INFO:     192.168.100.54:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/system/message?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1MDM0MzcsInN1YiI6IjEifQ.CYo1zGQf7JslP2cfOP9UHw88auhbJq2D534Y7Cwdg8c HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/schedule HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/transfer HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/storage HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/processes HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/statistic HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/system/logging?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTQ1MDM0MzcsInN1YiI6IjEifQ.CYo1zGQf7JslP2cfOP9UHw88auhbJq2D534Y7Cwdg8c HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/processes HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/processes HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/subscribe HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.100.54:0 - "GET /api/v1/subscribe/ HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/subscribe HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.100.54:0 - "GET /api/v1/subscribe/ HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/subscribe HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.100.54:0 - "GET /api/v1/subscribe/ HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/plugin HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.100.54:0 - "GET /api/v1/plugin/ HTTP/1.1" 200 OK
INFO:     192.168.100.54:0 - "GET /api/v1/subscribe HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.100.54:0 - "GET /api/v1/subscribe/ HTTP/1.1" 200 OK
ERROR:   base.py - Job "SubscribeChain.search (trigger: interval[0:05:00], next run at: 2023-09-04 20:48:43 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/chain/subscribe.py", line 185, in search
    subscribes = self.subscribeoper.list(state)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/subscribe_oper.py", line 57, in list
    return Subscribe.get_by_state(self._db, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/models/subscribe.py", line 72, in get_by_state
    return db.query(Subscribe).filter(Subscribe.state == state).all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2688, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2134, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 912, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO downloadhistory (path, type, title, year, tmdbid, imdbid, tvdbid, doubanid, seasons, episodes, image, download_hash, torrent_name, torrent_description, torrent_site, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('骄阳伴我.Sunshine.by.My.Side.S01.2023.2160p.WEB-DL.H265.AAC-ADWeb', '电视剧', '骄阳伴我', '2023', 233571, 'tt28115920', 437513, None, 'S01', 'E10', 'https://image.tmdb.org/t/p/w500/7begpqVam3uMFuMQvmYGXYkAF8G.jpg', '47bddca6cd0c5f3434e76f9cadb420bd08596177', 'Sunshine by My Side S01E10 2023 2160p WEB-DL H265 AAC-DramaS@ADWeb', '骄阳伴我 第10集', '观众', None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a)
INFO:    transfer.py - 开始执行下载器文件转移 ...
INFO:    transfer.py - 获取到 1 个已完成的下载任务
ERROR:   base.py - Job "下载文件整理 (trigger: interval[0:05:00], next run at: 2023-09-04 20:48:43 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/chain/transfer.py", line 63, in process
    downloadhis: DownloadHistory = self.downloadhis.get_by_hash(torrent.hash)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/downloadhistory_oper.py", line 25, in get_by_hash
    return DownloadHistory.get_by_hash(self._db, download_hash)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/models/downloadhistory.py", line 43, in get_by_hash
    return db.query(DownloadHistory).filter(DownloadHistory.download_hash == download_hash).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2743, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2134, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 912, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO downloadhistory (path, type, title, year, tmdbid, imdbid, tvdbid, doubanid, seasons, episodes, image, download_hash, torrent_name, torrent_description, torrent_site, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('骄阳伴我.Sunshine.by.My.Side.S01.2023.2160p.WEB-DL.H265.AAC-ADWeb', '电视剧', '骄阳伴我', '2023', 233571, 'tt28115920', 437513, None, 'S01', 'E10', 'https://image.tmdb.org/t/p/w500/7begpqVam3uMFuMQvmYGXYkAF8G.jpg', '47bddca6cd0c5f3434e76f9cadb420bd08596177', 'Sunshine by My Side S01E10 2023 2160p WEB-DL H265 AAC-DramaS@ADWeb', '骄阳伴我 第10集', '观众', None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a)
INFO:    cookiecloud.py - 开始同步CookieCloud站点 ...
ERROR:   base.py - Job "同步CookieCloud站点 (trigger: interval[0:10:00], next run at: 2023-09-04 20:54:43 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/chain/cookiecloud.py", line 73, in process
    indexer = self.siteshelper.get_indexer(domain)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "app/helper/sites.py", line 111, in app.helper.sites.SitesHelper.get_indexer
  File "/app/app/db/site_oper.py", line 58, in get_by_domain
    return Site.get_by_domain(self._db, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/models/site.py", line 51, in get_by_domain
    return db.query(Site).filter(Site.domain == domain).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2743, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2134, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 912, in _raise_for_prerequisite_state
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO downloadhistory (path, type, title, year, tmdbid, imdbid, tvdbid, doubanid, seasons, episodes, image, download_hash, torrent_name, torrent_description, torrent_site, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('骄阳伴我.Sunshine.by.My.Side.S01.2023.2160p.WEB-DL.H265.AAC-ADWeb', '电视剧', '骄阳伴我', '2023', 233571, 'tt28115920', 437513, None, 'S01', 'E10', 'https://image.tmdb.org/t/p/w500/7begpqVam3uMFuMQvmYGXYkAF8G.jpg', '47bddca6cd0c5f3434e76f9cadb420bd08596177', 'Sunshine by My Side S01E10 2023 2160p WEB-DL H265 AAC-DramaS@ADWeb', '骄阳伴我 第10集', '观众', None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) (Background on this error at: https://sqlalche.me/e/20/7s2a)
```

**Comment by yellowstrong** [comment]
目前发现可能造成的一个原因，我是先订阅的电视剧，只选择了一个站点，并且添加了一些条件类似官组、H265过滤，然后我执行了删除所有站点重新同步站点，之后订阅就出现了这个问题

**Comment by jxxghp** [comment]
上一次版本尝试优化了这个问题。如果仍会出现再提吧。
