### ISSUE TITLE
[错误报告]: 电影洗版同种子重复下载

### ISSUE THREAD

**Issue by evolsnow** [jxxghp/MoviePilot#591]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.0

### 问题类型

主程序运行问题

### 问题描述

- rss模式 5min
- 新电影订阅&开启洗版 -> 正常下载种子A -> 入库完成 -> 每五分钟重复下载同一个种子A

### 发生问题时系统日志和配置文件

```bash
INFO:    __init__.py - 种子 憨憨 - Once Upon a Crime 2023 1080p NF WEB-DL DDP5.1 H264-HHWEB[神探小红帽 | 1080p  | 类型: 喜剧/悬疑/犯罪 | 导演: 福田雄一 | 主演: 桥本环奈/新木优子/岩田刚典/室毅/佐藤二朗] 优先级为 6
INFO:    subscribe.py - 神探小红帽 (2023) 匹配成功：Once Upon a Crime 2023 1080p NF WEB-DL DDP5.1 H264-HHWEB[神探小红帽 | 1080p  | 类型: 喜剧/悬疑/犯罪 | 导演: 福田雄一 | 主演: 桥本环奈/新木优子/岩田刚典/室毅/佐藤二朗]
INFO:    subscribe.py - 神探小红帽 (2023) 匹配完成，共匹配到1个资源
INFO:    torrent.py - 解析种子：[HHC].Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.torrent => 目录：Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB，文件清单：['Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.mkv']
INFO:    __init__.py - 发送消息：channel=None，title=神探小红帽 (2023)  开始下载, text=站点：憨憨
INFO:    command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f422afcafc0>, <function WebHook.send at 0x7f422afb5760>]
ERROR:   telegram.py - 发送消息失败：A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message caption is too long
INFO:    command.py - 处理事件：download.added - [<function WebHook.send at 0x7f422afb5760>]
INFO:    subscribe.py - 神探小红帽 (2023) 正在洗版，更新资源优先级
INFO:    transfer.py - 开始执行下载器文件转移 ...
INFO:    transfer.py - 获取到 1 个已完成的下载任务
INFO:    tmdbapi.py - 正在查询TMDB电影：1122634 ...
INFO:    tmdbapi.py - 1122634 查询结果：神探小红帽
INFO:    __init__.py - 1122634 识别结果：电影 神探小红帽 (2023)
INFO:    transfer.py - Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.mkv 识别为：电影 神探小红帽 (2023)
ERROR:   base.py - Job "订阅刷新 (trigger: interval[0:05:00], next run at: 2023-09-14 17:28:15 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/chain/subscribe.py", line 381, in refresh
    sites = self.get_subscribed_sites()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/chain/subscribe.py", line 394, in get_subscribed_sites
    subscribes = self.subscribeoper.list('R')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/subscribe_oper.py", line 57, in list
    return Subscribe.get_by_state(self._db, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/db/models/subscribe.py", line 72, in get_by_state
    return db.query(Subscribe).filter(Subscribe.state == state).all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2688, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2262, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2134, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2001, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 929, in _raise_for_prerequisite_state
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is provisioning a new connection; concurrent operations are not permitted (Background on this error at: https://sqlalche.me/e/20/isce)
WARNING: __init__.py - 没有获取到 神探小红帽 (2023) 的Fanart图片数据
INFO:    tmdbapi.py - 正在获取电影图片：1122634...
INFO:    __init__.py - 正在转移文件：/mnt/ssd/MP/Movie/Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB/Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.mkv 到 /mnt/ssd/Media/电影/外语电影/神探小红帽 (2023)/神探小红帽 (2023) - WEB-DL.H264.DDP 5.1.1080p.mkv
INFO:    __init__.py - 文件 /mnt/ssd/MP/Movie/Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB/Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.mkv link完成
INFO:    __init__.py - 文件 /mnt/ssd/MP/Movie/Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB/Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.mkv 转移成功
INFO:    emby.py - 开始刷新Emby媒体库...
INFO:    __init__.py - 发送消息：channel=None，title=神探小红帽 (2023)  已入库, text=类型：电影，类别：外语电影，质量： WEB-DL 1080p，共1个文件，大小：4.91G，userid=None
INFO:    command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f422afcafc0>, <function WebHook.send at 0x7f422afb5760>]
INFO:    transfer.py - /mnt/ssd/MP/Movie/Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB/Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.mkv 转移完成，共 1 个文件，成功 1 个，失败 0 个
INFO:    command.py - 处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f422af98680>, <function WebHook.send at 0x7f422afb5760>]
INFO:    transfer.py - 下载器文件转移执行完成
INFO:    __init__.py - 神探小红帽 识别结果：电影 神探小红帽 (2023) 1122634
INFO:    __init__.py - 种子 憨憨 - Once Upon a Crime 2023 1080p NF WEB-DL DDP5.1 H264-HHWEB[神探小红帽 | 1080p  | 类型: 喜剧/悬疑/犯罪 | 导演: 福田雄一 | 主演: 桥本环奈/新木优子/岩田刚典/室毅/佐藤二朗] 优先级为 6
INFO:    subscribe.py - 神探小红帽 (2023) 匹配成功：Once Upon a Crime 2023 1080p NF WEB-DL DDP5.1 H264-HHWEB[神探小红帽 | 1080p  | 类型: 喜剧/悬疑/犯罪 | 导演: 福田雄一 | 主演: 桥本环奈/新木优子/岩田刚典/室毅/佐藤二朗]
INFO:    subscribe.py - 神探小红帽 (2023) 匹配完成，共匹配到1个资源
INFO:    torrent.py - 解析种子：[HHC].Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.torrent => 目录：Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB，文件清单：['Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.mkv']
ERROR:   download.py - 神探小红帽 (2023) 添加下载任务失败：Once Upon a Crime 2023 1080p NF WEB-DL DDP5.1 H264-HHWEB[神探小红帽 | 1080p  | 类型: 喜剧/悬疑/犯罪 | 导演: 福田雄一 | 主演: 桥本环奈/新木优子/岩田刚典/室毅/佐藤二朗] - https://hhanclub.top/download.php?id=56547&downhash=15390%7C5DGZ，添加种子任务失败：/config/temp/[HHC].Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.torrent
INFO:    __init__.py - 发送消息：channel=None，title=添加下载任务失败：神探小红帽 (2023) , text=站点：憨憨
种子名称：Once Upon a Crime 2023 1080p NF WEB-DL DDP5.1 H264-HHWEB[神探小红帽 | 1080p  | 类型: 喜剧/悬疑/犯罪 | 导演: 福田雄一 | 主演: 桥本环奈/新木优子/岩田刚典/室毅/佐藤二朗]
错误信息：添加种子任务失败：/config/temp/[HHC].Once.Upon.a.Crime.2023.1080p.NF.WEB-DL.DDP5.1.H264-HHWEB.torrent，userid=None
```

**Comment by evolsnow** [comment]
看了下user.db.subscribe表，current_priority居然是95，难道不应该如日志所说的6么

**Comment by jxxghp** [comment]
> 看了下user.db.subscribe表，current_priority是95

100减掉这个数就是界面上显示的优先级，实际上排序是按倒序的，值越大越前面。

你上面有数据库错误，重启下试试看是否还有重复的问题。

**Comment by WB-peter** [comment]
我也是这个问题啊，重复洗同个优先级的版
