### ISSUE TITLE
媒体文件同步删除插件报错

### ISSUE THREAD

**Issue by c77187326** [jxxghp/MoviePilot#723]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.7-1

### 问题类型

插件问题

### 问题描述

无论是emby_sync_del_nt还是webhooks方式 都无法同步删除源文件 ，emby版本版本 [4.8.0.48]。

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-10-02 22:50:36,700 - emby.py - 接收到emby webhook：{'Title': '封神第一部：朝歌风云 removed from Emby Server', 'Description': '《封神第一部：朝歌风云》是由乌尔善执导，费翔、李雪健、黄渤、娜然、于适、陈牧驰、此沙、武亚凡、夏雨、袁泉、王洛勇、侯雯元、黄曦彦、李昀锐、杨玏、陈坤出演的奇幻古装电影 ，于2023年7月20日在中国大陆上映。  讲述商王殷寿与狐妖妲己勾结，暴虐无道，引发天谴。昆仑仙人姜子牙携“封神榜”下山，寻找天下共主，以救苍生。西伯侯之子姬发逐渐发现殷寿的本来面目，反出朝歌。', 'Date': '2023-10-02T14:50:36.1963159Z', 'Event': 'library.deleted', 'Item': {'Name': '封神第一部：朝歌风云', 'OriginalTitle': '封神第一部：朝歌风云', 'ServerId': '699cccc0534a43be989a40752b55cfd6', 'Id': '523320', 'DateCreated': '2023-10-02T22:47:12.0000000Z', 'Container': 'mp4', 'SortName': '封神第一部：朝歌风云', 'PremiereDate': '2023-07-20T00:00:00.0000000Z', 'ExternalUrls': [{'Name': 'IMDb', 'Url': 'https://www.imdb.com/title/tt6979756'}, {'Name': 'TheMovieDb', 'Url': 'https://www.themoviedb.org/movie/856289'}, {'Name': 'TheTVDB', 'Url': 'https://thetvdb.com/dereferrer/movie/347697'}, {'Name': 'Trakt', 'Url': 'https://trakt.tv/search/tmdb/856289?id_type=movie'}], 'Path': '/media/hlink/电影/封神第一部：朝歌风云 (2023)/封神第一部：朝歌风云 (2023) - 1080p.mp4', 'Overview': '《封神第一部：朝歌风云》是由乌尔善执导，费翔、李雪健、黄渤、娜然、于适、陈牧驰、此沙、武亚凡、夏雨、袁泉、王洛勇、侯雯元、黄曦彦、李昀锐、杨玏、陈坤出演的奇幻古装电影 ，于2023年7月20日在中国大陆上映。  讲述商王殷寿与狐妖妲己勾结，暴虐无道，引发天谴。昆仑仙人姜子牙携“封神榜”下山，寻找天下共主，以救苍生。西伯侯之子姬发逐渐发现殷寿的本来面目，反出朝歌。', 'Taglines': [], 'Genres': [], 'CommunityRating': 7.5, 'RunTimeTicks': 89042730000, 'Size': 2857877719, 'FileName': '封神第一部：朝歌风云 (2023) - 1080p.mp4', 'Bitrate': 2567646, 'ProductionYear': 2023, 'RemoteTrailers': [{'Url': 'https://www.youtube.com/watch?v=wH6nlWl2MSQ'}, {'Url': 'https://www.youtube.com/watch?v=9osUW-WgpLU'}], 'ProviderIds': {'Tmdb': '856289', 'Imdb': 'tt6979756', 'Tvdb': '347697'}, 'IsFolder': False, 'ParentId': '487796', 'Type': 'Movie', 'Studios': [], 'GenreItems': [], 'TagItems': [], 'PrimaryImageAspectRatio': 0.6666666666666666, 'ImageTags': {'Primary': '4705ccb94ae8c2beec955faf5f0afc0b', 'Logo': '0668b36982ef4b4ab95adc765125fb27'}, 'BackdropImageTags': ['e98d396d35b6d86783ca639869993012'], 'MediaType': 'Video', 'Width': 1920, 'Height': 1040}, 'Server': {'Name': 'JT-embyserver', 'Id': '699cccc0534a43be989a40752b55cfd6', 'Version': '4.8.0.48'}}
【ERROR】2023-10-02 22:50:36,775 - emby.py - Items/RemoteImages 未获取到返回数据
【INFO】2023-10-02 22:50:36,787 - command.py - 处理事件：webhook.message - [<function BestFilmVersion.webhook_message_action at 0x7f2b25e26f20>, <function MediaSyncDel.sync_del_by_webhook at 0x7f2b258b87c0>, <function MediaSyncDel.sync_del_by_plugin at 0x7f2b258b8860>, <function SpeedLimiter.check_playing_sessions at 0x7f2b258f1760>, <function WebHook.send at 0x7f2b2590c2c0>]
【ERROR】2023-10-02 22:50:36,822 - command.py - 事件处理出错：list index out of range - Traceback (most recent call last):
  File "/app/app/command.py", line 181, in __run
    self.pluginmanager.run_plugin_method(names[0], names[1], event)
  File "/app/app/core/plugin.py", line 178, in run_plugin_method
    return getattr(self._running_plugins[pid], method)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/mediasyncdel/__init__.py", line 473, in sync_del_by_webhook
    self.__sync_del(media_type=media_type,
  File "/app/app/plugins/mediasyncdel/__init__.py", line 554, in __sync_del
    msg, transfer_history = self.__get_transfer_his(media_type=media_type,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/mediasyncdel/__init__.py", line 676, in __get_transfer_his
    media_path = media_path.replace(sub_paths[0], sub_paths[1]).replace('\\', '/')
                                                  ~~~~~~~~~^^^
IndexError: list index out of range

【ERROR】2023-10-02 22:50:36,835 - command.py - 事件处理出错：'WebhookEventInfo' object has no attribute 'items' - Traceback (most recent call last):
  File "/app/app/command.py", line 181, in __run
    self.pluginmanager.run_plugin_method(names[0], names[1], event)
  File "/app/app/core/plugin.py", line 178, in run_plugin_method
    return getattr(self._running_plugins[pid], method)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/webhook/__init__.py", line 150, in send
    "data": __to_dict(event.event_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/webhook/__init__.py", line 141, in __to_dict
    for key, value in _event.items():
                      ^^^^^^^^^^^^
AttributeError: 'WebhookEventInfo' object has no attribute 'items'
```

**Comment by jxxghp** [comment]
路径配置的有问题？
![image](https://github.com/jxxghp/MoviePilot/assets/51039935/7a94a0c1-bbfc-4c54-aee1-fe1c1771e817)
