### ISSUE TITLE
[错误报告]: 无法转移非moviepilot下载任务

### ISSUE THREAD

**Issue by jimlee2002** [jxxghp/MoviePilot#742]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.8

### 问题类型

主程序运行问题

### 问题描述

无法手动整理非moviepilot下载的视频。能够正常识别结果但无法转移。

我的环境：
```docker-compose.yml
services:
  moviepilot:
    environment:
      - PUID=1026
      - PGID=101
      - DOWNLOAD_PATH=/downloads/PT # 与qb内设置的默认下载路径对应
      - TORRENT_TAG=MOVIEPILOT
      - LIBRARY_PATH=/media
      - LIBRARY_MOVIE_NAME=Movies
      - LIBRARY_TV_NAME=TV
      - LIBRARY_ANIME_NAME=Anime
      - TRANSFER_TYPE=link
    volumes:
      - moviepilot_data:/config # 单独volume，用于备份配置数据
      - /volume2/Video:/media
      - /volume2/Downloads:/downloads # 容器挂载整个下载文件夹
 
  qbittorrent:
    network_mode: host
    environment:
      - PUID=1026
      - PGID=101
    volumes:
      - /volume2/Downloads:/downloads # 容器挂载整个下载文件夹，qb内设置的默认下载路径为`/downloads/PT`
      - /volume1/temp:/downloads/incomplete

volumes:
  moviepilot_data:
    name: moviepilot_data
```
![image](https://github.com/jxxghp/MoviePilot/assets/21117946/9ecdeda8-c1a7-4b27-9f32-86126dd97060)

供测试的问题种子BT磁链：

```
magnet:?xt=urn:btih:3d54e71bc8db90dc90a44f16eed8616a72e2c1ea&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce
magnet:?xt=urn:btih:879b04125727dde7915503bc1ef9fceea24bed18&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce
magnet:?xt=urn:btih:50322d16c79312ea4fa7277144d0e6f6cc5a10fb&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce
magnet:?xt=urn:btih:d523f5c852a76023275bd47d7bad86c5735bcf06&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce
```

### 发生问题时系统日志和配置文件

```bash
INFO:    transfer.py - 手动转移：/media/downloads/AutoBangumi/Frieren  Beyond Journey's End (2023) ...
INFO:     172.26.0.1:0 - "GET /api/v1/system/progress/filetransfer?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTcyOTU5NzgsInN1YiI6IjEifQ.fYBAOFD1UHBmGPSidscOemKkQ_Qyy4TGC6ksNml1xME HTTP/1.1" 200 OK
INFO:    __init__.py - Sousou No Frieren 使用识别缓存：葬送的芙莉莲
INFO:    tmdbapi.py - 正在查询TMDB电视剧：209867 ...
INFO:    tmdbapi.py - 209867 查询结果：葬送的芙莉莲
INFO:    __init__.py - Sousou No Frieren 识别结果：电视剧 葬送的芙莉莲 (2023) 209867
INFO:    tmdbapi.py - 正在获取剧集组年份：64f988c1ffc9de00c4a24917...
INFO:    tmdbapi.py - 正在查询TMDB电视剧：209867，季：1 ...
INFO:    transfer.py - [Sakurato] Sousou no Frieren [04][HEVC-10bit 1080p AAC][CHS&CHT].mkv 识别为：电视剧 葬送的芙莉莲 (2023)
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 90, in run_module
    result = func(*args, **kwargs)
  File "/app/app/modules/filetransfer/__init__.py", line 56, in transfer
             ^^^^^^^^^^^^^^^^^^^^^
    return self.transfer_media(in_path=path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filetransfer/__init__.py", line 446, in transfer_media
  File "/app/app/modules/filetransfer/__init__.py", line 554, in get_rename_path
    new_file = self.get_rename_path(
               ^^^^^^^^^^^^^^^^^^^^^
    template = Template(template_string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
    return env.from_string(source, template_class=cls)
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1208, in __new__
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return cls.from_code(self, self.compile(source), gs, None)
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1105, in from_string
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
                               ^^^^^^^^^^^^^^^^^^^^
    self.handle_exception(source=source_hint)
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'.
ERROR:   __init__.py - 运行模块 transfer 出错：FileTransferModule - Encountered unknown tag 'endif'.
ERROR:   transfer.py - 文件转移模块运行失败
```

**Comment by jimlee2002** [comment]
解决了，我自己定义的自定义重命名规则有语法错误。
