### ISSUE TITLE
媒体文件同步删除提示  未解析到已删除媒体信息

### ISSUE THREAD

**Issue by yangsheng1994** [jxxghp/MoviePilot#766]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.9

### 问题类型

插件问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/95394538/6b1fa7e0-3d6a-4f95-8180-42f47ddc80a9)
![image](https://github.com/jxxghp/MoviePilot/assets/95394538/e4bad3fe-3e30-475b-ad56-0af206909997)
![image](https://github.com/jxxghp/MoviePilot/assets/95394538/e1e767c6-f646-4ed8-b377-c314e611c254)
![image](https://github.com/jxxghp/MoviePilot/assets/95394538/98e74e55-06c4-46e5-9b8c-eb46acdd5564)

群晖
无论jellyfin还是emby 模式选择日志
只有第一次添加改插件是能解析到删除记录  后面就一直报错 未解析到已删除媒体信息
查看jellyfin和emby有删除记录
删了重建容器，换过媒体库，仍旧没有解决，不知道大佬们有同样的情况吗？或者大佬们给点排查意见，实在不知道怎么解决。

### 发生问题时系统日志和配置文件

```bash
2023-10-09T01:50:00.297058927Z ERROR:   __init__.py - 未解析到已删除媒体信息
2023-10-09T01:50:18.953223003Z INFO:     172.17.0.1:0 - "GET /api/v1/history/transfer?page=1&count=25&title= HTTP/1.1" 200 OK
2023-10-09T01:50:20.918744506Z INFO:     172.17.0.1:0 - "GET /api/v1/system/env HTTP/1.1" 200 OK
2023-10-09T01:50:21.156095459Z INFO:     172.17.0.1:0 - "GET /api/v1/filebrowser/list?path=%2F&sort=name HTTP/1.1" 200 OK
2023-10-09T01:50:21.156241279Z INFO:     172.17.0.1:0 - "GET /api/v1/filebrowser/list?path=%2Fmedia%2Fvideo%2F%E4%B8%8B%E8%BD%BD%2F&sort=name HTTP/1.1" 200 OK
2023-10-09T01:50:22.534214323Z INFO:     172.17.0.1:0 - "GET /api/v1/plugin/ HTTP/1.1" 200 OK
2023-10-09T01:50:23.558239809Z INFO:     172.17.0.1:0 - "GET /api/v1/plugin/page/MediaSyncDel HTTP/1.1" 200 OK
2023-10-09T01:50:25.736094189Z INFO:     172.17.0.1:0 - "GET /api/v1/plugin/form/MediaSyncDel HTTP/1.1" 200 OK
2023-10-09T01:50:25.745806231Z INFO:     172.17.0.1:0 - "GET /api/v1/plugin/MediaSyncDel HTTP/1.1" 200 OK
2023-10-09T01:51:14.527272002Z INFO:    transfer.py - 开始执行下载器文件转移 ...
2023-10-09T01:51:14.537580754Z INFO:    transfer.py - 没有获取到已完成的下载任务
2023-10-09T01:55:00.276474091Z ERROR:   __init__.py - 未解析到已删除媒体信息
2023-10-09T01:56:14.527242839Z INFO:    transfer.py - 开始执行下载器文件转移 ...
2023-10-09T01:56:14.540664209Z INFO:    transfer.py - 没有获取到已完成的下载任务
2023-10-09T01:59:16.856938623Z INFO:     172.17.0.1:0 - "GET /api/v1/system/logging?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc1MDY2MTcsInN1YiI6IjEifQ.OQrNkKOBMJcxE-Tp1ffi7w9TV0KQnWNuIPX08kJXekc HTTP/1.1" 200 OK
2023-10-09T01:59:33.298875811Z INFO:     172.17.0.1:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
2023-10-09T01:59:33.309168471Z INFO:     172.17.0.1:0 - "GET /api/v1/user/ HTTP/1.1" 200 OK
2023-10-09T01:59:34.632914582Z INFO:     172.17.0.1:0 - "GET /api/v1/system/env HTTP/1.1" 200 OK
2023-10-09T01:59:34.962946890Z INFO:     172.17.0.1:0 - "GET /api/v1/system/versions HTTP/1.1" 200 OK
2023-10-09T01:59:53.762796147Z INFO:     172.17.0.1:0 - "GET /api/v1/system/logging?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc1MDY2MTcsInN1YiI6IjEifQ.OQrNkKOBMJcxE-Tp1ffi7w9TV0KQnWNuIPX08kJXekc HTTP/1.1" 200 OK
2023-10-09T01:59:55.738203832Z INFO:     172.17.0.1:0 - "GET /api/v1/plugin/ HTTP/1.1" 200 OK
2023-10-09T02:00:00.329932365Z ERROR:   __init__.py - 未解析到已删除媒体信息
2023-10-09T02:00:14.047050908Z INFO:     172.17.0.1:0 - "GET /api/v1/system/logging?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc1MDY2MTcsInN1YiI6IjEifQ.OQrNkKOBMJcxE-Tp1ffi7w9TV0KQnWNuIPX08kJXekc HTTP/1.1" 200 OK
```

**Comment by thsrite** [comment]
没问题，只处理一次，处理完保存当前时间到数据库，
下载只获取上次处理时间以后的删除数据，防止每次都重复处理

**Comment by yangsheng1994** [comment]
> 没问题，只处理一次，处理完保存当前时间到数据库， 下载只获取上次处理时间以后的删除数据，防止每次都重复处理

![image](https://github.com/jxxghp/MoviePilot/assets/95394538/8e8d9320-2f77-4882-8b68-b2e1f71636ce)
![image](https://github.com/jxxghp/MoviePilot/assets/95394538/2b4fce4b-75e5-409f-9c76-0bf5835735dd)

谢谢回复 但好像仍有问题 刚刚测试了一次
新添加到媒体库后删除  jellyfin日志中有记录  但是mp仍报错

**Comment by thsrite** [comment]
jellyfin日志删除媒体部分 发下文本

**Comment by yangsheng1994** [comment]
> jellyfin日志删除媒体部分 发下文本

[2023-10-09 02:49:58.631 +00:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Webhook Item Added Notifier"
[2023-10-09 02:49:58.631 +00:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "ItemAddedScheduledTask"
[2023-10-09 02:49:58.631 +00:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Webhook Item Added Notifier"
[2023-10-09 02:49:58.632 +00:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2023-10-09 02:49:58.633 +00:00] [INF] [11] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2023-10-09 02:50:00.666 +00:00] [WRN] [13] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.8.124:8096/Users/f72b90189b3b4f69bd982d0ad07f1907/Items/Latest?Limit=12&ParentId=3227ce1e069754c594af25ea66d69fc7" to "192.168.8.124" in 0:00:00.5692664 with Status Code 200
[2023-10-09 02:50:10.596 +00:00] [INF] [23] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "茶啊二中", Path: "/media/电影/茶啊二中 (2023)/茶啊二中 (2023) - 2160p.mkv", Id: 1058915b-d154-6e9e-9088-f1270af494ff
[2023-10-09 02:50:10.597 +00:00] [INF] [23] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Movie", Name: "茶啊二中", Path: "/media/电影/茶啊二中 (2023)", Id: 1058915b-d154-6e9e-9088-f1270af494ff
[2023-10-09 02:50:11.787 +00:00] [WRN] [23] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.8.124:8096/Items/1058915bd1546e9e9088f1270af494ff" to "172.17.0.1" in 0:00:01.1934417 with Status Code 204
[2023-10-09 02:50:16.786 +00:00] [INF] [28] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Started library sync
[2023-10-09 02:50:17.118 +00:00] [INF] [28] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Library Sync: Removed 1 items
[2023-10-09 02:50:17.118 +00:00] [INF] [28] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished library sync, taking "00:00:00.3312441"
[2023-10-09 02:50:28.632 +00:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: "IntervalTrigger" fired for task: "Webhook Item Added Notifier"
[2023-10-09 02:50:28.633 +00:00] [INF] [31] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task "ItemAddedScheduledTask"
[2023-10-09 02:50:28.633 +00:00] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Webhook Item Added Notifier"
[2023-10-09 02:50:28.633 +00:00] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Webhook Item Added Notifier" Completed after 0 minute(s) and 0 seconds
[2023-10-09 02:50:28.634 +00:00] [INF] [21] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks

**Comment by thsrite** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/54088512/e43f2e5a-a52d-416c-9b75-4db6cc258e8b)
截图看下日志这里

**Comment by yangsheng1994** [comment]
> ![image](https://user-images.githubusercontent.com/54088512/273490384-e43f2e5a-a52d-416c-9b75-4db6cc258e8b.png) 截图看下日志这里

![image](https://github.com/jxxghp/MoviePilot/assets/95394538/621b8058-18ea-4b73-905c-cd6e3d7a8eab)
![image](https://github.com/jxxghp/MoviePilot/assets/95394538/fb72d808-6ac0-4d04-acc0-26ae56fbb795)
Application path: /system
NetVips.VipsException: NetVips.VipsException: unable to load from file /media/电影/茶啊二中 (2023)/folder.jpg
VipsForeignLoad: file "/media/电影/茶啊二中 (2023)/folder.jpg" does not exist
at NetVips.Image.NewFromFile(String vipsFilename, Nullable`1 memory, Nullable`1 access, Nullable`1 failOn, VOption kwargs)
at Emby.Drawing.LibVips.LibVipsImageProcessor.LoadImage(String path)
at Emby.Drawing.LibVips.LibVipsImageProcessor.GetImageSize(String path)
at Emby.Drawing.ImageProcessor.GetImageSizeFromImageEncoders(String path, String format, Boolean requiresOrientation, Boolean logException)
Source: NetVips
TargetSite: NetVips.Image NewFromFile(System.String, System.Nullable`1[System.Boolean], System.Nullable`1[NetVips.Enums+Access], System.Nullable`1[NetVips.Enums+FailOn], NetVips.VOption)
2023-10-09 02:51:10.225 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 02:51:10.609 Info LibraryMonitor: 电影 (/media/电影) will be refreshed.
2023-10-09 02:51:10.626 Info LibraryMonitor: 电影 (/media/电影) will be refreshed.
2023-10-09 02:51:10.666 Info App: Removing item from database, Type: Folder, Name: 茶啊二中 (2023), Path: /media/电影/茶啊二中 (2023), Id: 3311
2023-10-09 02:51:10.671 Info App: Deleting path /config/metadata/library/83/8335af2bdbb767af0273150f5a9931f9
2023-10-09 02:51:10.672 Info App: Deleting path /config/metadata/library/83/8335af2bdbb767af0273150f5a9931f9
2023-10-09 02:51:10.672 Info App: Deleting path /config/metadata/library/10/1058915bd1546e9e9088f1270af494ff
2023-10-09 02:51:55.213 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 03:24:52.948 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 03:25:57.649 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)

**Comment by yangsheng1994** [comment]
刚在emby里删除了一下

2023-10-09 02:51:10.225 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 02:51:10.609 Info LibraryMonitor: 电影 (/media/电影) will be refreshed.
2023-10-09 02:51:10.626 Info LibraryMonitor: 电影 (/media/电影) will be refreshed.
2023-10-09 02:51:10.666 Info App: Removing item from database, Type: Folder, Name: 茶啊二中 (2023), Path: /media/电影/茶啊二中 (2023), Id: 3311
2023-10-09 02:51:10.671 Info App: Deleting path /config/metadata/library/83/8335af2bdbb767af0273150f5a9931f9
2023-10-09 02:51:10.672 Info App: Deleting path /config/metadata/library/83/8335af2bdbb767af0273150f5a9931f9
2023-10-09 02:51:10.672 Info App: Deleting path /config/metadata/library/10/1058915bd1546e9e9088f1270af494ff
2023-10-09 02:51:55.213 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 03:24:52.948 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 03:25:57.649 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 03:27:56.605 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 03:32:45.013 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 03:32:46.909 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 03:32:46.996 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
2023-10-09 03:32:50.905 Info Server: http/1.1 POST http://host1:1111/emby/Items/Delete?Ids=1111&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=3873f589-e1ca-4195-b91a-a7bac56859c6&X-Emby-Client-Version=4.8.0.51&X-Emby-Token=x_secret1_x&X-Emby-Language=zh-cn. UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
2023-10-09 03:32:50.964 Info App: Removing item from database, Type: Episode, Name: 砍你丫的！, Path: /media/动漫/沧元图 (2023)/Season 1/沧元图 - S01E04 - 第4集.mp4, Id: 1111
2023-10-09 03:32:50.974 Info App: Deleting file /media/动漫/沧元图 (2023)/Season 1/沧元图 - S01E04 - 第4集.mp4
2023-10-09 03:32:51.015 Info App: Deleting file /media/动漫/沧元图 (2023)/Season 1/沧元图 - S01E04 - 第4集.nfo
2023-10-09 03:32:51.018 Info App: Deleting path /config/metadata/library/70/705a995093b430afab25bc7b684cc8a4
2023-10-09 03:32:51.019 Info Server: http/1.1 Response 204 to host2. Time: 114ms. POST http://host1:1111/emby/Items/Delete?Ids=1111&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=3873f589-e1ca-4195-b91a-a7bac56859c6&X-Emby-Client-Version=4.8.0.51&X-Emby-Token=x_secret1_x&X-Emby-Language=zh-cn
2023-10-09 03:32:51.102 Info App: Sqlite: 284 - automatic index on LastWatchedEpisodes(SeriesPresentationUniqueKey)
