### ISSUE TITLE
[错误报告]: Win版站点自动签到无法使用

### ISSUE THREAD

**Issue by LeePhe** [jxxghp/MoviePilot#883]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.4

### 问题类型

插件问题

### 问题描述

Win版站点自动签到无法使用

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-10-16 19:43:35,168 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2023-10-16 19:43:42,714 - transfer.py - 没有获取到已完成的下载任务
【INFO】2023-10-16 19:47:02,296 - autosignin - 站点自动签到服务启动，立即运行一次
【INFO】2023-10-16 19:47:02,305 - autosignin - 站点自动签到服务启动，执行周期 23 3 * * *
【ERROR】2023-10-16 19:47:05,306 - base.py - Job "站点自动签到 (trigger: date[2023-10-16 19:47:05 CST], next run at: 2023-10-16 19:47:05 CST)" raised an exception
Traceback (most recent call last):
  File "sqlalchemy\engine\base.py", line 1969, in _exec_single_context
  File "sqlalchemy\engine\default.py", line 922, in do_execute
sqlite3.OperationalError: no such table: plugindata

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apscheduler\executors\base.py", line 125, in run_job
  File "app\plugins\autosignin\__init__.py", line 585, in sign_in
  File "app\plugins\autosignin\__init__.py", line 596, in __do
  File "app\plugins\__init__.py", line 176, in del_data
  File "app\db\plugindata_oper.py", line 52, in del_data
  File "app\db\models\plugin.py", line 26, in del_plugin_data_by_key
  File "sqlalchemy\orm\query.py", line 3181, in delete
  File "sqlalchemy\orm\session.py", line 2306, in execute
  File "sqlalchemy\orm\session.py", line 2188, in _execute_internal
  File "sqlalchemy\orm\bulk_persistence.py", line 1946, in orm_execute_statement
  File "sqlalchemy\orm\context.py", line 293, in orm_execute_statement
  File "sqlalchemy\engine\base.py", line 1416, in execute
  File "sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
  File "sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
  File "sqlalchemy\engine\base.py", line 1848, in _execute_context
  File "sqlalchemy\engine\base.py", line 1988, in _exec_single_context
  File "sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
  File "sqlalchemy\engine\base.py", line 1969, in _exec_single_context
  File "sqlalchemy\engine\default.py", line 922, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: plugindata
[SQL: DELETE FROM plugindata WHERE plugindata.plugin_id = ? AND plugindata."key" = ?]
[parameters: ('AutoSignIn', '签到-2023-10-15')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by Yustyn555** [comment]
同无法签到，大佬说暂时不支持仿真

**Comment by Sajotim** [comment]
1.4.6也有一样的问题，日志相同
